# Generated by Django 6.0.5 on 2026-05-18 12:25

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_id', models.IntegerField(blank=True, null=True)),
                ('loan_account_no', models.BigIntegerField(blank=True, null=True)),
                ('collection_officer_code', models.CharField(blank=True, max_length=100, null=True)),
                ('collection_officer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('contactibility', models.CharField(blank=True, max_length=100, null=True)),
                ('reasons_for_default', models.CharField(blank=True, max_length=255, null=True)),
                ('outcomes', models.CharField(blank=True, max_length=255, null=True)),
                ('foreclosure_outcomes', models.CharField(blank=True, max_length=255, null=True)),
                ('ptp_amount', models.BigIntegerField(blank=True, null=True)),
                ('profiling', models.CharField(blank=True, max_length=255, null=True)),
                ('next_action', models.CharField(blank=True, max_length=255, null=True)),
                ('next_action_date', models.DateField(blank=True, null=True)),
                ('additional_comments', models.TextField(blank=True, null=True)),
                ('additional_contacts_1', models.CharField(blank=True, max_length=100, null=True)),
                ('additional_contacts_2', models.CharField(blank=True, max_length=100, null=True)),
                ('additional_contacts_3', models.CharField(blank=True, max_length=100, null=True)),
                ('recording_date', models.DateField(default=django.utils.timezone.now)),
                ('collection_status', models.CharField(default='closed', max_length=50)),
            ],
            options={
                'db_table': 'hf_collections_feedback',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HistoricalCollection',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('cust_id', models.IntegerField(blank=True, null=True)),
                ('loan_account_no', models.BigIntegerField(blank=True, null=True)),
                ('collection_officer_code', models.CharField(blank=True, max_length=100, null=True)),
                ('collection_officer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('contactibility', models.CharField(blank=True, max_length=100, null=True)),
                ('reasons_for_default', models.CharField(blank=True, max_length=255, null=True)),
                ('outcomes', models.CharField(blank=True, max_length=255, null=True)),
                ('foreclosure_outcomes', models.CharField(blank=True, max_length=255, null=True)),
                ('ptp_amount', models.BigIntegerField(blank=True, null=True)),
                ('profiling', models.CharField(blank=True, max_length=255, null=True)),
                ('next_action', models.CharField(blank=True, max_length=255, null=True)),
                ('next_action_date', models.DateField(blank=True, null=True)),
                ('additional_comments', models.TextField(blank=True, null=True)),
                ('additional_contacts_1', models.CharField(blank=True, max_length=100, null=True)),
                ('additional_contacts_2', models.CharField(blank=True, max_length=100, null=True)),
                ('additional_contacts_3', models.CharField(blank=True, max_length=100, null=True)),
                ('recording_date', models.DateField(default=django.utils.timezone.now)),
                ('collection_status', models.CharField(default='closed', max_length=50)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical collection',
                'verbose_name_plural': 'historical collections',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
