# Generated by Django 6.0.5 on 2026-05-18 12:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hf_collections', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='recording_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='historicalcollection',
            name='recording_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
