# Generated by Django 4.2.20 on 2026-08-07 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalReferral',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('referral_ref', models.CharField(blank=True, db_index=True, max_length=40)),
                ('pf_number', models.CharField(max_length=30)),
                ('sales_code', models.CharField(blank=True, max_length=50)),
                ('staff_verified', models.BooleanField(blank=True, null=True)),
                ('verified_staff_name', models.CharField(blank=True, max_length=200)),
                ('customer_name', models.CharField(max_length=200)),
                ('national_id', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('unallocated', 'Unallocated'), ('allocated', 'Allocated'), ('contacted', 'Contacted'), ('converted', 'Converted'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='unallocated', max_length=20)),
                ('allocated_at', models.DateTimeField(blank=True, null=True)),
                ('contacted_at', models.DateTimeField(blank=True, null=True)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_possible_duplicate', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('allocated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical referral',
                'verbose_name_plural': 'historical referrals',
                'db_table': 'referrals_history',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('referral_ref', models.CharField(blank=True, max_length=40, unique=True)),
                ('pf_number', models.CharField(max_length=30)),
                ('sales_code', models.CharField(blank=True, max_length=50)),
                ('staff_verified', models.BooleanField(blank=True, null=True)),
                ('verified_staff_name', models.CharField(blank=True, max_length=200)),
                ('customer_name', models.CharField(max_length=200)),
                ('national_id', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('unallocated', 'Unallocated'), ('allocated', 'Allocated'), ('contacted', 'Contacted'), ('converted', 'Converted'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='unallocated', max_length=20)),
                ('allocated_at', models.DateTimeField(blank=True, null=True)),
                ('contacted_at', models.DateTimeField(blank=True, null=True)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_possible_duplicate', models.BooleanField(default=False)),
                ('allocated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals_allocated', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals_assigned', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'referrals',
                'ordering': ['-created_at'],
                'managed': True,
                'indexes': [models.Index(fields=['status'], name='referrals_status_135a0e_idx'), models.Index(fields=['national_id'], name='referrals_nationa_582dcc_idx'), models.Index(fields=['phone'], name='referrals_phone_9943b6_idx'), models.Index(fields=['assigned_to'], name='referrals_assigne_828ba3_idx'), models.Index(fields=['created_by'], name='referrals_created_716e23_idx')],
            },
        ),
    ]
