# Generated by Django 4.2.20 on 2026-08-07 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0003_historicalreferral_branch_historicalreferral_segment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalreferral',
            name='department',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='referral',
            name='department',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
