# Generated by Django 4.2.20 on 2026-08-21 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0004_historicalreferral_department_referral_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalreferral',
            name='assigned_sales_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='referral',
            name='assigned_sales_code',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
