# Generated by Django 4.2.20 on 2026-09-23 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Surface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('prompt', models.TextField()),
                ('spec', models.JSONField(default=dict)),
                ('visibility', models.CharField(choices=[('private', 'Only me'), ('shared', 'Anyone signed in')], default='private', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surfaces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'surface',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['visibility', '-updated_at'], name='surface_visibil_740d25_idx')],
            },
        ),
    ]
