# Generated by Django 4.2.20 on 2026-08-03 06:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StrategyTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(choices=[('deposits', 'Total Deposits'), ('loans', 'Total Loans'), ('nfi', 'Non-Funded Income'), ('interest_income', 'Interest Income'), ('interest_expense', 'Interest Expense'), ('revenue', 'Total Revenue'), ('customers', 'Total Customers'), ('new_customers', 'New Customers'), ('digital_active', 'Digital Active Customers')], max_length=32)),
                ('scope_type', models.CharField(choices=[('bank', 'Bank-wide'), ('segment', 'Segment'), ('branch', 'Branch'), ('rm', 'Relationship Manager')], default='bank', max_length=16)),
                ('scope_value', models.CharField(blank=True, default='', max_length=120)),
                ('period_type', models.CharField(choices=[('annual', 'Annual'), ('quarterly', 'Quarterly'), ('monthly', 'Monthly')], default='annual', max_length=16)),
                ('year', models.PositiveIntegerField()),
                ('quarter', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('target_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bp_strategy_target',
                'ordering': ['metric', '-year', '-quarter', '-month'],
            },
        ),
        migrations.AddConstraint(
            model_name='strategytarget',
            constraint=models.UniqueConstraint(fields=('metric', 'scope_type', 'scope_value', 'period_type', 'year', 'quarter', 'month'), name='uniq_strategy_target'),
        ),
    ]
