# Generated by Django 4.2.20 on 2026-09-30 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business_performance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalBankingSectorPosition',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('period', models.CharField(db_index=True, help_text="The CBK period, e.g. '2026-Q2'. Sorts correctly as text.", max_length=20)),
                ('bank_name', models.CharField(db_index=True, max_length=255)),
                ('is_us', models.BooleanField(default=False, help_text="True on HF Group's own row, so a chart can highlight it.")),
                ('total_assets', models.DecimalField(blank=True, decimal_places=2, max_digits=22, null=True)),
                ('total_deposits', models.DecimalField(blank=True, decimal_places=2, max_digits=22, null=True)),
                ('total_loans', models.DecimalField(blank=True, decimal_places=2, max_digits=22, null=True)),
                ('profit_before_tax', models.DecimalField(blank=True, decimal_places=2, max_digits=22, null=True)),
                ('market_share_pct', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('tier', models.CharField(blank=True, help_text='CBK tier: 1, 2 or 3.', max_length=20)),
                ('branches', models.IntegerField(blank=True, null=True)),
                ('npl_ratio_pct', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('source', models.CharField(blank=True, help_text='Which CBK release this row came from, so a figure can be traced.', max_length=255)),
                ('recorded_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Banking sector position',
                'verbose_name_plural': 'historical Banking sector positions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='BankingSectorPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(db_index=True, help_text="The CBK period, e.g. '2026-Q2'. Sorts correctly as text.", max_length=20)),
                ('bank_name', models.CharField(db_index=True, max_length=255)),
                ('is_us', models.BooleanField(default=False, help_text="True on HF Group's own row, so a chart can highlight it.")),
                ('total_assets', models.DecimalField(blank=True, decimal_places=2, max_digits=22, null=True)),
                ('total_deposits', models.DecimalField(blank=True, decimal_places=2, max_digits=22, null=True)),
                ('total_loans', models.DecimalField(blank=True, decimal_places=2, max_digits=22, null=True)),
                ('profit_before_tax', models.DecimalField(blank=True, decimal_places=2, max_digits=22, null=True)),
                ('market_share_pct', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('tier', models.CharField(blank=True, help_text='CBK tier: 1, 2 or 3.', max_length=20)),
                ('branches', models.IntegerField(blank=True, null=True)),
                ('npl_ratio_pct', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('source', models.CharField(blank=True, help_text='Which CBK release this row came from, so a figure can be traced.', max_length=255)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Banking sector position',
                'verbose_name_plural': 'Banking sector positions',
                'db_table': 'bp_banking_sector_position',
                'ordering': ['-period', '-total_assets'],
                'managed': True,
                'unique_together': {('period', 'bank_name')},
            },
        ),
    ]
