# Generated by Django 6.0.5 on 2026-06-21 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exco_innitiatives', '0002_strategicexcoowner_strategicinitiative_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='strategicexcoowner',
            options={'managed': True, 'ordering': ['owner_name']},
        ),
        migrations.AlterModelOptions(
            name='strategicinitiative',
            options={'managed': True, 'ordering': ['-recording_date']},
        ),
        migrations.AlterModelOptions(
            name='strategicmilestone',
            options={'managed': True, 'ordering': ['-recording_date']},
        ),
        migrations.AlterModelOptions(
            name='strategicthrust',
            options={'managed': True, 'ordering': ['-recording_date']},
        ),
    ]
