# Generated by Django 4.2.20 on 2026-07-15 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_no', models.CharField(db_index=True, max_length=64, unique=True)),
                ('customer_name', models.CharField(max_length=255)),
                ('account_no', models.CharField(blank=True, db_index=True, max_length=64)),
                ('file_type', models.CharField(choices=[('general', 'General'), ('loan', 'Loan'), ('mortgage', 'Mortgage'), ('aof', 'Account Opening')], default='general', max_length=16)),
                ('retention_class', models.CharField(blank=True, choices=[('seven_year', 'Seven years'), ('life', 'Entire life')], help_text='Auto-set from file type when blank: mortgage/AOF = life, else seven years.', max_length=16)),
                ('opened_on', models.DateField(default=django.utils.timezone.now)),
                ('current_volume', models.PositiveIntegerField(default=1)),
                ('pocket', models.CharField(blank=True, help_text='Shelf / pocket location code where the file lives.', max_length=64)),
                ('status', models.CharField(choices=[('active', 'Active — in registry'), ('on_loan', 'On loan — issued'), ('redeemed', 'Redeemed'), ('archived', 'Archived'), ('destroyed', 'Destroyed'), ('missing', 'Missing')], db_index=True, default='active', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registry_files_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'registry_file',
                'ordering': ['file_no'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MovementCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, max_length=128)),
                ('purpose', models.CharField(blank=True, max_length=255)),
                ('issued_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('due_at', models.DateTimeField(db_index=True)),
                ('borrower_ack', models.BooleanField(default=False)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('returned_condition', models.CharField(blank=True, choices=[('ok', 'Good'), ('torn', 'Torn — repair'), ('damaged', 'Damaged')], max_length=16)),
                ('return_note', models.CharField(blank=True, max_length=255)),
                ('escalated_at', models.DateTimeField(blank=True, null=True)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registry_files_held', to=settings.AUTH_USER_MODEL)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movement_cards', to='registry.filerecord')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registry_files_issued', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'registry_movement_card',
                'ordering': ['-issued_at'],
                'managed': True,
                'indexes': [models.Index(fields=['returned_at', 'due_at'], name='registry_mo_returne_2ed981_idx')],
            },
        ),
    ]
