# Generated by Django 4.2.20 on 2026-07-15 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registry', '0002_seed_registry_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='filerecord',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='filerecord',
            name='redeemed_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DestructionBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending approval'), ('approved', 'Approved'), ('destroyed', 'Destroyed'), ('certified', 'Certified')], db_index=True, default='pending', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('unit_ack_at', models.DateTimeField(blank=True, null=True)),
                ('head_ops_at', models.DateTimeField(blank=True, null=True)),
                ('coo_at', models.DateTimeField(blank=True, null=True)),
                ('vendor', models.CharField(blank=True, max_length=128)),
                ('destruction_location', models.CharField(blank=True, max_length=128)),
                ('destroyed_at', models.DateTimeField(blank=True, null=True)),
                ('certificate_ref', models.CharField(blank=True, max_length=128)),
                ('certificate_note', models.TextField(blank=True)),
                ('coo_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registry_destructions_created', to=settings.AUTH_USER_MODEL)),
                ('files', models.ManyToManyField(blank=True, related_name='destruction_batches', to='registry.filerecord')),
                ('head_ops_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('unit_ack_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'registry_destruction_batch',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ArchiveConsignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_unit', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('received', 'Received & archived')], db_index=True, default='requested', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('files', models.ManyToManyField(blank=True, related_name='consignments', to='registry.filerecord')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registry_consignments_received', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registry_consignments_requested', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'registry_archive_consignment',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ArchiveBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=64, unique=True)),
                ('location', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boxes', to='registry.archiveconsignment')),
            ],
            options={
                'db_table': 'registry_archive_box',
                'ordering': ['code'],
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='filerecord',
            name='archive_box',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='registry.archivebox'),
        ),
    ]
