# Generated by Django 4.2.20 on 2026-07-17 05:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registry', '0003_filerecord_archived_at_filerecord_redeemed_on_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('location', models.CharField(blank=True, help_text='Optional pocket/shelf filter — blank counts the whole registry.', max_length=128)),
                ('status', models.CharField(choices=[('open', 'In progress'), ('closed', 'Closed')], db_index=True, default='open', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registry_stocktakes_closed', to=settings.AUTH_USER_MODEL)),
                ('opened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registry_stocktakes_opened', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'registry_stock_take',
                'ordering': ['-opened_at'],
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='filerecord',
            name='is_skeleton',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='StockTakeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sighted', models.BooleanField(default=False)),
                ('sighted_at', models.DateTimeField(blank=True, null=True)),
                ('remark', models.CharField(blank=True, max_length=255)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_take_items', to='registry.filerecord')),
                ('sighted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('stock_take', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='registry.stocktake')),
            ],
            options={
                'db_table': 'registry_stock_take_item',
                'ordering': ['file__file_no'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MissingFileIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Open — under search'), ('found', 'Found'), ('skeleton', 'Skeleton reconstructed'), ('written_off', 'Written off')], db_index=True, default='open', max_length=16)),
                ('last_seen', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolution_note', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missing_incidents', to='registry.filerecord')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registry_incidents_reported', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('skeleton_file', models.ForeignKey(blank=True, help_text='The reconstructed file created when the original is lost.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skeleton_for_incidents', to='registry.filerecord')),
                ('stock_take', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='registry.stocktake')),
            ],
            options={
                'db_table': 'registry_missing_incident',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
        migrations.AddConstraint(
            model_name='stocktakeitem',
            constraint=models.UniqueConstraint(fields=('stock_take', 'file'), name='uniq_stocktake_file'),
        ),
    ]
