# Generated by Django 4.2.20 on 2026-07-17 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registry', '0004_stocktake_filerecord_is_skeleton_stocktakeitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingfileincident',
            name='marked_to',
            field=models.ForeignKey(blank=True, help_text='Officer the file was issued to, if it was out at the count.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registry_incidents_marked_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stocktakeitem',
            name='marked_to',
            field=models.ForeignKey(blank=True, help_text='Officer holding the file when the count opened, if issued out.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
