# Generated by Django 4.2.20 on 2026-08-18 08:09

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff_management', '0009_teamleaderbranch'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('ref_family', models.CharField(choices=[('guarantee', 'Guarantee (HFCB/GTE/…)'), ('import_lc', 'Import LC (HF#####)'), ('export_lc', 'Export LC (HFCB/ELC/…)')], max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Trade Product',
                'db_table': 'trade_register_product',
                'ordering': ['sort_order', 'name'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TradeRegisterEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('originating_branch', models.CharField(max_length=255)),
                ('rm_name', models.CharField(max_length=255)),
                ('rm_code', models.CharField(blank=True, max_length=255)),
                ('guarantee_ref', models.CharField(blank=True, db_index=True, max_length=255)),
                ('product_type', models.CharField(max_length=255)),
                ('amendment_type', models.CharField(blank=True, choices=[('', 'New (not an amendment)'), ('EXT', 'Ext'), ('AMENDMENT', 'Amendment'), ('SETTLEMENT', 'Settlement'), ('CANCELLATION', 'Cancellation'), ('CALL UP', 'Call Up'), ('PAYMENT', 'Payment'), ('ADVISING', 'Advising'), ('RELEASE ON INDEMNITY', 'Release On Indemnity'), ('REDUCTION', 'Reduction'), ('RETIREMENT', 'Retirement')], max_length=32)),
                ('parent_ref', models.CharField(blank=True, max_length=255)),
                ('customer_id', models.BigIntegerField()),
                ('segment', models.CharField(max_length=255)),
                ('our_customer', models.CharField(max_length=255)),
                ('beneficiary', models.CharField(blank=True, max_length=255)),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('amount_fcy', models.DecimalField(decimal_places=2, default=0, max_digits=25, validators=[django.core.validators.MinValueValidator(0)])),
                ('fx_rate', models.DecimalField(decimal_places=6, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('commission', models.DecimalField(decimal_places=6, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('issue_date', models.DateField()),
                ('is_open_ended', models.BooleanField(default=False)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('security_type', models.CharField(blank=True, max_length=255)),
                ('cash_cover_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('cash_cover_percentage', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('other_security', models.CharField(blank=True, max_length=255)),
                ('month', models.CharField(blank=True, max_length=32)),
                ('year', models.CharField(blank=True, db_index=True, max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trade_register_entries', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='trade_register.tradeproduct')),
                ('tf', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='register_entry', to='staff_management.tradefinancedata')),
            ],
            options={
                'verbose_name': 'Trade Register Entry',
                'verbose_name_plural': 'Trade Register Entries',
                'db_table': 'trade_register_entry',
                'ordering': ['-issue_date', '-id'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HistoricalTradeRegisterEntry',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('originating_branch', models.CharField(max_length=255)),
                ('rm_name', models.CharField(max_length=255)),
                ('rm_code', models.CharField(blank=True, max_length=255)),
                ('guarantee_ref', models.CharField(blank=True, db_index=True, max_length=255)),
                ('product_type', models.CharField(max_length=255)),
                ('amendment_type', models.CharField(blank=True, choices=[('', 'New (not an amendment)'), ('EXT', 'Ext'), ('AMENDMENT', 'Amendment'), ('SETTLEMENT', 'Settlement'), ('CANCELLATION', 'Cancellation'), ('CALL UP', 'Call Up'), ('PAYMENT', 'Payment'), ('ADVISING', 'Advising'), ('RELEASE ON INDEMNITY', 'Release On Indemnity'), ('REDUCTION', 'Reduction'), ('RETIREMENT', 'Retirement')], max_length=32)),
                ('parent_ref', models.CharField(blank=True, max_length=255)),
                ('customer_id', models.BigIntegerField()),
                ('segment', models.CharField(max_length=255)),
                ('our_customer', models.CharField(max_length=255)),
                ('beneficiary', models.CharField(blank=True, max_length=255)),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('amount_fcy', models.DecimalField(decimal_places=2, default=0, max_digits=25, validators=[django.core.validators.MinValueValidator(0)])),
                ('fx_rate', models.DecimalField(decimal_places=6, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('commission', models.DecimalField(decimal_places=6, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('issue_date', models.DateField()),
                ('is_open_ended', models.BooleanField(default=False)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('security_type', models.CharField(blank=True, max_length=255)),
                ('cash_cover_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('cash_cover_percentage', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('other_security', models.CharField(blank=True, max_length=255)),
                ('month', models.CharField(blank=True, max_length=32)),
                ('year', models.CharField(blank=True, db_index=True, max_length=8)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='trade_register.tradeproduct')),
                ('tf', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='staff_management.tradefinancedata')),
            ],
            options={
                'verbose_name': 'historical Trade Register Entry',
                'verbose_name_plural': 'historical Trade Register Entries',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
