# Generated by Django 4.2.20 on 2026-08-18 09:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trade_register', '0002_seed_trade_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltraderegisterentry',
            name='reporting_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name='traderegisterentry',
            name='reporting_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
