# Generated by Django 4.2.20 on 2026-09-07 07:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trade_register', '0003_historicaltraderegisterentry_reporting_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=3, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=100)),
            ],
            options={
                'verbose_name': 'Trade Currency',
                'verbose_name_plural': 'Trade Currencies',
                'db_table': 'trade_register_currency',
                'ordering': ['sort_order', 'code'],
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='historicaltraderegisterentry',
            name='commission_override',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tradeproduct',
            name='commission_basis',
            field=models.CharField(choices=[('flat', 'Flat % of the amount'), ('per_quarter', '% per quarter (or part) of the tenor'), ('per_annum', '% per annum over the tenor'), ('none', 'Not calculated — entered by hand')], default='none', max_length=16),
        ),
        migrations.AddField(
            model_name='tradeproduct',
            name='commission_rate',
            field=models.DecimalField(decimal_places=6, default=0, help_text='Percent. 0.5 means 0.5%.', max_digits=9, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='tradeproduct',
            name='minimum_commission',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Floor in local currency, applied after the rate.', max_digits=20, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='traderegisterentry',
            name='commission_override',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='HistoricalTradeProduct',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=20)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('ref_family', models.CharField(choices=[('guarantee', 'Guarantee (HFCB/GTE/…)'), ('import_lc', 'Import LC (HF#####)'), ('export_lc', 'Export LC (HFCB/ELC/…)')], max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('commission_basis', models.CharField(choices=[('flat', 'Flat % of the amount'), ('per_quarter', '% per quarter (or part) of the tenor'), ('per_annum', '% per annum over the tenor'), ('none', 'Not calculated — entered by hand')], default='none', max_length=16)),
                ('commission_rate', models.DecimalField(decimal_places=6, default=0, help_text='Percent. 0.5 means 0.5%.', max_digits=9, validators=[django.core.validators.MinValueValidator(0)])),
                ('minimum_commission', models.DecimalField(decimal_places=2, default=0, help_text='Floor in local currency, applied after the rate.', max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Trade Product',
                'verbose_name_plural': 'historical Trade Products',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
