# Generated by Django 4.2.20 on 2026-09-08 08:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trade_register', '0007_seed_trade_tariffs'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalTradeProductCategory',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=30)),
                ('name', models.CharField(db_index=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=100)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Trade Product Category',
                'verbose_name_plural': 'historical Trade Product Categories',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='TradeProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=30, unique=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=100)),
            ],
            options={
                'verbose_name': 'Trade Product Category',
                'verbose_name_plural': 'Trade Product Categories',
                'db_table': 'trade_register_product_category',
                'ordering': ['sort_order', 'name'],
                'managed': True,
            },
        ),
        # RENAME, not remove-and-add: amendment_type holds what every historical
        # transaction actually did, and dropping the column would destroy it.
        migrations.RenameField(
            model_name='historicaltraderegisterentry',
            old_name='amendment_type',
            new_name='action',
        ),
        migrations.RenameField(
            model_name='traderegisterentry',
            old_name='amendment_type',
            new_name='action',
        ),
        migrations.AlterField(
            model_name='historicaltraderegisterentry',
            name='action',
            field=models.CharField(blank=True, default='ISSUANCE', max_length=32),
        ),
        migrations.AddField(
            model_name='historicaltraderegisterentry',
            name='amount_delta',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Increase (+) or reduction (−) this amendment applies.', max_digits=25),
        ),
        migrations.AddField(
            model_name='historicaltraderegisterentry',
            name='archived_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaltraderegisterentry',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='historicaltraderegisterentry',
            name='new_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaltraderegisterentry',
            name='parent',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='trade_register.traderegisterentry'),
        ),
        migrations.AddField(
            model_name='historicaltradetariff',
            name='action',
            field=models.CharField(blank=True, help_text="One of the desk's actions, or blank to apply to all of them.", max_length=32),
        ),
        migrations.AddField(
            model_name='historicaltradetariff',
            name='charge_currency',
            field=models.CharField(default='KES', max_length=3),
        ),
        migrations.AddField(
            model_name='historicaltradetariff',
            name='fixed_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='A flat fee charged instead of a percentage (e.g. 2,000).', max_digits=20, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='historicaltradetariff',
            name='manual_note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='historicaltradetariff',
            name='product',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Set only for a product priced differently from its category.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='trade_register.tradeproduct'),
        ),
        migrations.AlterField(
            model_name='traderegisterentry',
            name='action',
            field=models.CharField(blank=True, default='ISSUANCE', max_length=32),
        ),
        migrations.AddField(
            model_name='traderegisterentry',
            name='amount_delta',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Increase (+) or reduction (−) this amendment applies.', max_digits=25),
        ),
        migrations.AddField(
            model_name='traderegisterentry',
            name='archived_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='traderegisterentry',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='traderegisterentry',
            name='new_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='traderegisterentry',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amendments', to='trade_register.traderegisterentry'),
        ),
        migrations.AddField(
            model_name='tradetariff',
            name='action',
            field=models.CharField(blank=True, help_text="One of the desk's actions, or blank to apply to all of them.", max_length=32),
        ),
        migrations.AddField(
            model_name='tradetariff',
            name='charge_currency',
            field=models.CharField(default='KES', max_length=3),
        ),
        migrations.AddField(
            model_name='tradetariff',
            name='fixed_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='A flat fee charged instead of a percentage (e.g. 2,000).', max_digits=20, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='tradetariff',
            name='manual_note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='tradetariff',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Set only for a product priced differently from its category.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='own_tariffs', to='trade_register.tradeproduct'),
        ),
        migrations.AlterField(
            model_name='historicaltradetariff',
            name='code',
            field=models.CharField(db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='historicaltradetariff',
            name='commission_basis',
            field=models.CharField(choices=[('flat', 'Flat % of the amount'), ('per_quarter', '% per quarter (or part) of the tenor'), ('per_annum', '% per annum over the tenor'), ('per_month', 'Per month (or part) of the tenor'), ('per_instance', 'A fixed amount, once per transaction'), ('none', 'Not calculated — entered by hand')], default='none', max_length=16),
        ),
        migrations.AlterField(
            model_name='historicaltradetariff',
            name='commission_rate',
            field=models.DecimalField(decimal_places=6, default=0, help_text='Percent. 0.75 means 0.75%. Leave 0 for a fixed-amount charge.', max_digits=9, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='historicaltradetariff',
            name='minimum_commission',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Floor applied after the rate (the tariff's 'Min. KShs …').", max_digits=20, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='tradetariff',
            name='code',
            field=models.CharField(db_index=True, max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='tradetariff',
            name='commission_basis',
            field=models.CharField(choices=[('flat', 'Flat % of the amount'), ('per_quarter', '% per quarter (or part) of the tenor'), ('per_annum', '% per annum over the tenor'), ('per_month', 'Per month (or part) of the tenor'), ('per_instance', 'A fixed amount, once per transaction'), ('none', 'Not calculated — entered by hand')], default='none', max_length=16),
        ),
        migrations.AlterField(
            model_name='tradetariff',
            name='commission_rate',
            field=models.DecimalField(decimal_places=6, default=0, help_text='Percent. 0.75 means 0.75%. Leave 0 for a fixed-amount charge.', max_digits=9, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='tradetariff',
            name='minimum_commission',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Floor applied after the rate (the tariff's 'Min. KShs …').", max_digits=20, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='historicaltradeproductcategory',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaltradeproduct',
            name='category',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='trade_register.tradeproductcategory'),
        ),
        migrations.AddField(
            model_name='historicaltradetariff',
            name='category',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='trade_register.tradeproductcategory'),
        ),
        migrations.AddField(
            model_name='tradeproduct',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='trade_register.tradeproductcategory'),
        ),
        migrations.AddField(
            model_name='tradetariff',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tariffs', to='trade_register.tradeproductcategory'),
        ),
        migrations.AddIndex(
            model_name='tradetariff',
            index=models.Index(fields=['category', 'action', 'is_active'], name='trade_regis_categor_48a87d_idx'),
        ),
        migrations.AlterField(
            model_name='historicaltradeproduct',
            name='code',
            field=models.CharField(db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='tradeproduct',
            name='code',
            field=models.CharField(db_index=True, max_length=40, unique=True),
        ),
    ]
