# Generated by Django 6.0.5 on 2026-06-21 07:39

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hfdi', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AffordableHousingProjectsPipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('county', models.CharField(max_length=255)),
                ('mapping', models.CharField(blank=True, max_length=255, null=True)),
                ('units', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('projected_completion_date', models.CharField(blank=True, max_length=255, null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Affordable Housing Projects Pipeline',
                'verbose_name_plural': 'Affordable Housing Projects Pipeline',
                'db_table': 'affordable_housing_projects_pipeline',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AffordableHousingRegistrations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.BigIntegerField(unique=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('assisted_by', models.CharField(blank=True, max_length=255, null=True)),
                ('user_deposits', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('typology', models.CharField(blank=True, max_length=200, null=True)),
                ('house_type', models.CharField(default='default', max_length=200)),
                ('project', models.CharField(blank=True, max_length=200, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
            ],
            options={
                'verbose_name': 'Affordable Housing Registration',
                'verbose_name_plural': 'Affordable Housing Registrations',
                'db_table': 'affordable_housing_registrations',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AFHSellerMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(blank=True, max_length=255, null=True)),
                ('afh_name', models.CharField(blank=True, max_length=255, null=True)),
                ('staff_subsidiary', models.CharField(blank=True, max_length=255, null=True)),
                ('staff_unit', models.CharField(blank=True, max_length=255, null=True)),
                ('org_unit', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'AFH Seller Mapping',
                'verbose_name_plural': 'AFH Seller Mappings',
                'db_table': 'afh_seller_mapping',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HistoricalAffordableHousingProjectsPipeline',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('county', models.CharField(max_length=255)),
                ('mapping', models.CharField(blank=True, max_length=255, null=True)),
                ('units', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('projected_completion_date', models.CharField(blank=True, max_length=255, null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Affordable Housing Projects Pipeline',
                'verbose_name_plural': 'historical Affordable Housing Projects Pipeline',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalAffordableHousingRegistrations',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.BigIntegerField(db_index=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('assisted_by', models.CharField(blank=True, max_length=255, null=True)),
                ('user_deposits', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('typology', models.CharField(blank=True, max_length=200, null=True)),
                ('house_type', models.CharField(default='default', max_length=200)),
                ('project', models.CharField(blank=True, max_length=200, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Affordable Housing Registration',
                'verbose_name_plural': 'historical Affordable Housing Registrations',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
