# Generated by Django 4.2.20 on 2026-07-30 06:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


def copy_agent_allocations(apps, schema_editor):
    """Preserve existing agent-allocation data before the source columns are
    dropped. Clinton's restructure split allocation_collection_* out of
    ProjectTitanPlotsAllocation into its own table but didn't carry the data
    across — do it here so nothing is lost on prod."""
    Plots = apps.get_model("hfdi", "ProjectTitanPlotsAllocation")
    Agent = apps.get_model("hfdi", "ProjectTitanPlotsAgentAllocation")
    rows = Plots.objects.exclude(
        allocation_collection_code__isnull=True,
        allocation_collection_agent__isnull=True,
        allocation_collection_group__isnull=True,
    )
    Agent.objects.bulk_create(
        [
            Agent(
                plot_number=r.plot_number,
                allocation_collection_code=r.allocation_collection_code,
                allocation_collection_agent=r.allocation_collection_agent,
                allocation_collection_group=r.allocation_collection_group,
            )
            for r in rows.iterator()
        ],
        batch_size=500,
    )


def noop_reverse(apps, schema_editor):
    """Reverse re-adds the columns (RemoveField auto-reverses); the copied rows
    stay in the agent table — nothing to undo here."""


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hfdi', '0003_projecttitandailycollections_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTitanPlotsAgentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot_number', models.IntegerField(blank=True, null=True, verbose_name='Plot Number')),
                ('allocation_collection_code', models.IntegerField(blank=True, null=True, verbose_name='Staff Collection Code')),
                ('allocation_collection_agent', models.CharField(blank=True, max_length=300, null=True, verbose_name='Staff Collection Name')),
                ('allocation_collection_group', models.CharField(blank=True, max_length=300, null=True, verbose_name='Staff Collection Group')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'project_titan_plots_agent_allocation',
                'managed': True,
            },
        ),
        migrations.RunPython(copy_agent_allocations, noop_reverse),
        migrations.RemoveField(
            model_name='historicalprojecttitanplotsallocation',
            name='allocation_collection_agent',
        ),
        migrations.RemoveField(
            model_name='historicalprojecttitanplotsallocation',
            name='allocation_collection_code',
        ),
        migrations.RemoveField(
            model_name='historicalprojecttitanplotsallocation',
            name='allocation_collection_group',
        ),
        migrations.RemoveField(
            model_name='projecttitanplotsallocation',
            name='allocation_collection_agent',
        ),
        migrations.RemoveField(
            model_name='projecttitanplotsallocation',
            name='allocation_collection_code',
        ),
        migrations.RemoveField(
            model_name='projecttitanplotsallocation',
            name='allocation_collection_group',
        ),
        migrations.AddField(
            model_name='projecttitanplotsallocationfieldchange',
            name='administration_fees_changed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projecttitanplotsallocationfieldchange',
            name='alternative_phone_number_changed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projecttitanplotsallocationfieldchange',
            name='amount_paid_changed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projecttitanplotsallocationfieldchange',
            name='deed_of_settlment_allocation_changed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projecttitanplotsallocationfieldchange',
            name='eurobond_employee_allocaiton_changed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projecttitanplotsallocationfieldchange',
            name='gratuity_allocation_changed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projecttitanplotsallocationfieldchange',
            name='national_id_changed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projecttitanplotsallocationfieldchange',
            name='parcel_lr_number_changed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projecttitanplotsallocationfieldchange',
            name='phone_number_changed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projecttitanplotsallocationfieldchange',
            name='plot_area_changed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projecttitanplotsallocationfieldchange',
            name='plot_balance_changed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projecttitanplotsallocationfieldchange',
            name='plot_squatter_name_changed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projecttitanplotsallocationfieldchange',
            name='plot_status_changed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projecttitanplotsallocationfieldchange',
            name='plot_title_number_changed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projecttitanplotsallocationfieldchange',
            name='plot_value_changed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projecttitanplotsallocationfieldchange',
            name='serial_number_changed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projecttitanplotsallocationfieldchange',
            name='surveyor_allocation_changed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='HistoricalProjectTitanPlotsAgentAllocation',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('plot_number', models.IntegerField(blank=True, null=True, verbose_name='Plot Number')),
                ('allocation_collection_code', models.IntegerField(blank=True, null=True, verbose_name='Staff Collection Code')),
                ('allocation_collection_agent', models.CharField(blank=True, max_length=300, null=True, verbose_name='Staff Collection Name')),
                ('allocation_collection_group', models.CharField(blank=True, max_length=300, null=True, verbose_name='Staff Collection Group')),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical project titan plots agent allocation',
                'verbose_name_plural': 'historical project titan plots agent allocations',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
