# Generated by Django 4.2.20 on 2026-08-05 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hfdi', '0004_projecttitanplotsagentallocation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprojecttitanplotsallocation',
            name='national_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='National ID'),
        ),
        migrations.AlterField(
            model_name='projecttitanplotsallocation',
            name='national_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='National ID'),
        ),
    ]
