# Generated by Django 4.2.20 on 2026-08-10 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hfdi', '0005_alter_historicalprojecttitanplotsallocation_national_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectInventoryLegalDocumentsStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('unit_name', models.CharField(max_length=255)),
                ('sale_agreement', models.BooleanField(default=False)),
                ('readiness_to_complete', models.BooleanField(default=False)),
                ('completion_notice', models.BooleanField(default=False)),
                ('rescission_notice', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Project Inventory Legal Documents Status',
                'verbose_name_plural': 'Project Inventory Legal Documents Status',
                'db_table': 'project_inventory_legal_documents_status',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HistoricalProjectInventoryLegalDocumentsStatus',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('unit_name', models.CharField(max_length=255)),
                ('sale_agreement', models.BooleanField(default=False)),
                ('readiness_to_complete', models.BooleanField(default=False)),
                ('completion_notice', models.BooleanField(default=False)),
                ('rescission_notice', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Project Inventory Legal Documents Status',
                'verbose_name_plural': 'historical Project Inventory Legal Documents Status',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
