# Generated by Django 4.2.20 on 2026-08-12 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hfdi', '0006_projectinventorylegaldocumentsstatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprojecttitanplotsallocation',
            name='parcel_block',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Plot Block Number'),
        ),
        migrations.AddField(
            model_name='historicalprojecttitanplotsallocation',
            name='plot_cleaned_name',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Plot Cleaned Name'),
        ),
        migrations.AddField(
            model_name='projecttitanplotsallocation',
            name='parcel_block',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Plot Block Number'),
        ),
        migrations.AddField(
            model_name='projecttitanplotsallocation',
            name='plot_cleaned_name',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Plot Cleaned Name'),
        ),
    ]
