# Generated by Django 4.2.20 on 2026-09-30 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hfdi', '0007_historicalprojecttitanplotsallocation_parcel_block_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hfditargets',
            name='site_admin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalhfditargets',
            name='site_admin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
