# Generated by Django 4.2.20 on 2026-10-09 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hfdi', '0009_hfdi_try_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affordablehousingapplication',
            name='assisted_by',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Assisted By'),
        ),
        migrations.AlterField(
            model_name='affordablehousingapplication',
            name='house_type',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='House Type'),
        ),
        migrations.AlterField(
            model_name='affordablehousingapplication',
            name='mode_of_payment',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Mode of Payment'),
        ),
        migrations.AlterField(
            model_name='affordablehousingapplication',
            name='need_deposit_assitance',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Need Deposit Assistance'),
        ),
        migrations.AlterField(
            model_name='affordablehousingapplication',
            name='project_name',
            field=models.CharField(blank=True, default='Project Name', max_length=200, verbose_name='Project Name'),
        ),
        migrations.AlterField(
            model_name='affordablehousingapplication',
            name='status',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='affordablehousingapplication',
            name='typology',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Typology'),
        ),
        migrations.AlterField(
            model_name='historicalaffordablehousingapplication',
            name='assisted_by',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Assisted By'),
        ),
        migrations.AlterField(
            model_name='historicalaffordablehousingapplication',
            name='house_type',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='House Type'),
        ),
        migrations.AlterField(
            model_name='historicalaffordablehousingapplication',
            name='mode_of_payment',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Mode of Payment'),
        ),
        migrations.AlterField(
            model_name='historicalaffordablehousingapplication',
            name='need_deposit_assitance',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Need Deposit Assistance'),
        ),
        migrations.AlterField(
            model_name='historicalaffordablehousingapplication',
            name='project_name',
            field=models.CharField(blank=True, default='Project Name', max_length=200, verbose_name='Project Name'),
        ),
        migrations.AlterField(
            model_name='historicalaffordablehousingapplication',
            name='status',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='historicalaffordablehousingapplication',
            name='typology',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Typology'),
        ),
    ]
