# Generated by Django 6.0.5 on 2026-05-18 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content_type', models.CharField(choices=[('deposits_summary', 'Deposits Summary'), ('loans_summary', 'Loans Summary'), ('customers_summary', 'Customers Summary'), ('revenue_summary', 'Revenue Summary'), ('arrears_summary', 'Arrears Summary'), ('segment_breakdown', 'Segment Breakdown'), ('branch_performance', 'Branch Performance'), ('hfdi_performance', 'HFDI Performance'), ('collections_summary', 'Collections Summary'), ('custom', 'Custom')], max_length=50)),
                ('payload', models.JSONField(default=dict)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'slideshow_slides',
                'ordering': ['order', '-generated_at'],
                'managed': True,
            },
        ),
    ]
