# Generated by Django 6.0.5 on 2026-06-15 07:49

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortgages', '0002_seed_mortgage_groups'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_overdue', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('days_overdue', models.PositiveIntegerField(default=0)),
                ('bucket', models.CharField(blank=True, max_length=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('promised', 'Promise to Pay'), ('recovered', 'Recovered'), ('legal', 'Legal / Recovery'), ('written_off', 'Written Off')], default='pending', max_length=16)),
                ('action_taken', models.CharField(blank=True, max_length=255)),
                ('promised_date', models.DateField(blank=True, null=True)),
                ('promised_amount', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('notes', models.TextField(blank=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mortgage_collection_cases', to=settings.AUTH_USER_MODEL)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_cases', to='mortgages.mortgageloan')),
            ],
            options={
                'db_table': 'mortgage_collection_cases',
                'ordering': ['-days_overdue', '-id'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HistoricalInterestRate',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('name', models.CharField(max_length=120)),
                ('rate_type', models.CharField(choices=[('kmrc', 'KMRC Affordable'), ('commercial', 'Commercial'), ('affordable', 'Affordable Housing'), ('staff', 'Staff Scheme'), ('base', 'Base Rate')], default='commercial', max_length=16)),
                ('rate', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('effective_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical interest rate',
                'verbose_name_plural': 'historical interest rates',
                'db_table': 'mortgage_interest_rates_history',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='InterestRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('rate_type', models.CharField(choices=[('kmrc', 'KMRC Affordable'), ('commercial', 'Commercial'), ('affordable', 'Affordable Housing'), ('staff', 'Staff Scheme'), ('base', 'Base Rate')], default='commercial', max_length=16)),
                ('rate', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('effective_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mortgage_interest_rates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mortgage_interest_rates',
                'ordering': ['-effective_date', '-id'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('info', 'Info'), ('approval', 'Approval'), ('disbursement', 'Disbursement'), ('repayment_due', 'Repayment Due'), ('assignment', 'Assignment'), ('collection', 'Collection'), ('lead', 'Lead')], default='info', max_length=16)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('link', models.CharField(blank=True, max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mortgage_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mortgage_notifications',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
    ]
