# Generated by Django 6.0.5 on 2026-05-18 12:25

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerEnrichment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_id', models.BigIntegerField(unique=True)),
                ('income_band', models.CharField(blank=True, max_length=50, null=True)),
                ('employment_status', models.CharField(blank=True, max_length=100, null=True)),
                ('employer', models.CharField(blank=True, max_length=255, null=True)),
                ('industry', models.CharField(blank=True, max_length=100, null=True)),
                ('monthly_income_estimate', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('property_owner', models.BooleanField(blank=True, null=True)),
                ('credit_score', models.IntegerField(blank=True, null=True)),
                ('risk_rating', models.CharField(blank=True, max_length=20, null=True)),
                ('lifetime_value_estimate', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('preferred_channel', models.CharField(blank=True, max_length=50, null=True)),
                ('data_source', models.CharField(blank=True, max_length=100, null=True)),
                ('enrichment_date', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('input_user', models.CharField(default='me', max_length=100)),
            ],
            options={
                'db_table': 'portfolio_customer_enrichment',
                'ordering': ['-updated_at'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HistoricalCustomerEnrichment',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('cust_id', models.BigIntegerField(db_index=True)),
                ('income_band', models.CharField(blank=True, max_length=50, null=True)),
                ('employment_status', models.CharField(blank=True, max_length=100, null=True)),
                ('employer', models.CharField(blank=True, max_length=255, null=True)),
                ('industry', models.CharField(blank=True, max_length=100, null=True)),
                ('monthly_income_estimate', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('property_owner', models.BooleanField(blank=True, null=True)),
                ('credit_score', models.IntegerField(blank=True, null=True)),
                ('risk_rating', models.CharField(blank=True, max_length=20, null=True)),
                ('lifetime_value_estimate', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('preferred_channel', models.CharField(blank=True, max_length=50, null=True)),
                ('data_source', models.CharField(blank=True, max_length=100, null=True)),
                ('enrichment_date', models.DateField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('input_user', models.CharField(default='me', max_length=100)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical customer enrichment',
                'verbose_name_plural': 'historical customer enrichments',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalRmTarget',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('sales_code', models.CharField(max_length=50)),
                ('month', models.DateField()),
                ('deposit_target', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('loan_target', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('revenue_target', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('new_customers_target', models.IntegerField(default=0)),
                ('recording_date', models.DateField(blank=True, editable=False)),
                ('input_user', models.CharField(default='me', max_length=100)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical rm target',
                'verbose_name_plural': 'historical rm targets',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='RmTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_code', models.CharField(max_length=50)),
                ('month', models.DateField()),
                ('deposit_target', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('loan_target', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('revenue_target', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('new_customers_target', models.IntegerField(default=0)),
                ('recording_date', models.DateField(auto_now_add=True)),
                ('input_user', models.CharField(default='me', max_length=100)),
            ],
            options={
                'db_table': 'portfolio_rm_targets',
                'managed': True,
                'unique_together': {('sales_code', 'month')},
            },
        ),
    ]
