# Generated by Django 6.0.5 on 2026-06-21 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_management_enrichment', '0002_customerallocationbase_customertransferhistory_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerallocationbase',
            options={'managed': True, 'ordering': ['-aum_cust_id'], 'verbose_name': 'Customer Allocation Base', 'verbose_name_plural': 'Customer Allocation Bases'},
        ),
        migrations.AlterModelOptions(
            name='customertransferhistory',
            options={'managed': True, 'ordering': ['-transfer_date'], 'verbose_name': 'Customer Transfer History', 'verbose_name_plural': 'Customer Transfer Histories'},
        ),
        migrations.AlterModelOptions(
            name='rmallocationlist',
            options={'managed': True, 'ordering': ['rm_name'], 'verbose_name': 'RM Allocation List', 'verbose_name_plural': 'RM Allocation Lists'},
        ),
        migrations.AlterModelOptions(
            name='teamleadermovementapprovers',
            options={'managed': True, 'ordering': ['name'], 'verbose_name': 'customer_movment_approval_list', 'verbose_name_plural': 'customer_movment_approval_list'},
        ),
    ]
