# Generated by Django 4.2.20 on 2026-09-07 07:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=300)),
                ('method', models.CharField(max_length=10)),
                ('status_code', models.PositiveSmallIntegerField()),
                ('duration_ms', models.PositiveIntegerField()),
                ('username', models.CharField(blank=True, default='', max_length=150)),
                ('is_error', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'observability_request_metric',
                'ordering': ['-created_at'],
                'managed': True,
                'indexes': [models.Index(fields=['created_at'], name='observabili_created_a76ee9_idx'), models.Index(fields=['path', 'created_at'], name='observabili_path_0c3523_idx'), models.Index(fields=['is_error', 'created_at'], name='observabili_is_erro_961ec2_idx'), models.Index(fields=['status_code', 'created_at'], name='observabili_status__bf4a9e_idx'), models.Index(fields=['username', 'created_at'], name='observabili_usernam_63de7c_idx')],
            },
        ),
        migrations.CreateModel(
            name='AppHeartbeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute', models.DateTimeField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'observability_heartbeat',
                'ordering': ['-minute'],
                'managed': True,
                'indexes': [models.Index(fields=['minute'], name='observabili_minute_498bc0_idx')],
            },
        ),
    ]
