# Generated by Django 4.2.20 on 2026-09-11 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('observability', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(blank=True, max_length=120)),
                ('downtime', models.BooleanField(default=True)),
                ('data_health', models.BooleanField(default=True)),
                ('sensitive_change', models.BooleanField(default=False)),
                ('daily_digest', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'observability_alert_recipient',
                'ordering': ['email'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AlertState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200, unique=True)),
                ('state', models.CharField(max_length=32)),
                ('detail', models.TextField(blank=True)),
                ('since', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_notified_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'observability_alert_state',
                'ordering': ['key'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ExternalAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(db_index=True, max_length=50)),
                ('action', models.CharField(blank=True, max_length=32)),
                ('model_label', models.CharField(blank=True, max_length=120)),
                ('object_id', models.CharField(blank=True, max_length=100)),
                ('object_label', models.CharField(blank=True, max_length=200)),
                ('username', models.CharField(blank=True, max_length=150)),
                ('changes', models.JSONField(blank=True, default=list)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=100)),
            ],
            options={
                'db_table': 'observability_external_audit_event',
                'ordering': ['-occurred_at'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ExternalTableHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(db_index=True, max_length=50)),
                ('table', models.CharField(max_length=200)),
                ('label', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(default='unknown', max_length=20)),
                ('rows', models.BigIntegerField(default=0)),
                ('rows_are_estimate', models.BooleanField(default=False)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('age_days', models.IntegerField(blank=True, null=True)),
                ('error', models.CharField(blank=True, max_length=300)),
                ('reported_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'observability_external_table_health',
                'ordering': ['source', 'table'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MonitoredService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=120)),
                ('health_url', models.URLField(blank=True, help_text='Probed on a schedule. Leave blank for a push-only service.')),
                ('expected_status', models.PositiveSmallIntegerField(default=200)),
                ('timeout_seconds', models.PositiveSmallIntegerField(default=10)),
                ('slow_ms', models.PositiveIntegerField(default=3000)),
                ('ingest_token', models.CharField(blank=True, db_index=True, help_text='Shared secret the service sends as X-Observability-Token.', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'observability_monitored_service',
                'ordering': ['name'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ServiceProbe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ok', models.BooleanField(default=False)),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('error', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='probes', to='observability.monitoredservice')),
            ],
            options={
                'db_table': 'observability_service_probe',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HistoricalMonitoredService',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('name', models.CharField(max_length=120)),
                ('health_url', models.URLField(blank=True, help_text='Probed on a schedule. Leave blank for a push-only service.')),
                ('expected_status', models.PositiveSmallIntegerField(default=200)),
                ('timeout_seconds', models.PositiveSmallIntegerField(default=10)),
                ('slow_ms', models.PositiveIntegerField(default=3000)),
                ('ingest_token', models.CharField(blank=True, db_index=True, help_text='Shared secret the service sends as X-Observability-Token.', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical monitored service',
                'verbose_name_plural': 'historical monitored services',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalAlertRecipient',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('name', models.CharField(blank=True, max_length=120)),
                ('downtime', models.BooleanField(default=True)),
                ('data_health', models.BooleanField(default=True)),
                ('sensitive_change', models.BooleanField(default=False)),
                ('daily_digest', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical alert recipient',
                'verbose_name_plural': 'historical alert recipients',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddConstraint(
            model_name='externaltablehealth',
            constraint=models.UniqueConstraint(fields=('source', 'table'), name='uniq_external_table_health'),
        ),
        migrations.AddConstraint(
            model_name='externalauditevent',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id__gt', '')), fields=('source', 'external_id'), name='uniq_external_audit_event'),
        ),
        migrations.AddIndex(
            model_name='serviceprobe',
            index=models.Index(fields=['service', 'created_at'], name='observabili_service_da1cf2_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceprobe',
            index=models.Index(fields=['ok', 'created_at'], name='observabili_ok_4b09cb_idx'),
        ),
    ]
