# Generated by Django 4.2.20 on 2026-09-30 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observability', '0003_seed_customer_360'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalUsageDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(db_index=True, max_length=50)),
                ('day', models.DateField(db_index=True)),
                ('username', models.CharField(db_index=True, max_length=150)),
                ('requests', models.PositiveIntegerField(default=0)),
                ('page_views', models.PositiveIntegerField(default=0)),
                ('customer_views', models.PositiveIntegerField(default=0)),
                ('distinct_customers', models.PositiveIntegerField(default=0)),
                ('searches', models.PositiveIntegerField(default=0)),
                ('exports', models.PositiveIntegerField(default=0)),
                ('errors', models.PositiveIntegerField(default=0)),
                ('sessions', models.PositiveIntegerField(default=0)),
                ('active_minutes', models.PositiveIntegerField(default=0)),
                ('first_at', models.DateTimeField(blank=True, null=True)),
                ('last_at', models.DateTimeField(blank=True, null=True)),
                ('features', models.JSONField(blank=True, default=dict)),
                ('reported_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'observability_external_usage_day',
                'ordering': ['-day', 'username'],
                'managed': True,
                'indexes': [models.Index(fields=['source', 'day'], name='observabili_source_4c195f_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='externalusageday',
            constraint=models.UniqueConstraint(fields=('source', 'day', 'username'), name='uniq_external_usage_day'),
        ),
    ]
