-- Growing one-off: create NEW tables that exist in the code's migrations but were
-- never physically created on prod (the DB was adopted with migrations faked, so
-- newer tables are missing even though migrations show applied). Schemas match the
-- models / `manage.py sqlmigrate`. Safe: only CREATEs new tables; touches no
-- existing data. Fully idempotent (IF NOT EXISTS + guarded constraints), so it is
-- safe to re-run. Run:  psql ... -f deploy/host/create_missing_prod_tables.sql
BEGIN;

-- RmTarget (portfolio_management_enrichment 0001) — read by the scorecard engine.
CREATE TABLE IF NOT EXISTS "portfolio_rm_targets" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "sales_code" varchar(50) NOT NULL, "month" date NOT NULL, "deposit_target" numeric(20, 2) NOT NULL, "loan_target" numeric(20, 2) NOT NULL, "revenue_target" numeric(20, 2) NOT NULL, "new_customers_target" integer NOT NULL, "recording_date" date NOT NULL, "input_user" varchar(100) NOT NULL);
DO $$ BEGIN
    ALTER TABLE "portfolio_rm_targets" ADD CONSTRAINT "portfolio_rm_targets_sales_code_month_da9cbeaf_uniq" UNIQUE ("sales_code", "month");
EXCEPTION WHEN duplicate_table THEN NULL; WHEN duplicate_object THEN NULL;
END $$;

-- EmployeeMonthlyPerformance (staff_management, db_table employee_monthly_performance_v2)
-- The scorecard WRITE target. Deliberately a fresh table, separate from the legacy
-- "employee_monthly_performance". Model has no extra indexes/uniques.
CREATE TABLE IF NOT EXISTS "employee_monthly_performance_v2" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "sales_code" varchar(50) NOT NULL,
    "staff_name" varchar(255) NULL,
    "staff_role" varchar(255) NULL,
    "department" varchar(255) NULL,
    "org_unit" varchar(255) NULL,
    "month" date NOT NULL,
    "deposit_actual" numeric(20, 2) NOT NULL,
    "deposit_target" numeric(20, 2) NOT NULL,
    "loan_actual" numeric(20, 2) NOT NULL,
    "loan_target" numeric(20, 2) NOT NULL,
    "revenue_actual" numeric(20, 2) NOT NULL,
    "revenue_target" numeric(20, 2) NOT NULL,
    "new_customers_actual" integer NOT NULL,
    "new_customers_target" integer NOT NULL,
    "deposit_score" double precision NOT NULL,
    "loan_score" double precision NOT NULL,
    "revenue_score" double precision NOT NULL,
    "new_customers_score" double precision NOT NULL,
    "total_score" double precision NOT NULL,
    "grade" varchar(5) NULL,
    "kpis_met" varchar(50) NULL,
    "generated_at" timestamp with time zone NOT NULL
);

-- Scorecard config fields (staff_management 0007) so the Role KPI Mappings screen
-- fills in role_code/role_type and kpi_code/description/calc-mode/rating/score_cap.
ALTER TABLE "scorecard_roles" ADD COLUMN IF NOT EXISTS "role_code" varchar(50) NULL;
ALTER TABLE "scorecard_roles" ADD COLUMN IF NOT EXISTS "role_type" varchar(10) NULL;
ALTER TABLE "scorecard_kpis"  ADD COLUMN IF NOT EXISTS "kpi_code" varchar(50) NULL;
ALTER TABLE "scorecard_kpis"  ADD COLUMN IF NOT EXISTS "kpi_description" text NULL;
ALTER TABLE "scorecard_kpis"  ADD COLUMN IF NOT EXISTS "kpi_calculation_mode" varchar(50) NULL;
ALTER TABLE "scorecard_kpis"  ADD COLUMN IF NOT EXISTS "kpi_rating_type" varchar(50) NULL;
ALTER TABLE "scorecard_kpis"  ADD COLUMN IF NOT EXISTS "score_cap" double precision NOT NULL DEFAULT 0;

-- django-rest-passwordreset token table (final state after its 0001–0004 migrations).
-- A NEW app table: if it was never physically created, POST /auth/api/password_reset/
-- 500s while creating the token, so the reset email never fires. This is the likely
-- reason "reset password sends no mail". Idempotent.
CREATE TABLE IF NOT EXISTS "django_rest_passwordreset_resetpasswordtoken" (
    "id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "key" varchar(64) NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    "ip_address" inet NULL,
    "user_agent" varchar(512) NOT NULL,
    "user_id" integer NOT NULL
);
DO $$ BEGIN
    ALTER TABLE "django_rest_passwordreset_resetpasswordtoken"
        ADD CONSTRAINT "django_rest_passwordreset_resetpasswordtoken_key_f1b65873_uniq" UNIQUE ("key");
EXCEPTION WHEN duplicate_table THEN NULL; WHEN duplicate_object THEN NULL;
END $$;
DO $$ BEGIN
    ALTER TABLE "django_rest_passwordreset_resetpasswordtoken"
        ADD CONSTRAINT "django_rest_password_user_id_e8015b11_fk_auth_user"
        FOREIGN KEY ("user_id") REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED;
EXCEPTION WHEN duplicate_table THEN NULL; WHEN duplicate_object THEN NULL;
END $$;
CREATE INDEX IF NOT EXISTS "django_rest_passwordreset_resetpasswordtoken_key_f1b65873_like"
    ON "django_rest_passwordreset_resetpasswordtoken" ("key" varchar_pattern_ops);
CREATE INDEX IF NOT EXISTS "django_rest_passwordreset_resetpasswordtoken_user_id_e8015b11"
    ON "django_rest_passwordreset_resetpasswordtoken" ("user_id");

COMMIT;
