-- Growing one-off: create NEW tables that exist in the code's migrations but were
-- never physically created on prod (the DB was adopted with migrations faked, so
-- newer tables are missing even though migrations show applied). Each block is
-- verbatim from `manage.py sqlmigrate`, so schemas match exactly. Safe: only
-- CREATEs; touches no existing data. Re-runnable blocks guard with IF NOT EXISTS
-- where possible. Run:  psql ... -f deploy/host/create_missing_prod_tables.sql
BEGIN;

-- RmTarget (portfolio_management_enrichment 0001) — needed by the scorecard engine.
CREATE TABLE IF NOT EXISTS "portfolio_rm_targets" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "sales_code" varchar(50) NOT NULL, "month" date NOT NULL, "deposit_target" numeric(20, 2) NOT NULL, "loan_target" numeric(20, 2) NOT NULL, "revenue_target" numeric(20, 2) NOT NULL, "new_customers_target" integer NOT NULL, "recording_date" date NOT NULL, "input_user" varchar(100) NOT NULL);
ALTER TABLE "portfolio_rm_targets" ADD CONSTRAINT "portfolio_rm_targets_sales_code_month_da9cbeaf_uniq" UNIQUE ("sales_code", "month");

COMMIT;
