-- One-off: create the scorecard_* tables that staff_management migration 0001
-- defines but that were never physically created on prod (0001 was faked when
-- the DB was adopted from the legacy system, so these NEW tables are missing
-- even though the migration shows as applied). DDL is copied verbatim from
-- `manage.py sqlmigrate staff_management 0001`, so the schema matches exactly.
-- Safe: only CREATEs new tables/indexes/constraints; touches no existing data.
-- Run once:  PGPASSWORD=<pw> psql -h 127.0.0.1 -U <DB_USER> -d <DB_NAME> -f deploy/host/create_scorecard_tables.sql
BEGIN;

CREATE TABLE "scorecard_performance_actuals" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "sales_code" varchar(50) NOT NULL, "staff_name" varchar(255) NULL, "staff_role" varchar(255) NULL, "department" varchar(255) NULL, "kpi_name" varchar(255) NOT NULL, "month" date NOT NULL, "actual_value" numeric(20, 2) NOT NULL, "target_value" numeric(20, 2) NOT NULL);

CREATE TABLE "scorecard_kpis" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(255) NOT NULL UNIQUE, "category" varchar(50) NOT NULL, "weight" double precision NOT NULL, "is_active" boolean NOT NULL);

CREATE TABLE "scorecard_roles" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(255) NOT NULL UNIQUE, "description" text NULL, "is_active" boolean NOT NULL);

CREATE TABLE "scorecard_role_kpi_mappings" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "weight" double precision NOT NULL, "kpi_id" bigint NOT NULL, "role_id" bigint NOT NULL);

CREATE INDEX "scorecard_kpis_name_59140cd5_like" ON "scorecard_kpis" ("name" varchar_pattern_ops);
CREATE INDEX "scorecard_roles_name_a78c0ba6_like" ON "scorecard_roles" ("name" varchar_pattern_ops);

ALTER TABLE "scorecard_role_kpi_mappings" ADD CONSTRAINT "scorecard_role_kpi_mappings_role_id_kpi_id_6c7436fa_uniq" UNIQUE ("role_id", "kpi_id");
ALTER TABLE "scorecard_role_kpi_mappings" ADD CONSTRAINT "scorecard_role_kpi_m_kpi_id_9c2eb5fb_fk_scorecard" FOREIGN KEY ("kpi_id") REFERENCES "scorecard_kpis" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "scorecard_role_kpi_mappings" ADD CONSTRAINT "scorecard_role_kpi_m_role_id_e57d386e_fk_scorecard" FOREIGN KEY ("role_id") REFERENCES "scorecard_roles" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "scorecard_role_kpi_mappings_kpi_id_9c2eb5fb" ON "scorecard_role_kpi_mappings" ("kpi_id");
CREATE INDEX "scorecard_role_kpi_mappings_role_id_e57d386e" ON "scorecard_role_kpi_mappings" ("role_id");

COMMIT;
