-- Reconcile hfdi migration 0004 on the adopted prod DB.
--
-- The prod DB was adopted with its migration ledger out of sync: the 0002/0003
-- hfdi tables already exist physically but Django records them as unapplied, so
-- `migrate hfdi` dies trying to CREATE a table that already exists
-- (e.g. "relation affordable_housing_projects_pipeline already exists").
--
-- This script creates ONLY the genuinely-new 0004 objects — the agent-allocation
-- table (+ its history table), the 17 *_changed audit flags, and it moves the
-- allocation_collection_* data out of the plots table before dropping those
-- columns. Everything is idempotent and safe to run more than once.
--
-- AFTER running this, sync the ledger (does NOT touch the DB):
--     docker exec hf-backend python manage.py migrate hfdi --fake
--
-- Object names below are taken verbatim from `manage.py sqlmigrate hfdi 0004`.

BEGIN;

-- 1. New agent-allocation table (0004 CreateModel ProjectTitanPlotsAgentAllocation).
CREATE TABLE IF NOT EXISTS "project_titan_plots_agent_allocation" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "plot_number" integer NULL,
    "allocation_collection_code" integer NULL,
    "allocation_collection_agent" varchar(300) NULL,
    "allocation_collection_group" varchar(300) NULL,
    "created_at" timestamp with time zone NULL,
    "updated_at" timestamp with time zone NULL
);

-- 2. Its simple_history table (0004 CreateModel HistoricalProjectTitanPlotsAgentAllocation).
CREATE TABLE IF NOT EXISTS "hfdi_historicalprojecttitanplotsagentallocation" (
    "id" bigint NOT NULL,
    "plot_number" integer NULL,
    "allocation_collection_code" integer NULL,
    "allocation_collection_agent" varchar(300) NULL,
    "allocation_collection_group" varchar(300) NULL,
    "created_at" timestamp with time zone NULL,
    "updated_at" timestamp with time zone NULL,
    "history_id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "history_date" timestamp with time zone NOT NULL,
    "history_change_reason" varchar(100) NULL,
    "history_type" varchar(1) NOT NULL,
    "history_user_id" integer NULL
);
DO $$ BEGIN
    ALTER TABLE "hfdi_historicalprojecttitanplotsagentallocation"
        ADD CONSTRAINT "hfdi_historicalproje_history_user_id_6036932f_fk_auth_user"
        FOREIGN KEY ("history_user_id") REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED;
EXCEPTION WHEN duplicate_object THEN NULL; WHEN duplicate_table THEN NULL;
END $$;
CREATE INDEX IF NOT EXISTS "hfdi_historicalprojecttitanplotsagentallocation_id_faf63bf8"
    ON "hfdi_historicalprojecttitanplotsagentallocation" ("id");
CREATE INDEX IF NOT EXISTS "hfdi_historicalprojecttita_history_date_8dddf1a2"
    ON "hfdi_historicalprojecttitanplotsagentallocation" ("history_date");
CREATE INDEX IF NOT EXISTS "hfdi_historicalprojecttita_history_user_id_6036932f"
    ON "hfdi_historicalprojecttitanplotsagentallocation" ("history_user_id");

-- 3. Add the 17 *_changed audit flags to the field-change table (0004 AddField),
--    only if that 0003 table is present. Idempotent per-column.
DO $$
DECLARE col text;
BEGIN
    IF to_regclass('public.project_titan_plots_allocation_field_changes') IS NOT NULL THEN
        FOREACH col IN ARRAY ARRAY[
            'administration_fees_changed','alternative_phone_number_changed','amount_paid_changed',
            'deed_of_settlment_allocation_changed','eurobond_employee_allocaiton_changed',
            'gratuity_allocation_changed','national_id_changed','parcel_lr_number_changed',
            'phone_number_changed','plot_area_changed','plot_balance_changed',
            'plot_squatter_name_changed','plot_status_changed','plot_title_number_changed',
            'plot_value_changed','serial_number_changed','surveyor_allocation_changed'
        ]
        LOOP
            EXECUTE format(
                'ALTER TABLE "project_titan_plots_allocation_field_changes" '
                'ADD COLUMN IF NOT EXISTS %I boolean NOT NULL DEFAULT false', col);
        END LOOP;
    END IF;
END $$;

-- 4. Preserve existing agent data: copy allocation_collection_* out of the plots
--    table into the new table BEFORE dropping those columns. Runs only if the
--    source columns still exist and the target is still empty (so a re-run is a no-op).
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'project_titan_plots_allocation'
          AND column_name = 'allocation_collection_agent'
    ) AND NOT EXISTS (SELECT 1 FROM "project_titan_plots_agent_allocation") THEN
        INSERT INTO "project_titan_plots_agent_allocation"
            (plot_number, allocation_collection_code, allocation_collection_agent, allocation_collection_group)
        SELECT plot_number, allocation_collection_code, allocation_collection_agent, allocation_collection_group
        FROM "project_titan_plots_allocation"
        WHERE allocation_collection_code  IS NOT NULL
           OR allocation_collection_agent IS NOT NULL
           OR allocation_collection_group IS NOT NULL;
    END IF;
END $$;

-- 5. Drop the moved columns from the plots table + its history table (0004
--    RemoveField), matching the model's final state. ALTER TABLE IF EXISTS guards
--    the table; DROP COLUMN IF EXISTS guards the column.
ALTER TABLE IF EXISTS "project_titan_plots_allocation"             DROP COLUMN IF EXISTS "allocation_collection_agent";
ALTER TABLE IF EXISTS "project_titan_plots_allocation"             DROP COLUMN IF EXISTS "allocation_collection_code";
ALTER TABLE IF EXISTS "project_titan_plots_allocation"             DROP COLUMN IF EXISTS "allocation_collection_group";
ALTER TABLE IF EXISTS "hfdi_historicalprojecttitanplotsallocation" DROP COLUMN IF EXISTS "allocation_collection_agent";
ALTER TABLE IF EXISTS "hfdi_historicalprojecttitanplotsallocation" DROP COLUMN IF EXISTS "allocation_collection_code";
ALTER TABLE IF EXISTS "hfdi_historicalprojecttitanplotsallocation" DROP COLUMN IF EXISTS "allocation_collection_group";

COMMIT;
