# Generated by Django 6.0.5 on 2026-05-18 12:25

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RightsIssueApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('applicant_name', models.CharField(max_length=255)),
                ('national_id', models.CharField(blank=True, max_length=50, null=True)),
                ('cds_account', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('existing_shares', models.BigIntegerField(default=0)),
                ('rights_entitlement', models.BigIntegerField(default=0)),
                ('rights_applied', models.BigIntegerField(default=0)),
                ('additional_shares_applied', models.BigIntegerField(default=0)),
                ('share_price', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('amount_payable', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Received', 'Received'), ('Bounced', 'Bounced')], default='Pending', max_length=20)),
                ('payment_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('shares_allotted', models.BigIntegerField(default=0)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('status', models.CharField(choices=[('Submitted', 'Submitted'), ('Under Review', 'Under Review'), ('Allotted', 'Allotted'), ('Partially Allotted', 'Partially Allotted'), ('Rejected', 'Rejected'), ('Refunded', 'Refunded')], default='Submitted', max_length=20)),
                ('application_date', models.DateField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('input_user', models.CharField(default='me', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'hf_rights_issue_applications',
                'ordering': ['-application_date'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HistoricalRightsIssueApplication',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('application_number', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('applicant_name', models.CharField(max_length=255)),
                ('national_id', models.CharField(blank=True, max_length=50, null=True)),
                ('cds_account', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('existing_shares', models.BigIntegerField(default=0)),
                ('rights_entitlement', models.BigIntegerField(default=0)),
                ('rights_applied', models.BigIntegerField(default=0)),
                ('additional_shares_applied', models.BigIntegerField(default=0)),
                ('share_price', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('amount_payable', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Received', 'Received'), ('Bounced', 'Bounced')], default='Pending', max_length=20)),
                ('payment_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('shares_allotted', models.BigIntegerField(default=0)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('status', models.CharField(choices=[('Submitted', 'Submitted'), ('Under Review', 'Under Review'), ('Allotted', 'Allotted'), ('Partially Allotted', 'Partially Allotted'), ('Rejected', 'Rejected'), ('Refunded', 'Refunded')], default='Submitted', max_length=20)),
                ('application_date', models.DateField(blank=True, editable=False)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('input_user', models.CharField(default='me', max_length=100)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical rights issue application',
                'verbose_name_plural': 'historical rights issue applications',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
