# Generated by Django 4.2.20 on 2026-07-22 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hf_rights_issue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('security', models.CharField(help_text='Name of the security (e.g., stock name, bond name).', max_length=100, null=True)),
                ('shareholders_no', models.CharField(blank=True, help_text='Number of shareholders linked to the security.', max_length=100, null=True)),
                ('account_number', models.CharField(help_text='Unique account number assigned to the account holder.', max_length=50)),
                ('investor_category', models.CharField(blank=True, help_text='Investor category (e.g., individual, corporate, institutional).', max_length=100, null=True)),
                ('tax_category', models.CharField(blank=True, help_text='Tax category of the account holder (e.g., resident, non-resident).', max_length=100, null=True)),
                ('account_name', models.CharField(help_text='Name of the account holder (person or entity).', max_length=255)),
                ('id_passport_customer_number', models.CharField(help_text='ID/Passport/Customer number used for identification.', max_length=100)),
                ('telephone_number', models.CharField(blank=True, help_text='Telephone number for communication with the account holder.', max_length=255, null=True)),
                ('statement_email_address', models.EmailField(blank=True, help_text='Email address where account statements are sent.', max_length=254, null=True)),
                ('country', models.CharField(blank=True, help_text='Country where the account holder is based.', max_length=100, null=True)),
                ('instrument_type', models.CharField(blank=True, help_text='Type of financial instrument associated with the account (e.g., equity, bond).', max_length=100, null=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, help_text='Quantity of the financial instrument held by the account holder.', max_digits=10, null=True)),
                ('allocation_rm', models.CharField(blank=True, help_text='Name or code of the relationship manager responsible for the account.', max_length=100, null=True)),
                ('pf_number_rm_code_name', models.CharField(blank=True, help_text='PF number or RM code/name assigned to the relationship manager.', max_length=100, null=True)),
                ('role', models.CharField(blank=True, help_text='Role of the account holder (e.g., investor, admin, beneficiary).', max_length=50, null=True)),
                ('hf_customer', models.BooleanField(default=False, help_text='Indicates if the account belongs to a high-frequency customer (True/False).')),
                ('cif', models.CharField(blank=True, help_text='Customer Information File (CIF) identifier associated with the account.', max_length=100, null=True)),
                ('hf_segmentation', models.CharField(blank=True, help_text='Segmentation category for high-frequency customers.', max_length=100, null=True)),
                ('hf_phone_number', models.CharField(blank=True, help_text='Phone number specific for high-frequency customer contact.', max_length=100, null=True)),
                ('hf_email', models.EmailField(blank=True, help_text='Email address specific for high-frequency customer contact.', max_length=254, null=True)),
                ('location', models.CharField(blank=True, help_text='Location of the account holder.', max_length=100, null=True)),
                ('rm_managed', models.CharField(blank=True, help_text='Indicates if the account is managed by an RM.', max_length=100, null=True)),
                ('matrix_criteria', models.CharField(blank=True, help_text='Criteria for inclusion in a specific matrix.', max_length=100, null=True)),
                ('branch', models.CharField(blank=True, help_text='Branch of the account.', max_length=100, null=True)),
                ('segment', models.CharField(blank=True, help_text='Segment category.', max_length=100, null=True)),
                ('stock_broker_agent_name', models.CharField(blank=True, help_text='Name of the stock broker or agent.', max_length=255, null=True)),
                ('pal_no', models.CharField(blank=True, help_text='PAL number associated with the account.', max_length=50, null=True)),
                ('current_shares', models.DecimalField(blank=True, decimal_places=2, help_text='Current number of shares held.', max_digits=10, null=True)),
                ('rights', models.CharField(blank=True, help_text='Rights associated with the account.', max_length=255, null=True)),
                ('mobile_no', models.CharField(blank=True, help_text='Primary mobile number.', max_length=50, null=True)),
                ('additional_mobile_no', models.CharField(blank=True, help_text='Additional mobile number.', max_length=50, null=True)),
                ('additional_hfc_phone', models.CharField(blank=True, help_text='Additional phone number for HFC contacts.', max_length=50, null=True)),
                ('other_alternate_phone', models.CharField(blank=True, help_text='Other alternate phone number.', max_length=50, null=True)),
                ('additional_email_1', models.EmailField(blank=True, help_text='Additional email address 1.', max_length=254, null=True)),
                ('other_additional_email_2', models.EmailField(blank=True, help_text='Other additional email address 2.', max_length=254, null=True)),
                ('other_additional_email_3', models.EmailField(blank=True, help_text='Other additional email address 3.', max_length=254, null=True)),
                ('other_additional_email_4', models.EmailField(blank=True, help_text='Other additional email address 4.', max_length=254, null=True)),
                ('names', models.CharField(blank=True, help_text='Full names associated with the account.', max_length=255, null=True)),
                ('mobile', models.CharField(blank=True, help_text='Mobile contact number.', max_length=50, null=True)),
                ('rights_taken', models.CharField(blank=True, help_text='Details of rights taken.', max_length=255, null=True)),
                ('due', models.DecimalField(blank=True, decimal_places=2, help_text='Amount due.', max_digits=50, null=True)),
                ('paid', models.DecimalField(blank=True, decimal_places=2, help_text='Amount paid.', max_digits=50, null=True)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, help_text='Remaining balance.', max_digits=50, null=True)),
                ('email', models.EmailField(blank=True, help_text='Primary email address.', max_length=254, null=True)),
            ],
            options={
                'verbose_name': 'Security Detail',
                'verbose_name_plural': 'Security Details',
                'db_table': 'security_detail',
                'managed': False,
            },
        ),
    ]
