"""The adopt path in migration 0019 — the one that runs on production.

The first version of 0019 was a plain CreateModel and died on the host with
``relation "premium_types_mapping" already exists``. The table is already there,
built by somebody else, and this repo has never seen its columns.

The rewritten migration introspects it and adds only what is missing. That
branch cannot be exercised by building the test database (migrations run once,
against nothing), so its functions are driven directly here against tables
shaped the way production might be. DDL is transactional in PostgreSQL, so each
test's damage rolls back with the test.
"""
from importlib import import_module

from django.db import connection
from django.test import TransactionTestCase

# Migration module names start with a digit, so they cannot be imported with
# `from ... import`. Named in full rather than discovered, so renaming the
# migration breaks this loudly instead of silently testing nothing.
_m = import_module(
    "apps.staff_management.migrations"
    ".0019_historicalpremiumtypemapping_premiumtypemapping_and_more"
)
COLUMNS, TABLE = _m.COLUMNS, _m.TABLE
adopt, add_constraint, _columns = _m.adopt, _m.add_constraint, _m._columns


class _Editor:
    """The two attributes the migration functions use."""
    class _Conn:
        def cursor(self):
            return connection.cursor()
    connection = _Conn()


def _drop():
    with connection.cursor() as cur:
        cur.execute(f"DROP TABLE IF EXISTS {TABLE} CASCADE")


def _cols():
    with connection.cursor() as cur:
        return _columns(cur)


class AdoptTests(TransactionTestCase):
    """TransactionTestCase: these create and drop real tables."""

    def tearDown(self):
        # Put the table back the way the rest of the suite expects it.
        _drop()
        with connection.cursor() as cur:
            cur.execute(f"""
                CREATE TABLE {TABLE} (
                    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    product varchar(255) NOT NULL,
                    vic_check varchar(100) NOT NULL DEFAULT '',
                    life_policy_check varchar(100) NOT NULL DEFAULT '',
                    premium_type varchar(100) NOT NULL DEFAULT '',
                    policy_category varchar(100) NOT NULL DEFAULT '',
                    updated_at timestamptz NOT NULL DEFAULT now(),
                    updated_by varchar(150) NOT NULL DEFAULT ''
                )""")

    def test_it_creates_the_table_when_it_is_genuinely_absent(self):
        _drop()
        self.assertIsNone(_cols())
        adopt(None, _Editor())
        self.assertTrue(set(COLUMNS).issubset(_cols()))

    def test_an_existing_full_table_is_left_alone(self):
        """The production case. Nothing is altered, nothing is dropped."""
        _drop()
        with connection.cursor() as cur:
            cur.execute(f"""
                CREATE TABLE {TABLE} (
                    id bigserial PRIMARY KEY,
                    product varchar(255),
                    vic_check varchar(100),
                    life_policy_check varchar(100),
                    premium_type varchar(100),
                    policy_category varchar(100),
                    updated_at timestamptz,
                    updated_by varchar(150)
                )""")
            cur.execute(f"INSERT INTO {TABLE} (product) VALUES ('EXISTING PRODUCT')")
        before = _cols()
        adopt(None, _Editor())
        self.assertEqual(_cols(), before)
        with connection.cursor() as cur:
            cur.execute(f"SELECT product FROM {TABLE}")
            self.assertEqual(cur.fetchall(), [("EXISTING PRODUCT",)])

    def test_missing_columns_are_added_and_existing_rows_survive(self):
        """A table that predates the classification columns."""
        _drop()
        with connection.cursor() as cur:
            cur.execute(f"""
                CREATE TABLE {TABLE} (
                    id bigserial PRIMARY KEY,
                    product varchar(255)
                )""")
            cur.execute(f"INSERT INTO {TABLE} (product) VALUES ('ipp')")
        adopt(None, _Editor())
        self.assertTrue(set(COLUMNS).issubset(_cols()))
        with connection.cursor() as cur:
            cur.execute(f"SELECT product, premium_type FROM {TABLE}")
            # The row is still there; the new column defaulted rather than
            # failing the ALTER on a populated table.
            self.assertEqual(cur.fetchall(), [("ipp", "")])

    def test_extra_columns_this_repo_does_not_know_about_are_kept(self):
        _drop()
        with connection.cursor() as cur:
            cur.execute(f"""
                CREATE TABLE {TABLE} (
                    id bigserial PRIMARY KEY,
                    product varchar(255),
                    some_upstream_column text
                )""")
        adopt(None, _Editor())
        self.assertIn("some_upstream_column", _cols())

    def test_a_table_with_no_id_stops_rather_than_half_working(self):
        """Django's implicit pk is `id`. Without one every query selects a
        column that is not there, and the page 500s naming the column but not
        the cause. Better to fail the migration and say so."""
        _drop()
        with connection.cursor() as cur:
            cur.execute(f"CREATE TABLE {TABLE} (product varchar(255))")
        with self.assertRaises(RuntimeError) as caught:
            adopt(None, _Editor())
        message = str(caught.exception)
        self.assertIn("no \"id\" column", message)
        self.assertIn("product", message)   # the real columns, for diagnosis

    def test_running_it_twice_changes_nothing(self):
        _drop()
        adopt(None, _Editor())
        first = _cols()
        adopt(None, _Editor())
        self.assertEqual(_cols(), first)


class ConstraintTests(TransactionTestCase):

    def setUp(self):
        _drop()
        with connection.cursor() as cur:
            cur.execute(f"""
                CREATE TABLE {TABLE} (
                    id bigserial PRIMARY KEY,
                    product varchar(255) NOT NULL,
                    vic_check varchar(100) NOT NULL DEFAULT '',
                    life_policy_check varchar(100) NOT NULL DEFAULT '',
                    premium_type varchar(100) NOT NULL DEFAULT '',
                    policy_category varchar(100) NOT NULL DEFAULT '',
                    updated_at timestamptz NOT NULL DEFAULT now(),
                    updated_by varchar(150) NOT NULL DEFAULT ''
                )""")

    tearDown = AdoptTests.tearDown

    def _index_exists(self):
        with connection.cursor() as cur:
            cur.execute("SELECT to_regclass('uniq_premium_types_mapping_product')")
            return cur.fetchone()[0] is not None

    def test_the_index_is_created_on_clean_data(self):
        with connection.cursor() as cur:
            cur.execute(f"INSERT INTO {TABLE} (product) VALUES ('ipp'), ('IDD')")
        add_constraint(None, _Editor())
        self.assertTrue(self._index_exists())

    def test_existing_case_duplicates_do_not_fail_the_deploy(self):
        """The table already holds rows this repo has never seen. If two of
        them differ only in case the index cannot be built — that is a data
        question for Bancassurance, not a reason to stop a release."""
        with connection.cursor() as cur:
            cur.execute(f"INSERT INTO {TABLE} (product) VALUES ('ipp'), ('IPP')")
        add_constraint(None, _Editor())          # must not raise
        self.assertFalse(self._index_exists())

    def test_it_is_idempotent(self):
        add_constraint(None, _Editor())
        add_constraint(None, _Editor())
        self.assertTrue(self._index_exists())
