# Generated by Django 4.2.20 on 2026-10-05 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalDesignBrief',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('reference', models.CharField(blank=True, db_index=True, max_length=20)),
                ('design_item', models.CharField(help_text="The design item requested, e.g. 'Diaspora mortgage flyer'.", max_length=200)),
                ('item_type', models.CharField(choices=[('poster', 'Poster'), ('flyer', 'Flyer / leaflet'), ('banner', 'Banner / backdrop'), ('social', 'Social media post'), ('video', 'Video / motion'), ('brochure', 'Brochure'), ('email', 'Email / newsletter artwork'), ('branding', 'Branding / identity'), ('signage', 'Branch signage'), ('presentation', 'Presentation / deck'), ('print', 'Print production'), ('other', 'Other')], default='other', max_length=20)),
                ('brief', models.TextField(blank=True, help_text='The briefing: what it is for, the message, sizes, copy, references.')),
                ('department', models.CharField(db_index=True, max_length=120)),
                ('raised_by_name', models.CharField(blank=True, help_text="Snapshot of the requester's name, so a removed account does not erase who asked.", max_length=150)),
                ('addressed_to', models.CharField(help_text='Who the brief is to — a person, team or audience.', max_length=150)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('status', models.CharField(choices=[('new', 'Awaiting designer'), ('assigned', 'Assigned'), ('in_progress', 'In progress'), ('submitted', 'Submitted for review'), ('rework', 'Rework'), ('approved', 'Approved'), ('cancelled', 'Cancelled')], db_index=True, default='new', max_length=15)),
                ('release_date', models.DateField(blank=True, db_index=True, help_text='Target release date for the finished item.', null=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('rework_count', models.PositiveSmallIntegerField(default=0)),
                ('last_rework_at', models.DateTimeField(blank=True, null=True)),
                ('last_rework_reason', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('satisfaction', models.PositiveSmallIntegerField(blank=True, help_text='1-5, given by whoever raised the brief.', null=True)),
                ('closing_note', models.TextField(blank=True)),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('approved_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('assigned_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('assigned_designer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('raised_by', models.ForeignKey(blank=True, db_constraint=False, help_text='Who the brief is from. Taken from the signed-in user.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical design brief',
                'verbose_name_plural': 'historical design briefs',
                'db_table': 'design_brief_history',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='DesignBrief',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(blank=True, db_index=True, max_length=20, unique=True)),
                ('design_item', models.CharField(help_text="The design item requested, e.g. 'Diaspora mortgage flyer'.", max_length=200)),
                ('item_type', models.CharField(choices=[('poster', 'Poster'), ('flyer', 'Flyer / leaflet'), ('banner', 'Banner / backdrop'), ('social', 'Social media post'), ('video', 'Video / motion'), ('brochure', 'Brochure'), ('email', 'Email / newsletter artwork'), ('branding', 'Branding / identity'), ('signage', 'Branch signage'), ('presentation', 'Presentation / deck'), ('print', 'Print production'), ('other', 'Other')], default='other', max_length=20)),
                ('brief', models.TextField(blank=True, help_text='The briefing: what it is for, the message, sizes, copy, references.')),
                ('department', models.CharField(db_index=True, max_length=120)),
                ('raised_by_name', models.CharField(blank=True, help_text="Snapshot of the requester's name, so a removed account does not erase who asked.", max_length=150)),
                ('addressed_to', models.CharField(help_text='Who the brief is to — a person, team or audience.', max_length=150)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('status', models.CharField(choices=[('new', 'Awaiting designer'), ('assigned', 'Assigned'), ('in_progress', 'In progress'), ('submitted', 'Submitted for review'), ('rework', 'Rework'), ('approved', 'Approved'), ('cancelled', 'Cancelled')], db_index=True, default='new', max_length=15)),
                ('release_date', models.DateField(blank=True, db_index=True, help_text='Target release date for the finished item.', null=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('rework_count', models.PositiveSmallIntegerField(default=0)),
                ('last_rework_at', models.DateTimeField(blank=True, null=True)),
                ('last_rework_reason', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('satisfaction', models.PositiveSmallIntegerField(blank=True, help_text='1-5, given by whoever raised the brief.', null=True)),
                ('closing_note', models.TextField(blank=True)),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='design_briefs_approved', to=settings.AUTH_USER_MODEL)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='design_briefs_allocated', to=settings.AUTH_USER_MODEL)),
                ('assigned_designer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='design_briefs_assigned', to=settings.AUTH_USER_MODEL)),
                ('raised_by', models.ForeignKey(blank=True, help_text='Who the brief is from. Taken from the signed-in user.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='design_briefs_raised', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'design_brief',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BriefEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('raised', 'Raised'), ('assigned', 'Designer assigned'), ('reassigned', 'Reassigned'), ('started', 'Work started'), ('submitted', 'Submitted for review'), ('rework', 'Rework requested'), ('approved', 'Approved'), ('cancelled', 'Cancelled'), ('reopened', 'Reopened from archive'), ('note', 'Note'), ('edited', 'Brief edited')], max_length=15)),
                ('actor_name', models.CharField(blank=True, max_length=150)),
                ('note', models.TextField(blank=True)),
                ('from_status', models.CharField(blank=True, max_length=15)),
                ('to_status', models.CharField(blank=True, max_length=15)),
                ('at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='design_brief_events', to=settings.AUTH_USER_MODEL)),
                ('brief', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='design_briefs.designbrief')),
            ],
            options={
                'db_table': 'design_brief_event',
                'ordering': ['at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='designbrief',
            index=models.Index(fields=['status', '-created_at'], name='design_brie_status_d056e5_idx'),
        ),
        migrations.AddIndex(
            model_name='designbrief',
            index=models.Index(fields=['assigned_designer', 'status'], name='design_brie_assigne_82ad47_idx'),
        ),
        migrations.AddIndex(
            model_name='designbrief',
            index=models.Index(fields=['raised_by', '-created_at'], name='design_brie_raised__734a64_idx'),
        ),
        migrations.AddIndex(
            model_name='designbrief',
            index=models.Index(fields=['release_date'], name='design_brie_release_9b2e9f_idx'),
        ),
        migrations.AddIndex(
            model_name='designbrief',
            index=models.Index(fields=['department', 'status'], name='design_brie_departm_f92732_idx'),
        ),
        migrations.AddIndex(
            model_name='briefevent',
            index=models.Index(fields=['brief', 'at'], name='design_brie_brief_i_e5ca71_idx'),
        ),
    ]
