# Generated by Django 4.2.20 on 2026-10-05 17:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('design_briefs', '0002_seed_marketing_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='briefevent',
            name='kind',
            field=models.CharField(choices=[('raised', 'Raised'), ('assigned', 'Designer assigned'), ('reassigned', 'Reassigned'), ('started', 'Work started'), ('submitted', 'Submitted for review'), ('rework', 'Rework requested'), ('approved', 'Approved'), ('cancelled', 'Cancelled'), ('reopened', 'Reopened from archive'), ('note', 'Note'), ('edited', 'Brief edited'), ('proof', 'Artwork uploaded'), ('comment', 'Comment')], max_length=15),
        ),
        migrations.CreateModel(
            name='BriefProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveSmallIntegerField()),
                ('preview', models.BinaryField()),
                ('preview_content_type', models.CharField(default='image/jpeg', max_length=40)),
                ('thumbnail', models.BinaryField()),
                ('thumbnail_content_type', models.CharField(default='image/jpeg', max_length=40)),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('original_name', models.CharField(blank=True, max_length=200)),
                ('original_bytes', models.PositiveIntegerField(default=0)),
                ('source_url', models.URLField(blank=True, max_length=500)),
                ('note', models.TextField(blank=True)),
                ('uploaded_by_name', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('brief', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proofs', to='design_briefs.designbrief')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='design_proofs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'design_brief_proof',
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='BriefDeliverable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=160)),
                ('done', models.BooleanField(default=False)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brief', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='design_briefs.designbrief')),
                ('done_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='design_deliverables_done', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'design_brief_deliverable',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BriefComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('author_name', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='design_brief_comments', to=settings.AUTH_USER_MODEL)),
                ('brief', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='design_briefs.designbrief')),
                ('proof', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='design_briefs.briefproof')),
            ],
            options={
                'db_table': 'design_brief_comment',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='briefproof',
            index=models.Index(fields=['brief', '-version'], name='design_brie_brief_i_b358dd_idx'),
        ),
        migrations.AddConstraint(
            model_name='briefproof',
            constraint=models.UniqueConstraint(fields=('brief', 'version'), name='design_proof_version_unique'),
        ),
        migrations.AddIndex(
            model_name='briefdeliverable',
            index=models.Index(fields=['brief', 'order'], name='design_brie_brief_i_67e6e5_idx'),
        ),
        migrations.AddIndex(
            model_name='briefcomment',
            index=models.Index(fields=['brief', 'created_at'], name='design_brie_brief_i_e518c4_idx'),
        ),
    ]
