# Generated by Django 4.2.20 on 2026-10-06 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('design_briefs', '0003_alter_briefevent_kind_briefproof_briefdeliverable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='briefcomment',
            name='h',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='briefcomment',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='briefcomment',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='briefcomment',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='design_comments_resolved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='briefcomment',
            name='w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='briefcomment',
            name='x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='briefcomment',
            name='y',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='briefcomment',
            index=models.Index(fields=['proof', 'created_at'], name='design_brie_proof_i_5718ee_idx'),
        ),
    ]
