# Generated by Django 4.2.20 on 2026-09-29 05:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPipelineEntry',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('kind', models.CharField(choices=[('asset', 'Assets Pipeline'), ('trade', 'Trade Pipeline'), ('deposit', 'Deposits'), ('liability', 'Liabilities')], db_index=True, max_length=12)),
                ('sales_code', models.CharField(blank=True, db_index=True, max_length=32)),
                ('rm_name', models.CharField(blank=True, max_length=150)),
                ('branch', models.CharField(blank=True, default='Commercial', max_length=120)),
                ('segment', models.CharField(blank=True, db_index=True, default='COMMERCIAL', max_length=60)),
                ('customer_name', models.CharField(max_length=200)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('amount_to_disburse', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('product', models.CharField(blank=True, max_length=160)),
                ('deposit_product', models.CharField(blank=True, choices=[('CASA', 'CASA'), ('FD', 'Fixed deposit')], max_length=8)),
                ('account_no', models.CharField(blank=True, max_length=40)),
                ('broad_stage', models.CharField(blank=True, choices=[('discussion', 'Discussion — not yet in I-Apply'), ('application', 'Application — in the system, not yet approved'), ('approved', 'Approved — anywhere after approval'), ('disbursed', 'Disbursed')], max_length=20)),
                ('stage', models.CharField(blank=True, choices=[('discussion', 'Discussion'), ('at_branch', 'At branch'), ('at_credit_analyst', 'At credit analyst'), ('at_credit_risk', 'At credit risk'), ('offer_letter_generation', 'At offer letter generation'), ('offer_letter_at_branch', 'Offer letter at branch for collection'), ('awaiting_execution', 'Awaiting customer to execute offer letter'), ('valuation', 'Valuation'), ('charge_preparation', 'Charge preparation'), ('charge_dispatch', 'Charge dispatch to customer'), ('charge_execution', 'Charge execution by customer'), ('awaiting_registration', 'Awaiting registration process'), ('disbursement', 'Disbursement')], max_length=30)),
                ('expected_date', models.DateField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True, help_text='Cleared rather than deleted, so a dropped deal stays in the record and can be explained.')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, db_index=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical pipeline entry',
                'verbose_name_plural': 'historical Pipeline entries',
                'db_table': 'commercial_pipeline_entry_history',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='PipelineEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('asset', 'Assets Pipeline'), ('trade', 'Trade Pipeline'), ('deposit', 'Deposits'), ('liability', 'Liabilities')], db_index=True, max_length=12)),
                ('sales_code', models.CharField(blank=True, db_index=True, max_length=32)),
                ('rm_name', models.CharField(blank=True, max_length=150)),
                ('branch', models.CharField(blank=True, default='Commercial', max_length=120)),
                ('segment', models.CharField(blank=True, db_index=True, default='COMMERCIAL', max_length=60)),
                ('customer_name', models.CharField(max_length=200)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('amount_to_disburse', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('product', models.CharField(blank=True, max_length=160)),
                ('deposit_product', models.CharField(blank=True, choices=[('CASA', 'CASA'), ('FD', 'Fixed deposit')], max_length=8)),
                ('account_no', models.CharField(blank=True, max_length=40)),
                ('broad_stage', models.CharField(blank=True, choices=[('discussion', 'Discussion — not yet in I-Apply'), ('application', 'Application — in the system, not yet approved'), ('approved', 'Approved — anywhere after approval'), ('disbursed', 'Disbursed')], max_length=20)),
                ('stage', models.CharField(blank=True, choices=[('discussion', 'Discussion'), ('at_branch', 'At branch'), ('at_credit_analyst', 'At credit analyst'), ('at_credit_risk', 'At credit risk'), ('offer_letter_generation', 'At offer letter generation'), ('offer_letter_at_branch', 'Offer letter at branch for collection'), ('awaiting_execution', 'Awaiting customer to execute offer letter'), ('valuation', 'Valuation'), ('charge_preparation', 'Charge preparation'), ('charge_dispatch', 'Charge dispatch to customer'), ('charge_execution', 'Charge execution by customer'), ('awaiting_registration', 'Awaiting registration process'), ('disbursement', 'Disbursement')], max_length=30)),
                ('expected_date', models.DateField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True, help_text='Cleared rather than deleted, so a dropped deal stays in the record and can be explained.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pipeline_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pipeline_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Pipeline entries',
                'db_table': 'commercial_pipeline_entry',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['kind', 'is_active', '-updated_at'], name='commercial__kind_fcc091_idx'), models.Index(fields=['sales_code', 'kind'], name='commercial__sales_c_29bf16_idx'), models.Index(fields=['segment', 'kind'], name='commercial__segment_33e14d_idx')],
            },
        ),
    ]
