# Generated by Django 6.0.5 on 2026-05-18 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('deposits', 'Deposits'), ('loans', 'Loans'), ('customers', 'Customers'), ('revenue', 'Revenue'), ('collections', 'Collections')], max_length=50)),
                ('metric_name', models.CharField(max_length=255)),
                ('metric_value', models.DecimalField(decimal_places=5, max_digits=30)),
                ('segment', models.CharField(blank=True, max_length=100, null=True)),
                ('branch', models.CharField(blank=True, max_length=100, null=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'analytics_snapshots',
                'ordering': ['-computed_at'],
                'managed': True,
                'indexes': [models.Index(fields=['category', 'period_start'], name='analytics_s_categor_a697be_idx'), models.Index(fields=['segment', 'period_start'], name='analytics_s_segment_474199_idx')],
            },
        ),
    ]
