# Generated by Django 4.2.20 on 2026-08-17 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=300)),
                ('label', models.CharField(blank=True, default='', max_length=150)),
                ('event_type', models.CharField(choices=[('pageview', 'Page view'), ('click', 'Click'), ('action', 'Action')], default='pageview', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_activity_events',
                'ordering': ['-created_at'],
                'managed': True,
                'indexes': [models.Index(fields=['user', 'created_at'], name='user_activi_user_id_15ef47_idx'), models.Index(fields=['path'], name='user_activi_path_83502c_idx'), models.Index(fields=['created_at'], name='user_activi_created_93dda7_idx')],
            },
        ),
    ]
