# Generated by Django 6.0.5 on 2026-06-23 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_feedback_date_alter_historicalfeedback_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetailAllocatedPortfolioUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_id', models.IntegerField(blank=True, null=True)),
                ('customer_name', models.TextField(blank=True, null=True)),
                ('sales_code', models.TextField(blank=True, null=True)),
                ('rm_name', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('branch', models.IntegerField(blank=True, null=True)),
                ('main_segment', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'retail_allocated_portfolio_upload',
                'ordering': ['-uploaded_at'],
                'managed': True,
            },
        ),
    ]
