# Generated by Django 4.2.20 on 2026-09-28 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service_desk', '0010_ticketattachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='KbArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('article', 'Article'), ('reply', 'Canned reply')], default='article', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('body', models.TextField()),
                ('is_published', models.BooleanField(default=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='service_desk.ticketcategory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kb_articles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'service_desk_kb_article',
                'ordering': ['-views', 'title'],
                'indexes': [models.Index(fields=['kind', 'is_published'], name='service_des_kind_df9724_idx'), models.Index(fields=['category', 'is_published'], name='service_des_categor_68508d_idx')],
            },
        ),
    ]
