# Generated by Django 6.0.5 on 2026-05-14 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BranchEmployeeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.DecimalField(blank=True, decimal_places=5, max_digits=990, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('national_id', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_birth', models.DateTimeField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.TextField(blank=True, null=True)),
                ('date_of_employment', models.DateTimeField(blank=True, null=True)),
                ('service_code', models.TextField(blank=True, null=True)),
                ('service_years', models.IntegerField(blank=True, null=True)),
                ('division', models.TextField(blank=True, null=True)),
                ('department', models.TextField(blank=True, null=True)),
                ('unit', models.TextField(blank=True, null=True)),
                ('org_unit', models.TextField(blank=True, null=True)),
                ('grade', models.TextField(blank=True, null=True)),
                ('job_title', models.TextField(blank=True, null=True)),
                ('exit', models.IntegerField(blank=True, null=True)),
                ('promotion', models.IntegerField(blank=True, null=True)),
                ('new', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'employee_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PerformanceActual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_code', models.CharField(max_length=50)),
                ('staff_name', models.CharField(blank=True, max_length=255, null=True)),
                ('staff_role', models.CharField(blank=True, max_length=255, null=True)),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
                ('kpi_name', models.CharField(max_length=255)),
                ('month', models.DateField()),
                ('actual_value', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('target_value', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
            ],
            options={
                'db_table': 'scorecard_performance_actuals',
                'ordering': ['-month', 'sales_code'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ScorecardKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('category', models.CharField(choices=[('deposits', 'Deposits'), ('loans', 'Loans'), ('revenue', 'Revenue'), ('customers', 'New Customers'), ('quality', 'Quality')], default='deposits', max_length=50)),
                ('weight', models.FloatField(default=1.0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'scorecard_kpis',
                'ordering': ['name'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ScorecardRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'scorecard_roles',
                'ordering': ['name'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EmployeeMonthlyPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_code', models.CharField(max_length=50)),
                ('staff_name', models.CharField(blank=True, max_length=255, null=True)),
                ('staff_role', models.CharField(blank=True, max_length=255, null=True)),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
                ('org_unit', models.CharField(blank=True, max_length=255, null=True)),
                ('month', models.DateField()),
                ('deposit_actual', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('deposit_target', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('loan_actual', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('loan_target', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('revenue_actual', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('revenue_target', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('new_customers_actual', models.IntegerField(default=0)),
                ('new_customers_target', models.IntegerField(default=0)),
                ('deposit_score', models.FloatField(default=0)),
                ('loan_score', models.FloatField(default=0)),
                ('revenue_score', models.FloatField(default=0)),
                ('new_customers_score', models.FloatField(default=0)),
                ('total_score', models.FloatField(default=0)),
                ('grade', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=5, null=True)),
                ('kpis_met', models.CharField(blank=True, max_length=50, null=True)),
                ('generated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'employee_monthly_performance',
                'ordering': ['-month', '-total_score'],
                'managed': True,
                'unique_together': {('sales_code', 'month')},
            },
        ),
        migrations.CreateModel(
            name='RoleKPIMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=1.0)),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_mappings', to='staff_management.scorecardkpi')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_mappings', to='staff_management.scorecardrole')),
            ],
            options={
                'db_table': 'scorecard_role_kpi_mappings',
                'managed': True,
                'unique_together': {('role', 'kpi')},
            },
        ),
    ]
