# Generated by Django 6.0.5 on 2026-06-21 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff_management', '0003_sckpi_historicalscemployeeperformanceactual_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scemployeemonthlyperformance',
            options={'ordering': ['-eom_date', 'sales_code', 'kpi_order'], 'verbose_name': 'Scorecard Employee Monthly Performance', 'verbose_name_plural': 'Scorecard Employee Monthly Performances'},
        ),
    ]
