# Generated by Django 6.0.5 on 2026-06-23 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_management', '0004_alter_scemployeemonthlyperformance_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyDormancyConvertedAccountUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_num', models.CharField(blank=True, max_length=255, null=True)),
                ('cust_cif', models.BigIntegerField(blank=True, null=True)),
                ('brn_code', models.IntegerField(blank=True, null=True)),
                ('prod_id', models.IntegerField(blank=True, null=True)),
                ('full_name', models.CharField(blank=True, max_length=200, null=True)),
                ('customer_segment', models.CharField(blank=True, max_length=20, null=True)),
                ('last_dormant_date', models.DateField(blank=True, null=True)),
                ('current_status', models.CharField(blank=True, max_length=20, null=True)),
                ('current_bal', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('reactivation_date', models.DateField(blank=True, null=True)),
                ('action_user', models.CharField(blank=True, max_length=200, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'daily_dormancy_converted_accounts_upload',
                'ordering': ['-uploaded_at'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DailySalesAccountsWithCtoUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_cif', models.BigIntegerField(blank=True, null=True)),
                ('cust_open_date', models.DateField(blank=True, null=True)),
                ('full_name', models.CharField(blank=True, max_length=200, null=True)),
                ('brn_code', models.IntegerField(blank=True, null=True)),
                ('acc_num', models.CharField(blank=True, max_length=255, null=True)),
                ('sale_code', models.CharField(blank=True, max_length=255, null=True)),
                ('prod_id', models.IntegerField(blank=True, null=True)),
                ('customer_segment', models.CharField(blank=True, max_length=255, null=True)),
                ('acc_open_date', models.DateField(blank=True, null=True)),
                ('bal', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('cust_cto', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('account_cto', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('dec_23_bal', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('curr_24_bal', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('total_account_before_2024', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('account_status', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'daily_sales_accounts_with_cto_upload',
                'ordering': ['-uploaded_at'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MerchantBankTillManualUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_id', models.CharField(blank=True, max_length=200, null=True)),
                ('credit_account', models.CharField(blank=True, max_length=200, null=True)),
                ('account_no', models.CharField(blank=True, max_length=200, null=True)),
                ('account_name', models.CharField(blank=True, max_length=255, null=True)),
                ('creation_date', models.DateTimeField(blank=True, null=True)),
                ('sellercode', models.CharField(blank=True, max_length=200, null=True)),
                ('kra_pin', models.CharField(blank=True, max_length=200, null=True)),
                ('current_branch', models.CharField(blank=True, max_length=200, null=True)),
                ('brn_zone', models.CharField(blank=True, max_length=200, null=True)),
                ('seller_code', models.CharField(blank=True, max_length=200, null=True)),
                ('staff_role', models.CharField(blank=True, max_length=200, null=True)),
                ('staff_name', models.CharField(blank=True, max_length=200, null=True)),
                ('first_time_trx', models.DateTimeField(blank=True, null=True)),
                ('latest_time_trx', models.DateTimeField(blank=True, null=True)),
                ('number_trx_since_inception', models.IntegerField(blank=True, null=True)),
                ('amount_since_inception', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('current_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'merchant_bank_till_manual_upload',
                'ordering': ['-uploaded_at'],
                'managed': True,
            },
        ),
    ]
