# Generated by Django 6.0.5 on 2026-07-02 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff_management', '0005_dailydormancyconvertedaccountupload_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employeemonthlyperformance',
            table='employee_monthly_performance_v2',
        ),
    ]
