# Generated by Django 4.2.20 on 2026-07-28 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_management', '0006_alter_employeemonthlyperformance_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorecardkpi',
            name='kpi_calculation_mode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='scorecardkpi',
            name='kpi_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='scorecardkpi',
            name='kpi_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scorecardkpi',
            name='kpi_rating_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='scorecardkpi',
            name='score_cap',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='scorecardrole',
            name='role_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='scorecardrole',
            name='role_type',
            field=models.CharField(blank=True, choices=[('IC', 'IC'), ('MGR', 'MGR'), ('EXEC', 'EXEC')], max_length=10, null=True),
        ),
    ]
