# Generated by Django 4.2.20 on 2026-08-10 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_management', '0007_scorecardkpi_kpi_calculation_mode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DSRSalesCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pf_number', models.CharField(max_length=30, unique=True, verbose_name='PF Number')),
                ('sales_code', models.CharField(max_length=20, unique=True, verbose_name='Sales Code')),
                ('salesperson', models.CharField(blank=True, max_length=200)),
                ('branch', models.CharField(blank=True, max_length=120)),
                ('department', models.CharField(blank=True, max_length=120)),
                ('role', models.CharField(blank=True, max_length=60)),
                ('team_leader', models.CharField(blank=True, max_length=200)),
                ('date_of_employment', models.DateField(blank=True, null=True)),
                ('allocation_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'dsr_sales_codes',
                'ordering': ['sales_code'],
                'managed': True,
            },
        ),
    ]
