# Generated by Django 4.2.20 on 2026-08-10 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_management', '0008_dsrsalescode'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamLeaderBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=120, unique=True, verbose_name='Branch')),
                ('team_leader', models.CharField(max_length=200, verbose_name='Team Leader')),
                ('role', models.CharField(blank=True, default='PB DSR', max_length=60)),
                ('active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'team_leader_branches',
                'ordering': ['team_leader', 'branch'],
                'managed': True,
            },
        ),
    ]
