# Generated by Django 4.2.20 on 2026-08-18 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_management', '0009_teamleaderbranch'),
    ]

    operations = [
        migrations.CreateModel(
            name='DSRRoleTeamLeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(db_index=True, max_length=60)),
                ('team_leader', models.CharField(max_length=200)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'dsr_role_team_leaders',
                'ordering': ['role', 'sort_order', 'team_leader'],
                'managed': True,
            },
        ),
        migrations.AddConstraint(
            model_name='dsrroleteamleader',
            constraint=models.UniqueConstraint(fields=('role', 'team_leader'), name='uniq_role_team_leader'),
        ),
    ]
