# Generated by Django 4.2.20 on 2026-09-02 08:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_management', '0011_seed_dsr_role_team_leaders'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchDepartmentCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(db_index=True, max_length=120, verbose_name='Branch')),
                ('department', models.CharField(db_index=True, max_length=120, verbose_name='Department')),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(2000)])),
                ('month', models.IntegerField(help_text='1-12', validators=[django.core.validators.MinValueValidator(1)])),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('staff_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('other_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, default='', max_length=150)),
            ],
            options={
                'verbose_name': 'Branch department cost',
                'verbose_name_plural': 'Branch department costs',
                'db_table': 'branch_department_cost',
                'ordering': ['branch', 'department', '-year', '-month'],
                'managed': True,
            },
        ),
        migrations.AddConstraint(
            model_name='branchdepartmentcost',
            constraint=models.UniqueConstraint(fields=('branch', 'department', 'year', 'month'), name='uniq_branch_department_cost_period'),
        ),
        migrations.AddConstraint(
            model_name='branchdepartmentcost',
            constraint=models.CheckConstraint(check=models.Q(('month__gte', 1), ('month__lte', 12)), name='branch_department_cost_month_range'),
        ),
    ]
