# Generated by Django 4.2.20 on 2026-09-16 10:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff_management', '0014_alter_merchantbanktillmanualdata_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchPropertyTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brn_code', models.IntegerField(db_index=True, help_text='Warehouse brn_code, e.g. 200 for REHANI BRANCH.', verbose_name='Branch code')),
                ('staff_branch', models.CharField(help_text='Branch name as the plan spells it.', max_length=120, verbose_name='Branch')),
                ('staff_zone', models.CharField(blank=True, db_index=True, default='', help_text='e.g. Zone A.', max_length=60, verbose_name='Zone')),
                ('year', models.IntegerField(db_index=True, help_text='Plan year the target applies to.', validators=[django.core.validators.MinValueValidator(2000)])),
                ('target_properties', models.DecimalField(decimal_places=8, default=0, help_text='Units planned for the year. Fractional by design.', max_digits=14, verbose_name='Target properties')),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, default='', max_length=150)),
            ],
            options={
                'verbose_name': 'Branch property target',
                'verbose_name_plural': 'Branch property targets',
                'db_table': 'branch_property_target',
                'ordering': ['-year', 'staff_zone', 'staff_branch'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HistoricalBranchPropertyTarget',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('brn_code', models.IntegerField(db_index=True, help_text='Warehouse brn_code, e.g. 200 for REHANI BRANCH.', verbose_name='Branch code')),
                ('staff_branch', models.CharField(help_text='Branch name as the plan spells it.', max_length=120, verbose_name='Branch')),
                ('staff_zone', models.CharField(blank=True, db_index=True, default='', help_text='e.g. Zone A.', max_length=60, verbose_name='Zone')),
                ('year', models.IntegerField(db_index=True, help_text='Plan year the target applies to.', validators=[django.core.validators.MinValueValidator(2000)])),
                ('target_properties', models.DecimalField(decimal_places=8, default=0, help_text='Units planned for the year. Fractional by design.', max_digits=14, verbose_name='Target properties')),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_by', models.CharField(blank=True, default='', max_length=150)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Branch property target',
                'verbose_name_plural': 'historical Branch property targets',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddConstraint(
            model_name='branchpropertytarget',
            constraint=models.UniqueConstraint(fields=('brn_code', 'year'), name='uniq_branch_property_target_year'),
        ),
        migrations.AddConstraint(
            model_name='branchpropertytarget',
            constraint=models.CheckConstraint(check=models.Q(('target_properties__gte', 0)), name='branch_property_target_non_negative'),
        ),
    ]
