# Generated by Django 4.2.20 on 2026-09-16 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_management', '0016_seed_branch_property_targets'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchfinalemployeedmcdata',
            name='target_properties',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Property units planned for the year. Fractional by design.', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='historicalbranchfinalemployeedmcdata',
            name='target_properties',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Property units planned for the year. Fractional by design.', max_digits=14, null=True),
        ),
    ]
