# Generated by Django 4.2.20 on 2026-09-17 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff_management', '0018_fill_dmc_target_properties'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPremiumTypeMapping',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('product', models.CharField(help_text='Product name as it appears on the policy, e.g. WHOLE LIFE.', max_length=255, verbose_name='Product')),
                ('vic_check', models.CharField(blank=True, default='', help_text='Observed value: "vic".', max_length=100)),
                ('life_policy_check', models.CharField(blank=True, default='', help_text='Observed value: "life".', max_length=100)),
                ('premium_type', models.CharField(blank=True, db_index=True, default='', help_text='Observed value: "non-motor".', max_length=100)),
                ('policy_category', models.CharField(blank=True, db_index=True, default='', help_text='Observed value: "Life".', max_length=100)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_by', models.CharField(blank=True, default='', max_length=150)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Premium type mapping',
                'verbose_name_plural': 'historical Premium type mappings',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='PremiumTypeMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(help_text='Product name as it appears on the policy, e.g. WHOLE LIFE.', max_length=255, verbose_name='Product')),
                ('vic_check', models.CharField(blank=True, default='', help_text='Observed value: "vic".', max_length=100)),
                ('life_policy_check', models.CharField(blank=True, default='', help_text='Observed value: "life".', max_length=100)),
                ('premium_type', models.CharField(blank=True, db_index=True, default='', help_text='Observed value: "non-motor".', max_length=100)),
                ('policy_category', models.CharField(blank=True, db_index=True, default='', help_text='Observed value: "Life".', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, default='', max_length=150)),
            ],
            options={
                'verbose_name': 'Premium type mapping',
                'verbose_name_plural': 'Premium type mappings',
                'db_table': 'premium_types_mapping',
                'ordering': ['product'],
                'managed': True,
            },
        ),
        migrations.AddConstraint(
            model_name='premiumtypemapping',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('product'), name='uniq_premium_types_mapping_product'),
        ),
        migrations.AddField(
            model_name='historicalpremiumtypemapping',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
