"""Adopt ``premium_types_mapping`` — it already exists in production.

The first version of this migration was a plain CreateModel and died on the
host with::

    django.db.utils.ProgrammingError: relation "premium_types_mapping"
    already exists

The table is already there, owned by whoever built it. So the model is brought
into Django's state and the DATABASE work is reduced to the difference: create
the table only if it is genuinely absent (a fresh developer database, the test
database), and otherwise add only the columns and indexes that are missing.
Nothing existing is altered, renamed or dropped.

Everything it finds is printed, because the shape of that table is the one
thing this repo could not check for itself.

The historical table is new either way — simple_history owns it — so it is
created normally.
"""
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text
import simple_history.models

TABLE = "premium_types_mapping"

# What the model needs, and the DDL to add it to an existing table. Every
# column is NOT NULL DEFAULT '' so it can be added to a table that already has
# rows — Django's own CharField(blank=True, default="") behaves the same way.
COLUMNS = {
    "product":           "varchar(255) NOT NULL DEFAULT ''",
    "vic_check":         "varchar(100) NOT NULL DEFAULT ''",
    "life_policy_check": "varchar(100) NOT NULL DEFAULT ''",
    "premium_type":      "varchar(100) NOT NULL DEFAULT ''",
    "policy_category":   "varchar(100) NOT NULL DEFAULT ''",
    "updated_at":        "timestamptz NOT NULL DEFAULT now()",
    "updated_by":        "varchar(150) NOT NULL DEFAULT ''",
}

CREATE = f"""
    CREATE TABLE {TABLE} (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        product varchar(255) NOT NULL,
        vic_check varchar(100) NOT NULL DEFAULT '',
        life_policy_check varchar(100) NOT NULL DEFAULT '',
        premium_type varchar(100) NOT NULL DEFAULT '',
        policy_category varchar(100) NOT NULL DEFAULT '',
        updated_at timestamptz NOT NULL DEFAULT now(),
        updated_by varchar(150) NOT NULL DEFAULT ''
    )
"""


def _columns(cur):
    """Columns the table really has, or None when the table is absent.

    pg_attribute via to_regclass rather than information_schema.columns, which
    does not list materialized views — the same call the data-health check uses.
    """
    cur.execute("SELECT to_regclass(%s)", [TABLE])
    if cur.fetchone()[0] is None:
        return None
    cur.execute(
        "SELECT attname FROM pg_attribute "
        "WHERE attrelid = to_regclass(%s) AND attnum > 0 AND NOT attisdropped",
        [TABLE],
    )
    return {r[0].lower() for r in cur.fetchall()}


def adopt(apps, schema_editor):
    cur = schema_editor.connection.cursor()
    found = _columns(cur)

    if found is None:
        print(f"\n  {TABLE}: not present — creating it.")
        cur.execute(CREATE)
        found = set(COLUMNS) | {"id"}
    else:
        print(f"\n  {TABLE}: already exists with columns: "
              f"{', '.join(sorted(found))}")

    # Django's default pk is an implicit `id`. Without one, EVERY query for a
    # model instance selects a column that is not there and the page 500s with
    # a message that names the column but not the cause. Stop here and say so
    # rather than adopting a table the model cannot read — adding an id to a
    # table somebody else's loader writes is not this migration's call to make.
    if "id" not in found:
        raise RuntimeError(
            f'"{TABLE}" has no "id" column, so it cannot back a normal Django '
            f'model. Columns present: {", ".join(sorted(found))}. '
            "Send that list — the model needs to either declare one of these as "
            "its primary key or be read keyless, the way core/warehouse.py "
            "reads the other keyless warehouse tables."
        )

    added = []
    for column, ddl in COLUMNS.items():
        if column not in found:
            cur.execute(f"ALTER TABLE {TABLE} ADD COLUMN IF NOT EXISTS {column} {ddl}")
            added.append(column)
    if added:
        print(f"  {TABLE}: added missing column(s): {', '.join(added)}")
    else:
        print(f"  {TABLE}: every column the model needs is already there.")

    # db_index=True on the model. IF NOT EXISTS so a re-run is a no-op and an
    # index somebody already made by another name is simply left alone.
    for column in ("premium_type", "policy_category"):
        cur.execute(
            f"CREATE INDEX IF NOT EXISTS {TABLE}_{column}_idx "
            f"ON {TABLE} ({column})"
        )


def unadopt(apps, schema_editor):
    """Reverse leaves the table alone.

    It was not created here in the case that matters, and dropping somebody
    else's populated table to undo a model definition is not a trade this
    migration gets to make.
    """
    print(f"\n  {TABLE}: left in place — this migration did not create it.")


def add_constraint(apps, schema_editor):
    """The case-insensitive uniqueness on ``product``.

    Applied last and defensively: the table already holds rows this repo has
    never seen, and if two of them differ only in case the index cannot be
    built. Report the clashes and carry on rather than failing a deploy — the
    serializer still refuses duplicates on the way in, so the only thing missing
    is the backstop against rows that are already there.
    """
    cur = schema_editor.connection.cursor()
    cur.execute(f"""
        SELECT lower(product), count(*), string_agg(DISTINCT product, ' | ')
        FROM {TABLE}
        GROUP BY lower(product)
        HAVING count(*) > 1
    """)
    clashes = cur.fetchall()
    if clashes:
        print(f"\n  {TABLE}: NOT adding the unique index — these products "
              f"already appear more than once:")
        for _, n, spellings in clashes:
            print(f"    {n}x  {spellings}")
        print("  New duplicates are still refused by the API. Merge these rows on "
              "the Insurance Policies screen, then ask for the index in a "
              "follow-up migration.")
        return
    cur.execute(
        f"CREATE UNIQUE INDEX IF NOT EXISTS uniq_premium_types_mapping_product "
        f"ON {TABLE} (lower(product))"
    )


def drop_constraint(apps, schema_editor):
    schema_editor.connection.cursor().execute(
        "DROP INDEX IF EXISTS uniq_premium_types_mapping_product")


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff_management', '0018_fill_dmc_target_properties'),
    ]

    operations = [
        # New table, owned by simple_history — created normally.
        migrations.CreateModel(
            name='HistoricalPremiumTypeMapping',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('product', models.CharField(help_text='Product name as it appears on the policy, e.g. WHOLE LIFE.', max_length=255, verbose_name='Product')),
                ('vic_check', models.CharField(blank=True, default='', help_text='Observed value: "vic".', max_length=100)),
                ('life_policy_check', models.CharField(blank=True, default='', help_text='Observed value: "life".', max_length=100)),
                ('premium_type', models.CharField(blank=True, db_index=True, default='', help_text='Observed value: "non-motor".', max_length=100)),
                ('policy_category', models.CharField(blank=True, db_index=True, default='', help_text='Observed value: "Life".', max_length=100)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_by', models.CharField(blank=True, default='', max_length=150)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Premium type mapping',
                'verbose_name_plural': 'historical Premium type mappings',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),

        # The existing table: Django learns the model, the database gets only
        # the difference.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='PremiumTypeMapping',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('product', models.CharField(help_text='Product name as it appears on the policy, e.g. WHOLE LIFE.', max_length=255, verbose_name='Product')),
                        ('vic_check', models.CharField(blank=True, default='', help_text='Observed value: "vic".', max_length=100)),
                        ('life_policy_check', models.CharField(blank=True, default='', help_text='Observed value: "life".', max_length=100)),
                        ('premium_type', models.CharField(blank=True, db_index=True, default='', help_text='Observed value: "non-motor".', max_length=100)),
                        ('policy_category', models.CharField(blank=True, db_index=True, default='', help_text='Observed value: "Life".', max_length=100)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('updated_by', models.CharField(blank=True, default='', max_length=150)),
                    ],
                    options={
                        'verbose_name': 'Premium type mapping',
                        'verbose_name_plural': 'Premium type mappings',
                        'db_table': 'premium_types_mapping',
                        'ordering': ['product'],
                        'managed': True,
                    },
                ),
            ],
            database_operations=[migrations.RunPython(adopt, unadopt)],
        ),

        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddConstraint(
                    model_name='premiumtypemapping',
                    constraint=models.UniqueConstraint(
                        django.db.models.functions.text.Lower('product'),
                        name='uniq_premium_types_mapping_product'),
                ),
            ],
            database_operations=[migrations.RunPython(add_constraint, drop_constraint)],
        ),

        migrations.AddField(
            model_name='historicalpremiumtypemapping',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
