"""Seed Finance's GL-to-expense-line mapping - for an EMPTY table only.

The 249 rows below are ``Operating_expenses_mapping.xlsx`` as Finance
supplied it on 2026-10-07, transcribed column for column. They are the starting
point for the Operating Expense Mapping tab, so the screen opens with the real
mapping instead of asking somebody to retype 249 GL accounts.

It stops the moment it finds rows already there. If an ETL or an earlier upload
has populated the table, those rows are the live mapping and writing the
spreadsheet over them would be this migration inventing data.

The sheet contains GL 230000023 twice, both rows identical ("Staff costs" /
"Staff Salaries - Net"); it is seeded once. Blank cells - 33 outflow types and
22 GL names - are stored as empty strings, not guesses.
"""
from django.db import migrations

# gl, expense_type, operating_expense, outflow_type, actual_gl_name
ROWS = [
    ("100051000", 'Share register expense',          'Bank Account 5A-Main',                             '',             'Share register expenses'),
    ("144000006", 'Operating Expenses',              'Other Prepayments',                                '',             ''),
    ("145000001", 'Operating Expenses',              'Imprest',                                          '',             ''),
    ("170150001", 'ICT Expense',                     'Software',                                         '',             'IT Maintenance'),
    ("171050001", 'Depreciation and Amortization',   'Acc. Depreciation-Furniture',                      '',             ''),
    ("171080001", 'Depreciation and Amortization',   'Acc. Depreciation-Equipment',                      '',             ''),
    ("171120001", 'Depreciation and Amortization',   'Acc. Depreciation-Computer',                       '',             ''),
    ("230000021", 'Share register expense',          'Acc. Depreciation-Computer',                       '',             'Share register expenses'),
    ("230000023", 'Staff costs',                     'Staff Salaries - Net',                             '',             'Staff costs'),
    ("230000056", 'Operating Expenses',              'Life Insurance Payable',                           '',             ''),
    ("230000064", 'Operating Expenses',              'Life-plus Payable',                                '',             ''),
    ("230000130", 'Staff costs',                     'commissions',                                      '',             'Staff costs'),
    ("230000153", 'Other Receivables',               'Other Receivables',                                '',             ''),
    ("230000180", 'Office Expenses',                 'Lease Liability',                                  '',             ''),
    ("231000005", 'Staff costs',                     'Payroll-Other deductions',                         '',             'Staff costs'),
    ("505040009", 'Gain on Land',                    'Gain on Land',                                     '',             ''),
    ("505060002", 'Operating Expenses',              'Other Losses',                                     '',             ''),
    ("600010001", 'Interest expense',                'Interest Expense- H',                              '',             ''),
    ("600020001", 'Interest expense',                'Interest Expense- C',                              '',             ''),
    ("600110001", 'Interest expense',                'Interest Expense- S',                              '',             ''),
    ("600150001", 'Interest expense',                'Interest Expense-Cro',                             '',             ''),
    ("600200001", 'Interest expense',                'Interest Expense-FCY',                             '',             ''),
    ("601010001", 'Interest expense',                'Interest Expense- FT',                             '',             ''),
    ("601020001", 'Interest expense',                'Interest Expense- Hy',                             '',             ''),
    ("601060001", 'Interest expense',                'Interest Expense-FCY',                             '',             ''),
    ("602010001", 'Interest expense',                'Interest Expense-Loans',                           '',             ''),
    ("602010002", 'Interest expense',                'Interest Expense-Loans',                           '',             ''),
    ("603050003", 'Operating Expenses',              'Excise Duty - Fees',                               '',             ''),
    ("700010001", 'Staff costs',                     'Management - Basic Pay',                           'Controllable', 'Staff costs'),
    ("700010002", 'Staff costs',                     'Salaries',                                         'Controllable', 'Staff costs'),
    ("700010003", 'Staff costs',                     'Salaries',                                         'Controllable', 'Staff costs'),
    ("700010005", 'Staff costs',                     'Management - Other dues',                          'Controllable', 'Staff costs'),
    ("700010006", 'Staff costs',                     'Unionisable - Basic',                              'Controllable', 'Staff costs'),
    ("700010008", 'Staff costs',                     'Salaries',                                         'Controllable', 'Staff costs'),
    ("700010010", 'Staff costs',                     'Salaries',                                         'Controllable', 'Staff costs'),
    ("700010017", 'Staff costs',                     "MD's Other Expenses",                              'Controllable', 'Staff costs'),
    ("700020001", 'Staff costs',                     'Management - Staff Pension',                       'Controllable', 'Staff costs'),
    ("700020002", 'Staff costs',                     'Management - Staff NSSF',                          'Controllable', 'Staff costs'),
    ("700020004", 'Staff costs',                     'Unionisable - Staff',                              'Controllable', 'Staff costs'),
    ("700020005", 'Staff costs',                     'Pension costs',                                    'Controllable', 'Staff costs'),
    ("700030001", 'Staff costs',                     'Management - Staff Medical expenses',              'Controllable', 'Staff costs'),
    ("700030002", 'Staff costs',                     'Medical cost',                                     'Controllable', 'Staff costs'),
    ("700030003", 'Staff costs',                     'Medical cost',                                     'Controllable', 'Staff costs'),
    ("700040001", 'Staff costs',                     'Management - Staff Life cover',                    'Controllable', 'Staff costs'),
    ("700040002", 'Staff costs',                     'Management - Personal',                            'Controllable', 'Staff costs'),
    ("700050001", 'Staff costs',                     'Staff Training - Fee',                             'Controllable', 'Staff costs'),
    ("700050002", 'Staff costs',                     'Staff Training - Inc',                             'Controllable', 'Staff costs'),
    ("700060001", 'Staff costs',                     'Management - Staff R',                             'Controllable', 'Staff costs'),
    ("700070001", 'Staff costs',                     'FBT- Existing Staff',                              'Controllable', 'Staff costs'),
    ("700080001", 'Staff costs',                     'Temporay  staff',                                  'Controllable', 'Staff costs'),
    ("700080002", 'Staff costs',                     'Temporay  staff',                                  'Controllable', 'Staff costs'),
    ("700090001", 'Staff costs',                     'Other Staff Costs',                                'Controllable', 'Staff costs'),
    ("700090002", 'Office Expenses',                 'Utility - Water',                                  'Controllable', 'Office Expenses'),
    ("700090003", 'Office Expenses',                 'Utility - Electricity',                            'Controllable', 'Office Expenses'),
    ("700090004", 'Office Expenses',                 'Telephone',                                        'Controllable', 'Office Expenses'),
    ("700090006", 'Office Expenses',                 'Staff Movements',                                  'Controllable', 'Office Expenses'),
    ("700090007", 'Staff costs',                     'Other staff expenses',                             'Controllable', 'Staff costs'),
    ("700090009", 'Staff costs',                     'Other staff expenses',                             'Controllable', 'Staff costs'),
    ("700090010", 'Staff costs',                     'Other staff expenses',                             'Controllable', 'Staff costs'),
    ("700090011", 'Staff costs',                     'Other staff expenses',                             'Controllable', 'Staff costs'),
    ("700090012", 'Staff costs',                     'Conferences and Seminars',                         'Controllable', 'Staff costs'),
    ("700090013", 'Staff costs',                     'Club and Professional',                            'Controllable', 'Staff costs'),
    ("700090014", 'Staff costs',                     'Other staff expenses',                             'Controllable', 'Staff costs'),
    ("700090016", 'Staff costs',                     'Other staff expenses',                             'Controllable', 'Staff costs'),
    ("701010001", 'Office Expenses',                 'Office Rent',                                      'Installed',    'Occupancy expenses/Office rents and services'),
    ("701010002", 'Office Expenses',                 'Office Rates and Gro',                             'Controllable', 'Office Expenses'),
    ("701010003", 'Office Expenses',                 'Office Security',                                  'Controllable', 'Banking security'),
    ("701010004", 'Office Expenses',                 'Office Electricity',                               'Controllable', 'Office Expenses'),
    ("701010005", 'Office Expenses',                 'Office Water',                                     'Controllable', 'Office Expenses'),
    ("701010006", 'Office Expenses',                 'Office Expenses',                                  'Controllable', 'Office Expenses'),
    ("701010007", 'Office Expenses',                 'Cleaning Charges',                                 'Controllable', 'Other Expenses-cleaning&general'),
    ("701010008", 'Office Expenses',                 'VAT on Leases',                                    'Controllable', 'Office Expenses'),
    ("701010009", 'Office Expenses',                 'Lifts Maintenance',                                'Controllable', 'Office Expenses'),
    ("701010010", 'Office Expenses',                 'Office rents and services',                        'Installed',    'Occupancy expenses/Office rents and services'),
    ("701010012", 'Office Expenses',                 'Generator Fuel and Maintenance',                   'Controllable', 'Office Expenses'),
    ("701010013", 'Office Expenses',                 'Office Cleaning',                                  'Controllable', 'Office Expenses'),
    ("701010015", 'Depreciation and Amortization',   'Lease Depreciation',                               'Installed',    'Lease Depreciation'),
    ("701020003", 'Staff costs',                     'Other staff expenses',                             'Controllable', 'Staff costs'),
    ("701020004", 'Staff costs',                     'Other staff expenses',                             'Controllable', 'Staff costs'),
    ("702010001", 'Office Expenses',                 'Postage Expenses',                                 'Controllable', 'Postage Expenses'),
    ("702010002", 'Office Expenses',                 'Other Postage Expense',                            'Controllable', 'Postage Expenses'),
    ("702020001", 'Office Expenses',                 'Telephone Expenses',                               'Controllable', 'Telecommunication Expenses'),
    ("702020002", 'Office Expenses',                 'Telephone Expenses-M',                             'Controllable', 'Telecommunication Expenses'),
    ("702020003", 'Office Expenses',                 'Other Telecommunication',                          'Controllable', 'Telecommunication Expenses'),
    ("702030001", 'Office Expenses',                 'Printing',                                         'Controllable', 'Printing and stationery'),
    ("702030002", 'Office Expenses',                 'Stationery',                                       'Controllable', 'Printing and stationery'),
    ("702030003", 'ICT Expense',                     'ICT Expense',                                      'Installed',    'IT Maintenance'),
    ("702030004", 'Office Expenses',                 'Security Stationery',                              'Controllable', 'Printing and stationery'),
    ("702040000", 'Deferred Project expenses- CM',   'Deferred Project expenses- CM',                    'Controllable', 'Deferred Project expenses- CM'),
    ("702040001", 'Office Expenses',                 'Miscellaneous Office',                             'Controllable', 'Office Expenses'),
    ("702040002", 'Office Expenses',                 'Kitchen Provisions',                               'Controllable', 'Kitchen Provisions'),
    ("702040003", 'Office Expenses',                 'Staff Meals Allowance',                            'Controllable', 'Staff Meals &Accomodation Allowance'),
    ("702040004", 'Office Expenses',                 'Other Subscriptions',                              'Controllable', 'Subscriptions expenses'),
    ("702040005", 'Office Expenses',                 'Miscellaneous Write',                              'Controllable', 'Office Expenses'),
    ("702040006", 'Office Expenses',                 'General  Expenses',                                'Controllable', 'Other Expenses-cleaning&general'),
    ("702040007", 'Operating Expenses',              'KMALL Expenses',                                   'Controllable', 'KMALL Expenses'),
    ("703010001", 'Depreciation and Amortization',   'Lease Amortization',                               'Installed',    'ROU Depreciation'),
    ("703010002", 'Depreciation and Amortization',   'Land and buildings',                               'Installed',    'Land and buildings'),
    ("703010003", 'Depreciation and Amortization',   'Land and buildings',                               'Installed',    'Land and buildings'),
    ("703020001", 'Depreciation and Amortization',   'Depreciation-Freehold Building',                   'Installed',    'Depreciation Freehold building'),
    ("703020002", 'Depreciation and Amortization',   'Depreciation-Staff Houses',                        'Installed',    'Depreciation Staff house furniture and equipment'),
    ("703020003", 'Depreciation and Amortization',   'Depreciation-Fixtures and Fittings',               'Installed',    'Depreciation Fixtures and fittings'),
    ("703020004", 'Depreciation and Amortization',   'Depreciation-Furniture',                           'Installed',    'Depreciation Office Furniture and Equipment'),
    ("703020006", 'Depreciation and Amortization',   'Depreciation-Fixed Machinery',                     'Installed',    'Depreciation Machinery'),
    ("703020007", 'Depreciation and Amortization',   'Depreciation-Equipment',                           'Installed',    'Depreciation Office Furniture and Equipment'),
    ("703020008", 'Depreciation and Amortization',   'Depreciation-Motor Vehicles',                      'Installed',    'Depreciation Motor Vehicles'),
    ("703020009", 'Depreciation and Amortization',   'Depreciation-Safes',                               'Installed',    'Depreciation Safes'),
    ("703020010", 'Depreciation and Amortization',   'Depreciation-Murals and Desi',                     'Installed',    'Depreciation Murals'),
    ("703020011", 'Depreciation and Amortization',   'Depreciation-Computer and others',                 'Installed',    'Depreciation Computers'),
    ("703020012", 'Depreciation and Amortization',   'Depreciation-Hardware',                            'Installed',    'Depreciation Computers hardware'),
    ("703030001", 'Depreciation and Amortization',   'Depreciation-Software',                            'Installed',    'Depreciation Computer software'),
    ("704010001", 'Operating Expenses',              'Corporate Social Responsibility',                  'Controllable', 'Corporate Social Responsibility'),
    ("704020001", 'Marketing & Product Development', 'Print Advertisement',                              'Controllable', 'Marketing & Product Development'),
    ("704020002", 'Marketing & Product Development', 'Marketing & Product Development',                  'Controllable', 'Marketing & Product Development'),
    ("704020003", 'Marketing & Product Development', 'Bronchures & Leaflets',                            'Controllable', 'Marketing & Product Development'),
    ("704020004", 'Marketing & Product Development', 'Show Expenses/Prom',                               'Controllable', 'Marketing & Product Development'),
    ("704020005", 'Marketing & Product Development', 'Company Rebranding',                               'Controllable', 'Marketing & Product Development'),
    ("704020006", 'Marketing & Product Development', 'Marketing & Product Development',                  'Controllable', 'Marketing & Product Development'),
    ("704020007", 'Marketing & Product Development', 'Marketing & Product Development',                  'Controllable', 'Marketing & Product Development'),
    ("704020008", 'Marketing & Product Development', 'Billboards Costs',                                 'Controllable', 'Marketing & Product Development'),
    ("704020009", 'Marketing & Product Development', 'Websites',                                         'Controllable', 'Marketing & Product Development'),
    ("704020010", 'Marketing & Product Development', 'Property Advertisements HFDI',                     'Controllable', 'Marketing & Product Development'),
    ("704020011", 'Marketing & Product Development', 'Public Relations',                                 'Controllable', 'Marketing & Product Development'),
    ("704020012", 'Marketing & Product Development', 'Other Sales Costs',                                'Controllable', 'Marketing & Product Development'),
    ("704020013", 'Marketing & Product Development', 'Marketing & Product Development',                  'Controllable', 'Marketing & Product Development'),
    ("704030002", 'Marketing & Product Development', 'Marketing & Product Development',                  'Controllable', 'Marketing & Product Development'),
    ("704030003", 'Operating Expenses',              'ATM Implementation',                               'Installed',    'ATM Charges (Kenswitch)'),
    ("704030004", 'Operating Expenses',              'ATM Usage Expenses',                               'Installed',    'ATM Charges (Kenswitch)'),
    ("704030005", 'Operating Expenses',              'Mastercard scheme ex',                             'Installed',    'Mastercard scheme ex'),
    ("705010001", 'Operating Expenses',              "Directors' Fees",                                  'Installed',    'Directors fees and expenses'),
    ("705010002", 'Operating Expenses',              "Directors' Sitting Allowance",                     'Installed',    'Directors fees and expenses'),
    ("705010003", 'Operating Expenses',              "Directors' Expenses",                              'Installed',    'Directors fees and expenses'),
    ("705020001", 'Audit fees and expenses',         'Audit Fees',                                       'Installed',    'Audit fees and expenses'),
    ("705020002", 'Audit fees and expenses',         'Audit fees and expenses',                          'Installed',    'Audit fees and expenses'),
    ("705020003", 'Operating Expenses',              'Other Professional Fees',                          'Controllable', 'Professional fees'),
    ("705030001", 'Rehani house Expenses',           'Rehani House - Electricity',                       'Installed',    'Rehani house Expenses'),
    ("705030002", 'Rehani house Expenses',           'Rehani House - Water',                             'Installed',    'Rehani house Expenses'),
    ("705030003", 'Rehani house Expenses',           'Rehani House - Guard',                             'Installed',    'Rehani house Expenses'),
    ("705030004", 'Rehani house Expenses',           'Rehani House - Repairs',                           'Installed',    'Rehani house Expenses'),
    ("705030005", 'Rehani house Expenses',           'Rehani House - Lift',                              'Installed',    'Rehani house Expenses'),
    ("705030006", 'Rehani house Expenses',           'Rehani House - Generator',                         'Installed',    'Rehani house Expenses'),
    ("705030007", 'Rehani house Expenses',           'Rehani House - Cleaning',                          'Installed',    'Rehani house Expenses'),
    ("705030008", 'Rehani house Expenses',           'Rehani house expenses',                            'Installed',    'Rehani house Expenses'),
    ("705030009", 'Rehani house Expenses',           'Rehani house expenses',                            'Installed',    'Rehani house Expenses'),
    ("705030011", 'Operating Expenses',              'Komarock 5A expenses',                             'Controllable', 'Komarock expenses'),
    ("705030012", 'Operating Expenses',              'Komarock 5B expenses',                             'Controllable', 'Komarock expenses'),
    ("705030013", 'Operating Expenses',              'Komarock 5C expenses',                             'Controllable', 'Komarock expenses'),
    ("705040001", 'Operating Expenses',              'Insurance charges',                                'Installed',    'Insurance charges'),
    ("705040002", 'Operating Expenses',              'Insurance charges',                                'Installed',    'Insurance charges'),
    ("705040003", 'Operating Expenses',              'Insurance charges',                                'Installed',    'Insurance charges'),
    ("705040004", 'Operating Expenses',              'Insurance charges',                                'Installed',    'Insurance charges'),
    ("705040005", 'Operating Expenses',              'All Risks',                                        'Installed',    'Insurance charges'),
    ("705040006", 'Operating Expenses',              'Insurance charges',                                'Installed',    'Insurance charges'),
    ("705040007", 'Operating Expenses',              'Insurance charges',                                'Installed',    'Insurance charges'),
    ("705040008", 'Operating Expenses',              'Insurance charges',                                'Installed',    'Insurance charges'),
    ("705040009", 'Operating Expenses',              'Motor Vehicle Insurance',                          'Installed',    'Insurance charges'),
    ("705040010", 'Operating Expenses',              'Insurance charges',                                'Installed',    'Insurance charges'),
    ("705040011", 'Operating Expenses',              'Insurance charges',                                'Installed',    'Insurance charges'),
    ("705050001", 'Operating Expenses',              'Bank Service Charges',                             'Controllable', 'Bank charges and commissions'),
    ("705050002", 'Operating Expenses',              'Overdraft Charges',                                'Controllable', 'Bank charges and commissions'),
    ("705050003", 'Operating Expenses',              'Uncleared Effects Charge',                         'Installed',    'Uncleared Effects Charge'),
    ("705050004", 'Operating Expenses',              'JV Share of loss',                                 'Installed',    'JV Share of loss'),
    ("705050005", 'Operating Expenses',              'Bank charges and commissions',                     'Controllable', 'Bank charges and commissions'),
    ("705050008", 'Operating Expenses',              'Safaricom charges',                                'Controllable', 'Bank charges and commissions'),
    ("705060003", 'Operating Expenses',              'Sundry Expenses',                                  'Controllable', 'Sundry Expenses'),
    ("705060004", 'Operating Expenses',              'PHL Expenses',                                     'Installed',    'PHL Expenses'),
    ("705070001", 'Legal and professional fees',     'Legal Expenses - Admission',                       'Controllable', 'Legal and professional fees'),
    ("705070002", 'Legal and professional fees',     'Legal and professional fees',                      'Controllable', 'Legal and professional fees'),
    ("705080001", 'Operating Expenses',              'Banking Licences',                                 'Installed',    'Banking licences'),
    ("705080002", 'Operating Expenses',              'Business Permits',                                 'Installed',    'Banking licences'),
    ("705090001", 'Operating Expenses',              'Cash In Transit',                                  'Installed',    'Banking licences'),
    ("705090002", 'Operating Expenses',              'Bank Guards',                                      'Controllable', 'Banking security'),
    ("705100001", 'Operating Expenses',              'Tax Consultancy',                                  'Installed',    'Banking licences'),
    ("705100003", 'ICT Expense',                     'ICT Expense',                                      'Installed',    'IT Maintenance'),
    ("705100004", 'Operating Expenses',              'Other Consultancy Expenses',                       'Installed',    'Banking licences'),
    ("705100005", 'Operating Expenses',              'Consultancy expenses',                             'Installed',    'Banking licences'),
    ("705100006", 'Project Expenses',                'Project Expenses',                                 'Installed',    'Banking licences'),
    ("705110001", 'ICT Expense',                     'Hardware Maintenance',                             'Installed',    'IT Maintenance'),
    ("705110002", 'ICT Expense',                     'ICT Expense',                                      'Installed',    'IT Maintenance'),
    ("705110003", 'ICT Expense',                     'Other Software Licences',                          'Installed',    'IT Maintenance'),
    ("705110004", 'ICT Expense',                     'Data Lines Hire',                                  'Installed',    'IT Maintenance'),
    ("705110005", 'ICT Expense',                     'Other Maintenance Expense',                        'Installed',    'IT Maintenance'),
    ("705110006", 'ICT Expense',                     'ICT Expense',                                      'Installed',    'IT Maintenance'),
    ("705120001", 'Operating Expenses',              'AGM Expenses',                                     'Installed',    'Banking licences'),
    ("705120002", 'Share register expense',          'Share Register Processing',                        'Controllable', 'Share register expenses'),
    ("705120005", 'Operating Expenses',              'Banking licences',                                 'Installed',    'Banking licences'),
    ("705120006", 'Share register expense',          'Other Share Register Expenses',                    'Controllable', 'Share register expenses'),
    ("705130003", 'Operating Expenses',              'Sundry Expenses',                                  'Controllable', 'Sundry Expenses'),
    ("705130004", 'Operating Expenses',              'Sundry Expenses',                                  'Controllable', 'Sundry Expenses'),
    ("705140001", 'Operating Expenses',              'Messengerial Service',                             'Controllable', 'Courier services'),
    ("705140002", 'Operating Expenses',              'Outsourced Services',                              'Controllable', 'Outsourced Services'),
    ("705140003", 'Operating Expenses',              'Cleaning Services',                                'Controllable', 'Other Expenses-cleaning&general'),
    ("705140004", 'Operating Expenses',              'IPPD Payroll Process',                             'Installed',    'Payroll expenses'),
    ("705140005", 'Operating Expenses',              'Other Outsourced Services',                        'Controllable', 'Outsourced Services'),
    ("705150001", 'Operating Expenses',              'Deposit Protection Fund',                          'Installed',    'Deposit protection fund'),
    ("705160001", 'Motor vehicle maintenance',       'Motor vehicle maintenance',                        'Controllable', 'Motor vehicle maintenance& hire'),
    ("705160002", 'Motor vehicle maintenance',       'KBU 901Z',                                         'Controllable', 'Motor vehicle maintenance& hire'),
    ("705160003", 'Motor vehicle maintenance',       'KBU 902Z',                                         'Controllable', 'Motor vehicle maintenance& hire'),
    ("705160004", 'Motor vehicle maintenance',       'KBU 903Z',                                         'Controllable', 'Motor vehicle maintenance& hire'),
    ("705160005", 'Motor vehicle maintenance',       'KBV 041A',                                         'Controllable', 'Motor vehicle maintenance& hire'),
    ("705160006", 'Motor vehicle maintenance',       'KBV 042A',                                         'Controllable', 'Motor vehicle maintenance& hire'),
    ("705160007", 'Motor vehicle maintenance',       'Motor vehicle maintenance',                        'Controllable', 'Motor vehicle maintenance& hire'),
    ("705160008", 'Motor vehicle maintenance',       'KBV 342A',                                         'Controllable', 'Motor vehicle maintenance& hire'),
    ("705160009", 'Motor vehicle maintenance',       'KBV 344A',                                         'Controllable', 'Motor vehicle maintenance& hire'),
    ("705160010", 'Motor vehicle maintenance',       'Motor vehicle maintenance',                        'Controllable', 'Motor vehicle maintenance& hire'),
    ("705160011", 'Motor vehicle maintenance',       'KBV 346A',                                         'Controllable', 'Motor vehicle maintenance& hire'),
    ("705160012", 'Motor vehicle maintenance',       'KBV 585K',                                         'Controllable', 'Motor vehicle maintenance& hire'),
    ("705160013", 'Motor vehicle maintenance',       'KBV 586K',                                         'Controllable', 'Motor vehicle maintenance& hire'),
    ("705160014", 'Motor vehicle maintenance',       'KDR 432S',                                         'Controllable', 'Motor vehicle maintenance& hire'),
    ("705160019", 'Motor vehicle maintenance',       'KDP 648Z',                                         'Controllable', 'Motor vehicle maintenance& hire'),
    ("705160023", 'Motor vehicle maintenance',       'Motor vehicle maintenance',                        'Controllable', 'Motor vehicle maintenance& hire'),
    ("705160025", 'Motor vehicle maintenance',       'Motor vehicle maintenance',                        'Controllable', 'Motor vehicle maintenance& hire'),
    ("705160026", 'Motor vehicle maintenance',       'Motor vehicle maintenance',                        'Controllable', 'Motor vehicle maintenance& hire'),
    ("705160027", 'Motor vehicle maintenance',       'KDL 299E',                                         'Controllable', 'Motor vehicle maintenance& hire'),
    ("705160028", 'Motor vehicle maintenance',       'KDL 424F',                                         'Controllable', 'Motor vehicle maintenance& hire'),
    ("705160029", 'Motor vehicle maintenance',       'Motor vehicle maintenance',                        'Controllable', 'Motor vehicle maintenance& hire'),
    ("705160030", 'Motor vehicle maintenance',       'Motor vehicle maintenance',                        'Controllable', 'Motor vehicle maintenance& hire'),
    ("705170001", 'Operating Expenses',              'Local Travelling Expense',                         'Controllable', 'Motor vehicle hire and travelling'),
    ("705170002", 'Operating Expenses',              'Oveseas Travelling Expense',                       'Controllable', 'Staff costs'),
    ("705170003", 'Operating Expenses',              'Motor Vehicle Hire Charges',                       'Controllable', 'Motor vehicle hire and travelling'),
    ("705190002", 'Loan Loss Provisions',            'Non_operating expense',                            '',             'Loan Loss Provisions'),
    ("705190005", 'IFRS 9 Provisions',               'Other Assets Provisions',                          'Installed',    'Other Assets Provisions'),
    ("705200001", 'Operating Expenses',              'Business Transformation',                          'Controllable', 'Business Transformation Costs'),
    ("705210001", 'Operating Expenses',              'Sundry Expenses',                                  'Controllable', 'Sundry Expenses'),
    ("705220001", 'Operating Expenses',              'Operational Losses',                               'Controllable', 'Operational Losses'),
    ("705220002", 'Operating Expenses',              'Commission expense',                               'Controllable', 'Debt collection fees'),
    ("705230001", 'Office Expenses',                 'Head Office Cost All',                             'Controllable', 'Office Expenses'),
    ("705230004", 'Operating Expenses',              'Gains/loss on loan modification',                  'Controllable', 'Gains/loss on loan modification'),
    ("706000001", 'tax expense',                     'tax expense',                                      'Installed',    'tax expense'),
    ("704030006", 'Visa Card Scheme Fee',            'Visa Card Scheme Fee',                             'Controllable', 'visa card fee'),
    ("700030004", 'Staff costs',                     'Housing Levy',                                     'Controllable', 'Staff costs'),
    ("701010014", 'Non_operating expense',           'Non_operating expense',                            '',             'Non_operating expense'),
    ("700010018", 'Staff costs',                     'Management-Leave Liability',                       'Controllable', 'Management Costs'),
    ("705160031", 'Motor vehicle maintenance',       'KDE 111D',                                         'Controllable', 'Motor vehicle maintenance& hire'),
    ("705190006", 'Non_operating expense',           'Non_operating expense',                            '',             'Non_operating expense'),
    ("705190008", 'Non_operating expense',           'Off \xa0Balance Sheet Provisions',                 '',             'Non_operating expense'),
    ("705160033", 'Motor vehicle maintenance',       'KDP 646Z',                                         'Controllable', 'Motor vehicle maintenance& hire'),
    ("705160032", 'Motor vehicle maintenance',       'KDP 647Z',                                         'Controllable', 'Motor vehicle maintenance& hire'),
    ("705220003", 'Operational Losses',              'CBK Penalties',                                    'Controllable', 'Operational Losses'),
    ("704030008", 'Card Personalization',            'Card Personalization',                             'Controllable', 'Card Personalization'),
    ("704030007", 'Card Personalization',            'ICPS Card Processing',                             'Controllable', 'ICPS Card Processing'),
    ("704030009", 'Coop settlement expense',         'Coop settlement expense',                          'Controllable', 'Coop settlement expense'),
    ("705160021", 'Motor vehicle maintenance',       'KDU 184Q',                                         'Controllable', 'Motor vehicle maintenance& hire'),
    ("705160022", 'Motor vehicle maintenance',       'KDU 183Q',                                         'Controllable', 'Motor vehicle maintenance& hire'),
    ("705160024", 'Motor vehicle maintenance',       'KDU 178Q',                                         'Controllable', 'Motor vehicle maintenance& hire'),
    ("705160015", 'Motor vehicle maintenance',       'KDS 186S',                                         'Controllable', 'Motor vehicle maintenance& hire'),
    ("705100002", 'Operating Expenses',              'Secretarial Services',                             'Controllable', 'Outsourced Services'),
    ("705160016", 'Motor vehicle maintenance',       'KDW 893T',                                         'Controllable', 'Motor vehicle maintenance& hire'),
    ("705040012", 'Operating Expenses',              'Insurance Premium Expense-Treasure&Ultimate Accs', 'Installed',    'Insurance Premium Expense-Treasure&Ultimate Accs'),
]


def load(apps, schema_editor):
    Mapping = apps.get_model("staff_management", "OperatingExpenseMapping")

    existing = Mapping.objects.count()
    if existing:
        print(f"\n  operating_expense_mapping: {existing} row(s) already present - "
              "leaving them alone, not seeding the spreadsheet.")
        return

    Mapping.objects.bulk_create([
        Mapping(gl=gl, expense_type=expense_type, operating_expense=operating_expense,
                outflow_type=outflow_type, actual_gl_name=actual_gl_name,
                updated_by="Finance spreadsheet")
        for gl, expense_type, operating_expense, outflow_type, actual_gl_name in ROWS
    ])
    print(f"\n  operating_expense_mapping: was empty - seeded {len(ROWS)} GL accounts.")


def unload(apps, schema_editor):
    """Remove only the GLs this migration put there, by code. An edited row
    still has its original gl, so a correction Finance made on the screen is
    reversed along with the seed rather than left orphaned."""
    Mapping = apps.get_model("staff_management", "OperatingExpenseMapping")
    Mapping.objects.filter(gl__in=[gl for gl, *_ in ROWS]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("staff_management", "0022_operatingexpensemapping_and_more"),
    ]

    operations = [migrations.RunPython(load, unload)]
