# Generated by Django 4.2.20 on 2026-10-09 06:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff_management', '0023_seed_operating_expense_mapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalScEmployeeKpiTarget',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('sales_code', models.CharField(db_index=True, max_length=255)),
                ('kpi_code', models.CharField(max_length=100)),
                ('year', models.PositiveSmallIntegerField()),
                ('kpi_target', models.FloatField()),
                ('base_value', models.FloatField(blank=True, null=True)),
                ('source', models.CharField(blank=True, default='', max_length=160)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_by', models.CharField(blank=True, default='', max_length=150)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Scorecard Employee KPI Target',
                'verbose_name_plural': 'historical Scorecard Employee KPI Targets',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ScEmployeeKpiTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_code', models.CharField(db_index=True, max_length=255)),
                ('kpi_code', models.CharField(max_length=100)),
                ('year', models.PositiveSmallIntegerField()),
                ('kpi_target', models.FloatField()),
                ('base_value', models.FloatField(blank=True, null=True)),
                ('source', models.CharField(blank=True, default='', max_length=160)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, default='', max_length=150)),
            ],
            options={
                'verbose_name': 'Scorecard Employee KPI Target',
                'verbose_name_plural': 'Scorecard Employee KPI Targets',
                'db_table': 'sc_employee_kpi_targets',
                'indexes': [models.Index(fields=['year', 'kpi_code'], name='sc_employee_year_279f07_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='scemployeekpitarget',
            constraint=models.UniqueConstraint(fields=('sales_code', 'kpi_code', 'year'), name='sc_unique_employee_kpi_target_per_year'),
        ),
        migrations.AddField(
            model_name='historicalscemployeekpitarget',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
