# Generated by Django 4.2.20 on 2026-10-09 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_management', '0024_sc_employee_kpi_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='sckpi',
            name='actuals_block',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Which 18-column repeat within that sheet, 1-based.', null=True),
        ),
        migrations.AddField(
            model_name='sckpi',
            name='actuals_sheet',
            field=models.CharField(blank=True, default='', help_text='Sheet in the actuals workbook, e.g. Banca_Assurance_Income.', max_length=120),
        ),
        migrations.AddField(
            model_name='sckpi',
            name='negate',
            field=models.BooleanField(default=False, help_text='Flip the sign of the value read from the sheet.'),
        ),
        migrations.AddField(
            model_name='sckpi',
            name='not_configured_reason',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
