# Generated by Django 4.2.20 on 2026-10-09 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_management', '0025_sc_kpi_actuals_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='sckpi',
            name='allocation_base_column',
            field=models.CharField(blank=True, default='', help_text='Column holding the card\'s "2025 FY" base, if it has one.', max_length=120),
        ),
        migrations.AddField(
            model_name='sckpi',
            name='allocation_column',
            field=models.CharField(blank=True, default='', help_text='Per-person target column, e.g. "DEPOSITS/Deposit Growth".', max_length=120),
        ),
    ]
