"""Seed the RM scorecards: 12 roles, their KPI lines and their weights.

Taken from ``Portfolio Management - Q3 2026_scorecards.xlsb`` - the eight RM
role cards, read cell by cell - and from the calibration recorded in
``docs/rm-scorecard-kpi-map.csv``, where each line's actuals block was
established by reproducing the ACTUAL the card itself states.

ARMs and BBCs use their segment's RM card, confirmed by the desk, so the twelve
roles on the ``List`` roster map onto eight cards.

Seed-only-if-empty, like 0020 and 0023: if somebody has already configured a
KPI or a mapping this does nothing, because a seed that overwrote a desk's
tuning would be worse than one that never ran.

A KPI whose actuals block could not be established carries
``not_configured_reason`` and is deliberately left inactive. Defaulting it to
block 1 would put Banca premiums 860x out, and a wrong figure on a scorecard is
worse than an absent one.
"""

from datetime import date

from django.db import migrations

YEAR = 2026

ROLES = {
    'commercial_rm': 'COMMERCIAL RM',
    'commercial_rm_trade': 'COMMERCIAL RM- TRADE',
    'diaspora_arm': 'DIASPORA ARM',
    'diaspora_rm': 'DIASPORA RM',
    'mortgage_business_arm': 'Mortgage Business ARM',
    'pb_arm': 'PB ARM',
    'pb_bbc': 'PB BBC',
    'pb_rm': 'PB RM',
    'sme_arm': 'SME ARM',
    'sme_bbc': 'SME BBC',
    'sme_rm': 'SME RM',
    'ultimate_rm': 'Ultimate RM',
}

KPIS = [
    {'kpi_code': 'active_customers', 'kpi_name': 'Active Customers', 'kpi_description': '2 month active(increase by 20%)', 'actuals_sheet': 'Active_Customers', 'actuals_block': 1, 'negate': False, 'allocation_column': 'ACTIVE/2024.0', 'allocation_base_column': '', 'has_base_value': True, 'is_increasing': True, 'not_configured_reason': ''},
    {'kpi_code': 'active_customers_2_months_active', 'kpi_name': 'Active Customers (2 months active)', 'kpi_description': 'Increase by active customers 20%', 'actuals_sheet': 'Active_Customers', 'actuals_block': 1, 'negate': False, 'allocation_column': 'ACTIVE/2024.0', 'allocation_base_column': '', 'has_base_value': True, 'is_increasing': True, 'not_configured_reason': ''},
    {'kpi_code': 'active_customers_two_month', 'kpi_name': 'Active Customers (two Month)', 'kpi_description': 'Increase by active customers 20%', 'actuals_sheet': 'Active_Customers', 'actuals_block': 1, 'negate': False, 'allocation_column': 'ACTIVE/2024.0', 'allocation_base_column': '', 'has_base_value': True, 'is_increasing': True, 'not_configured_reason': ''},
    {'kpi_code': 'asset_growth', 'kpi_name': 'Asset Growth', 'kpi_description': 'Grow by 43% of the Dec book Balance', 'actuals_sheet': 'Asset_Growth', 'actuals_block': 1, 'negate': False, 'allocation_column': 'LOANS/asset_growth', 'allocation_base_column': 'LOANS/Assets', 'has_base_value': True, 'is_increasing': True, 'not_configured_reason': ''},
    {'kpi_code': 'audit', 'kpi_name': 'Audit', 'kpi_description': 'Annual audit score of 1.65', 'actuals_sheet': 'Branch_Audit', 'actuals_block': 1, 'negate': False, 'allocation_column': '', 'allocation_base_column': '', 'has_base_value': False, 'is_increasing': True, 'not_configured_reason': ''},
    {'kpi_code': 'bancassurance_premiums', 'kpi_name': 'Bancassurance Premiums', 'kpi_description': 'Renewals and other banca products as per assigned target', 'actuals_sheet': 'Banca_Assurance_Income', 'actuals_block': None, 'negate': False, 'allocation_column': 'banca_total', 'allocation_base_column': '', 'has_base_value': False, 'is_increasing': True, 'not_configured_reason': 'Which Banca block is life and which is non-life is not established: block 4 is the VIC total and block 5 is other bancassurance, but blocks 2 and 3 could not be told apart because every calibration ca'},
    {'kpi_code': 'banking_covenant_tracking_should_be_in_iapply', 'kpi_name': 'Banking covenant tracking should be in Iapply', 'kpi_description': 'As per assigned Target', 'actuals_sheet': 'covenant_tracking', 'actuals_block': 1, 'negate': False, 'allocation_column': '', 'allocation_base_column': '', 'has_base_value': False, 'is_increasing': True, 'not_configured_reason': ''},
    {'kpi_code': 'business_banking_leave_magement', 'kpi_name': 'Leave magement', 'kpi_description': 'Clear leave days before EOY', 'actuals_sheet': 'Leave_management', 'actuals_block': 1, 'negate': False, 'allocation_column': '', 'allocation_base_column': '', 'has_base_value': False, 'is_increasing': True, 'not_configured_reason': ''},
    {'kpi_code': 'business_banking_par', 'kpi_name': 'PAR', 'kpi_description': 'Per assigned target', 'actuals_sheet': 'PAR', 'actuals_block': 1, 'negate': False, 'allocation_column': '', 'allocation_base_column': '', 'has_base_value': False, 'is_increasing': False, 'not_configured_reason': ''},
    {'kpi_code': 'business_banking_training', 'kpi_name': 'Training', 'kpi_description': 'Training hours for team', 'actuals_sheet': 'training_hours', 'actuals_block': 1, 'negate': False, 'allocation_column': '', 'allocation_base_column': '', 'has_base_value': False, 'is_increasing': True, 'not_configured_reason': ''},
    {'kpi_code': 'business_banking_vic_premiums', 'kpi_name': 'VIC Premiums', 'kpi_description': 'life policies as per assigned target', 'actuals_sheet': 'Banca_Assurance_Income', 'actuals_block': 2, 'negate': False, 'allocation_column': 'banca_life', 'allocation_base_column': '', 'has_base_value': False, 'is_increasing': True, 'not_configured_reason': ''},
    {'kpi_code': 'commercial_trade_group_synergies_23_0', 'kpi_name': 'Group Synergies (23.0%)', 'kpi_description': 'non-life as per assigned Target', 'actuals_sheet': 'Banca_Assurance_Income', 'actuals_block': 3, 'negate': False, 'allocation_column': 'banca_life', 'allocation_base_column': '', 'has_base_value': False, 'is_increasing': True, 'not_configured_reason': ''},
    {'kpi_code': 'commercial_vic_premiums', 'kpi_name': 'VIC Premiums', 'kpi_description': 'All insurance', 'actuals_sheet': 'Banca_Assurance_Income', 'actuals_block': 4, 'negate': False, 'allocation_column': 'banca_total', 'allocation_base_column': '', 'has_base_value': False, 'is_increasing': True, 'not_configured_reason': ''},
    {'kpi_code': 'cross_sell_new_casa_accounts_focus_accounts', 'kpi_name': 'Cross-sell new CASA accounts (focus accounts)', 'kpi_description': 'As per Targets', 'actuals_sheet': 'CASA', 'actuals_block': None, 'negate': False, 'allocation_column': 'CASA', 'allocation_base_column': '', 'has_base_value': False, 'is_increasing': True, 'not_configured_reason': 'Which block of CASA this line reads was not established: every calibration card reads zero for it, so the blocks could not be told apart.'},
    {'kpi_code': 'deposit_growth', 'kpi_name': 'Deposit Growth', 'kpi_description': 'As per assigned target', 'actuals_sheet': 'Deposit_Growth_Retail', 'actuals_block': 1, 'negate': False, 'allocation_column': 'DEPOSITS/Deposit Growth', 'allocation_base_column': 'DEPOSITS/deposit_base', 'has_base_value': True, 'is_increasing': True, 'not_configured_reason': ''},
    {'kpi_code': 'deposit_growth_liab_growth_ntb_liab', 'kpi_name': 'Deposit Growth (Liab Growth + NTB Liab)', 'kpi_description': 'As per Assigned Targets', 'actuals_sheet': 'Deposit_Growth_Retail', 'actuals_block': 1, 'negate': False, 'allocation_column': 'DEPOSITS/Deposit Growth', 'allocation_base_column': 'DEPOSITS/deposit_base', 'has_base_value': True, 'is_increasing': True, 'not_configured_reason': ''},
    {'kpi_code': 'deposits_energy_water', 'kpi_name': 'Deposits(Energy&Water)', 'kpi_description': 'As per assigned Target', 'actuals_sheet': 'sector_deposits', 'actuals_block': 1, 'negate': False, 'allocation_column': '', 'allocation_base_column': '', 'has_base_value': False, 'is_increasing': True, 'not_configured_reason': ''},
    {'kpi_code': 'deposits_portfolio', 'kpi_name': 'Deposits(Portfolio)', 'kpi_description': 'As per assigned Target', 'actuals_sheet': 'Deposit_Growth_Retail', 'actuals_block': 1, 'negate': False, 'allocation_column': 'DEPOSITS/Deposit Growth', 'allocation_base_column': 'DEPOSITS/deposit_base', 'has_base_value': True, 'is_increasing': True, 'not_configured_reason': ''},
    {'kpi_code': 'deposits_portfolio_ntb', 'kpi_name': 'Deposits (Portfolio + NTB)', 'kpi_description': 'As per Targets', 'actuals_sheet': 'Deposit_Growth_Retail', 'actuals_block': 1, 'negate': False, 'allocation_column': 'DEPOSITS/Deposit Growth', 'allocation_base_column': 'DEPOSITS/deposit_base', 'has_base_value': True, 'is_increasing': True, 'not_configured_reason': ''},
    {'kpi_code': 'diaspora_net_disbursements', 'kpi_name': 'Net Disbursements', 'kpi_description': 'As per Targets', 'actuals_sheet': 'Asset_Drawdown', 'actuals_block': 1, 'negate': False, 'allocation_column': 'Disbursment/Total', 'allocation_base_column': '', 'has_base_value': False, 'is_increasing': True, 'not_configured_reason': ''},
    {'kpi_code': 'digital_adoption', 'kpi_name': 'Digital Adoption', 'kpi_description': 'Increase portfolio by 50%', 'actuals_sheet': 'Digital_adoption', 'actuals_block': 1, 'negate': False, 'allocation_column': 'DIGITAL_ADOPTION', 'allocation_base_column': '', 'has_base_value': True, 'is_increasing': True, 'not_configured_reason': ''},
    {'kpi_code': 'direct_portfolio_contribution', 'kpi_name': 'Direct Portfolio Contribution', 'kpi_description': '(GII-IE+NFI)', 'actuals_sheet': 'Revenue_Contribution', 'actuals_block': 2, 'negate': False, 'allocation_column': 'TOTAL INCOME CONTRIBUTION/Growth', 'allocation_base_column': 'TOTAL INCOME CONTRIBUTION/2024 (Income+(FTP-LoanLoss))', 'has_base_value': True, 'is_increasing': True, 'not_configured_reason': ''},
    {'kpi_code': 'drawdowns', 'kpi_name': 'Drawdowns', 'kpi_description': 'As per Assigned Targets', 'actuals_sheet': 'Asset_Drawdown', 'actuals_block': None, 'negate': False, 'allocation_column': 'Disbursment/Total', 'allocation_base_column': '', 'has_base_value': False, 'is_increasing': True, 'not_configured_reason': 'Which block of Asset_Drawdown this line reads was not established: every calibration card reads zero for it, so the blocks could not be told apart.'},
    {'kpi_code': 'errors', 'kpi_name': 'Errors', 'kpi_description': 'Mortgage application errors', 'actuals_sheet': 'Loan_Application_Errors', 'actuals_block': None, 'negate': False, 'allocation_column': '', 'allocation_base_column': '', 'has_base_value': False, 'is_increasing': False, 'not_configured_reason': 'Which block of Loan_Application_Errors this line reads was not established: every calibration card reads zero for it, so the blocks could not be told apart.'},
    {'kpi_code': 'group_synergies_20_0', 'kpi_name': 'Group Synergies (20.0%)', 'kpi_description': 'non-life as per assigned Target', 'actuals_sheet': 'Banca_Assurance_Income', 'actuals_block': 3, 'negate': False, 'allocation_column': 'banca_life', 'allocation_base_column': '', 'has_base_value': False, 'is_increasing': True, 'not_configured_reason': ''},
    {'kpi_code': 'group_synergies_25_0', 'kpi_name': 'Group Synergies (25.0%)', 'kpi_description': 'non-life as per assigned Target', 'actuals_sheet': 'Banca_Assurance_Income', 'actuals_block': None, 'negate': False, 'allocation_column': 'banca_life', 'allocation_base_column': '', 'has_base_value': False, 'is_increasing': True, 'not_configured_reason': 'Which Banca block is life and which is non-life is not established: block 4 is the VIC total and block 5 is other bancassurance, but blocks 2 and 3 could not be told apart because every calibration ca'},
    {'kpi_code': 'grow_deposits', 'kpi_name': 'Grow Deposits', 'kpi_description': 'As per assigned Target', 'actuals_sheet': 'Deposit_Growth_Retail', 'actuals_block': 1, 'negate': False, 'allocation_column': 'DEPOSITS/Deposit Growth', 'allocation_base_column': 'DEPOSITS/deposit_base', 'has_base_value': True, 'is_increasing': True, 'not_configured_reason': ''},
    {'kpi_code': 'income_contribution', 'kpi_name': 'Income Contribution', 'kpi_description': '(GII-IE+NFI(+/-)FTP-Loan Loss)', 'actuals_sheet': 'Revenue_Contribution', 'actuals_block': 1, 'negate': False, 'allocation_column': 'TOTAL INCOME CONTRIBUTION/Growth', 'allocation_base_column': 'TOTAL INCOME CONTRIBUTION/2024 (Income+(FTP-LoanLoss))', 'has_base_value': True, 'is_increasing': True, 'not_configured_reason': ''},
    {'kpi_code': 'income_contribution_portfolio_ntb', 'kpi_name': 'Income Contribution (Portfolio + NTB)', 'kpi_description': '(GII-IE+NFI(+/-)FTP-Loan Loss)', 'actuals_sheet': 'Revenue_Contribution', 'actuals_block': 1, 'negate': False, 'allocation_column': 'TOTAL INCOME CONTRIBUTION/Growth', 'allocation_base_column': 'TOTAL INCOME CONTRIBUTION/2024 (Income+(FTP-LoanLoss))', 'has_base_value': True, 'is_increasing': True, 'not_configured_reason': ''},
    {'kpi_code': 'loan_loss', 'kpi_name': 'Loan Loss', 'kpi_description': 'As per assigned Target', 'actuals_sheet': 'PL_Charge', 'actuals_block': 1, 'negate': True, 'allocation_column': 'LOAN LOSS/Growth', 'allocation_base_column': 'LOAN LOSS/2025.0', 'has_base_value': True, 'is_increasing': False, 'not_configured_reason': ''},
    {'kpi_code': 'mortgage_business_par', 'kpi_name': 'PAR', 'kpi_description': 'Per assigned target', 'actuals_sheet': 'PAR', 'actuals_block': None, 'negate': False, 'allocation_column': '', 'allocation_base_column': '', 'has_base_value': False, 'is_increasing': False, 'not_configured_reason': 'Which block of PAR this line reads was not established: every calibration card reads zero for it, so the blocks could not be told apart.'},
    {'kpi_code': 'net_asset_disbursements', 'kpi_name': 'Net Asset Disbursements', 'kpi_description': 'As per assigned target', 'actuals_sheet': 'Asset_Drawdown', 'actuals_block': 1, 'negate': False, 'allocation_column': 'Disbursment/Total', 'allocation_base_column': '', 'has_base_value': False, 'is_increasing': True, 'not_configured_reason': ''},
    {'kpi_code': 'net_loan_disbursments', 'kpi_name': 'Net Loan Disbursments', 'kpi_description': 'As per assigned Target', 'actuals_sheet': 'Asset_Drawdown', 'actuals_block': 1, 'negate': False, 'allocation_column': 'Disbursment/Total', 'allocation_base_column': '', 'has_base_value': False, 'is_increasing': True, 'not_configured_reason': ''},
    {'kpi_code': 'net_mortgage_sales_10_commercial_rate_mortgages', 'kpi_name': 'Net Mortgage sales (10% commercial rate mortgages)', 'kpi_description': 'As per Targets', 'actuals_sheet': 'Asset_Drawdown', 'actuals_block': None, 'negate': False, 'allocation_column': 'Disbursment/Total', 'allocation_base_column': '', 'has_base_value': False, 'is_increasing': True, 'not_configured_reason': 'Which block of Asset_Drawdown this line reads was not established: every calibration card reads zero for it, so the blocks could not be told apart.'},
    {'kpi_code': 'net_mortgage_sales_10_non_commercial_rate_mortgages', 'kpi_name': 'Net Mortgage sales (10% non-commercial rate mortgages)', 'kpi_description': 'As per Targets', 'actuals_sheet': 'Asset_Drawdown', 'actuals_block': None, 'negate': False, 'allocation_column': 'Disbursment/Total', 'allocation_base_column': '', 'has_base_value': False, 'is_increasing': True, 'not_configured_reason': 'Which block of Asset_Drawdown this line reads was not established: every calibration card reads zero for it, so the blocks could not be told apart.'},
    {'kpi_code': 'new_business_banking_customers', 'kpi_name': 'New Business Banking Customers', 'kpi_description': 'As per assigned target', 'actuals_sheet': 'New_Customers', 'actuals_block': 1, 'negate': False, 'allocation_column': 'New_Cust', 'allocation_base_column': '', 'has_base_value': False, 'is_increasing': True, 'not_configured_reason': ''},
    {'kpi_code': 'new_customer_min_turnover_of_10m', 'kpi_name': 'New Customer (Min Turnover of 10M)', 'kpi_description': 'As per assigned Target', 'actuals_sheet': 'New_Customers', 'actuals_block': 1, 'negate': False, 'allocation_column': 'New_Cust', 'allocation_base_column': '', 'has_base_value': False, 'is_increasing': True, 'not_configured_reason': ''},
    {'kpi_code': 'new_customer_min_turnover_of_50m', 'kpi_name': 'New Customer (Min Turnover of 50M)', 'kpi_description': 'As per assigned Target', 'actuals_sheet': 'New_Customers', 'actuals_block': 1, 'negate': False, 'allocation_column': 'New_Cust', 'allocation_base_column': '', 'has_base_value': False, 'is_increasing': True, 'not_configured_reason': ''},
    {'kpi_code': 'nps', 'kpi_name': 'NPS', 'kpi_description': 'Achieve 60% and above', 'actuals_sheet': 'NPS', 'actuals_block': 1, 'negate': False, 'allocation_column': '', 'allocation_base_column': '', 'has_base_value': False, 'is_increasing': True, 'not_configured_reason': ''},
    {'kpi_code': 'number_of_property', 'kpi_name': 'Number of Property', 'kpi_description': 'Achieve property sales as per assigned targets', 'actuals_sheet': 'Plot_Sales_Volume', 'actuals_block': None, 'negate': False, 'allocation_column': 'Plot_Sales', 'allocation_base_column': '', 'has_base_value': False, 'is_increasing': True, 'not_configured_reason': 'Which block of Plot_Sales_Volume this line reads was not established: every calibration card reads zero for it, so the blocks could not be told apart.'},
    {'kpi_code': 'operating_profit', 'kpi_name': 'Operating Profit', 'kpi_description': '(GII-IE+NFI(+/-)FTP-Loan Loss) Growth on Growth', 'actuals_sheet': 'Revenue_Contribution', 'actuals_block': 1, 'negate': False, 'allocation_column': 'TOTAL INCOME CONTRIBUTION/Growth', 'allocation_base_column': 'TOTAL INCOME CONTRIBUTION/2024 (Income+(FTP-LoanLoss))', 'has_base_value': True, 'is_increasing': True, 'not_configured_reason': ''},
    {'kpi_code': 'other_bancassurance_premiums', 'kpi_name': 'Other Bancassurance Premiums', 'kpi_description': 'Renewals and other banca products as per assigned target', 'actuals_sheet': 'Banca_Assurance_Income', 'actuals_block': 5, 'negate': False, 'allocation_column': 'banca_total', 'allocation_base_column': '', 'has_base_value': False, 'is_increasing': True, 'not_configured_reason': ''},
    {'kpi_code': 'personal_banking_group_synergies_23_0', 'kpi_name': 'Group Synergies (23.0%)', 'kpi_description': 'non-life as per assigned Target', 'actuals_sheet': 'Banca_Assurance_Income', 'actuals_block': None, 'negate': False, 'allocation_column': 'banca_life', 'allocation_base_column': '', 'has_base_value': False, 'is_increasing': True, 'not_configured_reason': 'Which Banca block is life and which is non-life is not established: block 4 is the VIC total and block 5 is other bancassurance, but blocks 2 and 3 could not be told apart because every calibration ca'},
    {'kpi_code': 'personal_banking_leave_magement', 'kpi_name': 'Leave magement', 'kpi_description': 'Clear leave days before EOY', 'actuals_sheet': 'Leave_management', 'actuals_block': None, 'negate': False, 'allocation_column': '', 'allocation_base_column': '', 'has_base_value': False, 'is_increasing': True, 'not_configured_reason': 'Which block of Leave_management this line reads was not established: every calibration card reads zero for it, so the blocks could not be told apart.'},
    {'kpi_code': 'personal_banking_new_customers', 'kpi_name': 'New Customers', 'kpi_description': 'As per Assigned Targets', 'actuals_sheet': 'New_Customers', 'actuals_block': 1, 'negate': False, 'allocation_column': 'New_Cust', 'allocation_base_column': '', 'has_base_value': False, 'is_increasing': True, 'not_configured_reason': ''},
    {'kpi_code': 'personal_banking_training', 'kpi_name': 'Training', 'kpi_description': 'As per Assigned Targets', 'actuals_sheet': 'training_hours', 'actuals_block': None, 'negate': False, 'allocation_column': '', 'allocation_base_column': '', 'has_base_value': False, 'is_increasing': True, 'not_configured_reason': 'Which block of training_hours this line reads was not established: every calibration card reads zero for it, so the blocks could not be told apart.'},
    {'kpi_code': 'personal_banking_vic_premiums', 'kpi_name': 'VIC Premiums', 'kpi_description': 'life policies as per assigned target', 'actuals_sheet': 'Banca_Assurance_Income', 'actuals_block': None, 'negate': False, 'allocation_column': 'banca_life', 'allocation_base_column': '', 'has_base_value': False, 'is_increasing': True, 'not_configured_reason': 'Which Banca block is life and which is non-life is not established: block 4 is the VIC total and block 5 is other bancassurance, but blocks 2 and 3 could not be told apart because every calibration ca'},
    {'kpi_code': 'portfolio_coverage_engagement', 'kpi_name': 'Portfolio Coverage (engagement)', 'kpi_description': 'Achieve 80% and above', 'actuals_sheet': 'Contactability', 'actuals_block': 1, 'negate': False, 'allocation_column': '', 'allocation_base_column': '', 'has_base_value': False, 'is_increasing': True, 'not_configured_reason': ''},
    {'kpi_code': 'portfolio_management_aum_dec_previous_year', 'kpi_name': 'Portfolio Management AUM (Dec previous year)', 'kpi_description': 'Grow by 100%', 'actuals_sheet': 'Portfolio_AUM', 'actuals_block': 1, 'negate': False, 'allocation_column': 'AUM/AUMGrowth', 'allocation_base_column': 'AUM/Starting AUM', 'has_base_value': True, 'is_increasing': True, 'not_configured_reason': ''},
    {'kpi_code': 'portfolio_nps', 'kpi_name': 'Portfolio NPS', 'kpi_description': 'Achieve 60% and above', 'actuals_sheet': 'NPS', 'actuals_block': 1, 'negate': False, 'allocation_column': '', 'allocation_base_column': '', 'has_base_value': False, 'is_increasing': True, 'not_configured_reason': ''},
    {'kpi_code': 'portfolo_nps', 'kpi_name': 'Portfolo NPS', 'kpi_description': 'Achieve 60% and above', 'actuals_sheet': 'NPS', 'actuals_block': 1, 'negate': False, 'allocation_column': '', 'allocation_base_column': '', 'has_base_value': False, 'is_increasing': True, 'not_configured_reason': ''},
    {'kpi_code': 'reduce_p_l_provisions_nil_provisions_loan_loss', 'kpi_name': 'Reduce P&L provisions / Nil provisions (Loan Loss)', 'kpi_description': 'By Assigned Amount', 'actuals_sheet': 'PL_Charge', 'actuals_block': 1, 'negate': True, 'allocation_column': 'LOAN LOSS/Growth', 'allocation_base_column': 'LOAN LOSS/2025.0', 'has_base_value': True, 'is_increasing': False, 'not_configured_reason': ''},
    {'kpi_code': 'reduce_p_l_provisions_nill_provisions_loan_loss', 'kpi_name': 'Reduce P&L provisions / Nill provisions (Loan Loss)', 'kpi_description': 'By Assigned Amount', 'actuals_sheet': 'PL_Charge', 'actuals_block': 1, 'negate': True, 'allocation_column': 'LOAN LOSS/Growth', 'allocation_base_column': 'LOAN LOSS/2025.0', 'has_base_value': True, 'is_increasing': False, 'not_configured_reason': ''},
    {'kpi_code': 'tat_loan', 'kpi_name': 'TAT (Loan)', 'kpi_description': '< 7 Days (Binary 90%)', 'actuals_sheet': 'TAT_Loans', 'actuals_block': None, 'negate': False, 'allocation_column': '', 'allocation_base_column': '', 'has_base_value': False, 'is_increasing': True, 'not_configured_reason': 'Which block of TAT_Loans this line reads was not established: every calibration card reads zero for it, so the blocks could not be told apart.'},
    {'kpi_code': 'tooling_and_account_planning_all_customers', 'kpi_name': 'Tooling and account planning all customers', 'kpi_description': 'As per assigned Target', 'actuals_sheet': 'tooling_n_account_planning', 'actuals_block': 1, 'negate': False, 'allocation_column': '', 'allocation_base_column': '', 'has_base_value': False, 'is_increasing': True, 'not_configured_reason': ''},
    {'kpi_code': 'trade_finance_volume', 'kpi_name': 'Trade Finance Volume', 'kpi_description': 'As per assigned target', 'actuals_sheet': 'Trade_Finance_income', 'actuals_block': None, 'negate': False, 'allocation_column': 'Trade income/Total', 'allocation_base_column': '', 'has_base_value': False, 'is_increasing': True, 'not_configured_reason': 'Which block of Trade_Finance_income this line reads was not established: every calibration card reads zero for it, so the blocks could not be told apart.'},
    {'kpi_code': 'trade_income', 'kpi_name': 'Trade Income', 'kpi_description': 'As per assigned Target', 'actuals_sheet': 'Trade_Finance_Income', 'actuals_block': 1, 'negate': False, 'allocation_column': 'Trade income/Total', 'allocation_base_column': '', 'has_base_value': False, 'is_increasing': True, 'not_configured_reason': ''},
    {'kpi_code': 'trade_volume', 'kpi_name': 'Trade Volume', 'kpi_description': 'As per assigned Target', 'actuals_sheet': 'Trade_Finance_Income', 'actuals_block': 2, 'negate': False, 'allocation_column': 'Trade income/Total', 'allocation_base_column': '', 'has_base_value': False, 'is_increasing': True, 'not_configured_reason': ''},
    {'kpi_code': 'ultimate_rm_net_disbursements', 'kpi_name': 'Net Disbursements', 'kpi_description': 'As per Targets', 'actuals_sheet': 'Asset_Drawdown', 'actuals_block': None, 'negate': False, 'allocation_column': 'Disbursment/Total', 'allocation_base_column': '', 'has_base_value': False, 'is_increasing': True, 'not_configured_reason': 'Which block of Asset_Drawdown this line reads was not established: every calibration card reads zero for it, so the blocks could not be told apart.'},
    {'kpi_code': 'ultimate_rm_new_customers', 'kpi_name': 'New customers', 'kpi_description': '> 2 Active Products', 'actuals_sheet': 'New_Customers', 'actuals_block': None, 'negate': False, 'allocation_column': 'New_Cust', 'allocation_base_column': '', 'has_base_value': False, 'is_increasing': True, 'not_configured_reason': 'Which block of New_Customers this line reads was not established: every calibration card reads zero for it, so the blocks could not be told apart.'},
    {'kpi_code': 'value_of_property_sales', 'kpi_name': 'Value of Property Sales', 'kpi_description': 'Achieve property sales as per assigned targets', 'actuals_sheet': 'Plot_Sales_Value', 'actuals_block': None, 'negate': False, 'allocation_column': 'PLOT_SALES_VALUE', 'allocation_base_column': '', 'has_base_value': False, 'is_increasing': True, 'not_configured_reason': 'Which block of Plot_Sales_Value this line reads was not established: every calibration card reads zero for it, so the blocks could not be told apart.'},
    {'kpi_code': 'vic_premium', 'kpi_name': 'VIC Premium', 'kpi_description': 'life policies as per assigned target', 'actuals_sheet': 'Banca_Assurance_Income', 'actuals_block': None, 'negate': False, 'allocation_column': 'banca_life', 'allocation_base_column': '', 'has_base_value': False, 'is_increasing': True, 'not_configured_reason': 'Which Banca block is life and which is non-life is not established: block 4 is the VIC total and block 5 is other bancassurance, but blocks 2 and 3 could not be told apart because every calibration ca'},
    {'kpi_code': 'weighted_sales', 'kpi_name': 'Weighted Sales', 'kpi_description': 'As per assigned 80% target', 'actuals_sheet': 'Weighted_Sales', 'actuals_block': 1, 'negate': False, 'allocation_column': '', 'allocation_base_column': '', 'has_base_value': False, 'is_increasing': True, 'not_configured_reason': ''},
    {'kpi_code': 'weighted_sales_dashboard', 'kpi_name': 'Weighted Sales Dashboard', 'kpi_description': 'As per Targets', 'actuals_sheet': 'Weighted_Sales', 'actuals_block': 1, 'negate': False, 'allocation_column': '', 'allocation_base_column': '', 'has_base_value': False, 'is_increasing': True, 'not_configured_reason': ''},
    {'kpi_code': 'weigted_tat', 'kpi_name': 'Weigted TAT', 'kpi_description': 'Per assigned target', 'actuals_sheet': 'Weighted_TAT', 'actuals_block': 1, 'negate': False, 'allocation_column': '', 'allocation_base_column': '', 'has_base_value': False, 'is_increasing': True, 'not_configured_reason': ''},
    {'kpi_code': 'weigted_tat_sla_service_standards_query_response_time', 'kpi_name': 'Weigted TAT(SLA,Service standards, query response time)', 'kpi_description': 'Per assigned target', 'actuals_sheet': 'Weighted_TAT', 'actuals_block': 1, 'negate': False, 'allocation_column': '', 'allocation_base_column': '', 'has_base_value': False, 'is_increasing': True, 'not_configured_reason': ''},
]

MAPPINGS = [
    {'role_code': 'sme_rm', 'role_name': 'SME RM', 'kpi_order': 1, 'kpi_code': 'new_business_banking_customers', 'mapping_category': 'Weighted sales (35.0%)', 'kpi_weight': 0.075, 'kpi_target': 24.0, 'is_bonus': False},
    {'role_code': 'sme_rm', 'role_name': 'SME RM', 'kpi_order': 2, 'kpi_code': 'net_asset_disbursements', 'mapping_category': 'Weighted sales (35.0%)', 'kpi_weight': 0.1, 'kpi_target': 270000000.0, 'is_bonus': False},
    {'role_code': 'sme_rm', 'role_name': 'SME RM', 'kpi_order': 3, 'kpi_code': 'asset_growth', 'mapping_category': 'Weighted sales (35.0%)', 'kpi_weight': 0.05, 'kpi_target': 14729931.788000003, 'is_bonus': False},
    {'role_code': 'sme_rm', 'role_name': 'SME RM', 'kpi_order': 4, 'kpi_code': 'weighted_sales', 'mapping_category': 'Weighted sales (35.0%)', 'kpi_weight': 0.05, 'kpi_target': None, 'is_bonus': False},
    {'role_code': 'sme_rm', 'role_name': 'SME RM', 'kpi_order': 5, 'kpi_code': 'trade_finance_volume', 'mapping_category': 'Weighted sales (35.0%)', 'kpi_weight': 0.075, 'kpi_target': 180000000.0, 'is_bonus': False},
    {'role_code': 'sme_rm', 'role_name': 'SME RM', 'kpi_order': 6, 'kpi_code': 'number_of_property', 'mapping_category': 'Group Synergies (20.0%)', 'kpi_weight': 0.05, 'kpi_target': 2.0, 'is_bonus': False},
    {'role_code': 'sme_rm', 'role_name': 'SME RM', 'kpi_order': 7, 'kpi_code': 'value_of_property_sales', 'mapping_category': 'Group Synergies (20.0%)', 'kpi_weight': 0.05, 'kpi_target': 16400000.0, 'is_bonus': False},
    {'role_code': 'sme_rm', 'role_name': 'SME RM', 'kpi_order': 8, 'kpi_code': 'business_banking_vic_premiums', 'mapping_category': 'Group Synergies (20.0%)', 'kpi_weight': 0.03, 'kpi_target': 1155627.12890625, 'is_bonus': False},
    {'role_code': 'sme_rm', 'role_name': 'SME RM', 'kpi_order': 9, 'kpi_code': 'group_synergies_20_0', 'mapping_category': 'Group Synergies (20.0%)', 'kpi_weight': 0.03, 'kpi_target': 1155576.0, 'is_bonus': False},
    {'role_code': 'sme_rm', 'role_name': 'SME RM', 'kpi_order': 10, 'kpi_code': 'bancassurance_premiums', 'mapping_category': 'Group Synergies (20.0%)', 'kpi_weight': 0.04, 'kpi_target': 1155576.0, 'is_bonus': False},
    {'role_code': 'sme_rm', 'role_name': 'SME RM', 'kpi_order': 11, 'kpi_code': 'portfolio_nps', 'mapping_category': 'Portfolio Management (35.0%)', 'kpi_weight': 0.05, 'kpi_target': 0.6, 'is_bonus': False},
    {'role_code': 'sme_rm', 'role_name': 'SME RM', 'kpi_order': 12, 'kpi_code': 'active_customers_2_months_active', 'mapping_category': 'Portfolio Management (35.0%)', 'kpi_weight': 0.1, 'kpi_target': 72.0, 'is_bonus': False},
    {'role_code': 'sme_rm', 'role_name': 'SME RM', 'kpi_order': 13, 'kpi_code': 'operating_profit', 'mapping_category': 'Portfolio Management (35.0%)', 'kpi_weight': 0.1, 'kpi_target': 6245102.206767494, 'is_bonus': False},
    {'role_code': 'sme_rm', 'role_name': 'SME RM', 'kpi_order': 14, 'kpi_code': 'deposit_growth', 'mapping_category': 'Portfolio Management (35.0%)', 'kpi_weight': 0.1, 'kpi_target': 72552526.28, 'is_bonus': False},
    {'role_code': 'sme_rm', 'role_name': 'SME RM', 'kpi_order': 15, 'kpi_code': 'weigted_tat', 'mapping_category': 'Service Excellence (5.0%)', 'kpi_weight': 0.05, 'kpi_target': 1.0, 'is_bonus': False},
    {'role_code': 'sme_rm', 'role_name': 'SME RM', 'kpi_order': 16, 'kpi_code': 'business_banking_training', 'mapping_category': 'Staff Engagement (5.0%)', 'kpi_weight': 0.025, 'kpi_target': 48.0, 'is_bonus': False},
    {'role_code': 'sme_rm', 'role_name': 'SME RM', 'kpi_order': 17, 'kpi_code': 'business_banking_leave_magement', 'mapping_category': 'Staff Engagement (5.0%)', 'kpi_weight': 0.025, 'kpi_target': 1.0, 'is_bonus': False},
    {'role_code': 'sme_rm', 'role_name': 'SME RM', 'kpi_order': 18, 'kpi_code': 'business_banking_par', 'mapping_category': 'Bonus Points (2.5%)', 'kpi_weight': 0.025, 'kpi_target': 0.025, 'is_bonus': True},
    {'role_code': 'sme_arm', 'role_name': 'SME ARM', 'kpi_order': 1, 'kpi_code': 'new_business_banking_customers', 'mapping_category': 'Weighted sales (35.0%)', 'kpi_weight': 0.075, 'kpi_target': 24.0, 'is_bonus': False},
    {'role_code': 'sme_arm', 'role_name': 'SME ARM', 'kpi_order': 2, 'kpi_code': 'net_asset_disbursements', 'mapping_category': 'Weighted sales (35.0%)', 'kpi_weight': 0.1, 'kpi_target': 270000000.0, 'is_bonus': False},
    {'role_code': 'sme_arm', 'role_name': 'SME ARM', 'kpi_order': 3, 'kpi_code': 'asset_growth', 'mapping_category': 'Weighted sales (35.0%)', 'kpi_weight': 0.05, 'kpi_target': 14729931.788000003, 'is_bonus': False},
    {'role_code': 'sme_arm', 'role_name': 'SME ARM', 'kpi_order': 4, 'kpi_code': 'weighted_sales', 'mapping_category': 'Weighted sales (35.0%)', 'kpi_weight': 0.05, 'kpi_target': None, 'is_bonus': False},
    {'role_code': 'sme_arm', 'role_name': 'SME ARM', 'kpi_order': 5, 'kpi_code': 'trade_finance_volume', 'mapping_category': 'Weighted sales (35.0%)', 'kpi_weight': 0.075, 'kpi_target': 180000000.0, 'is_bonus': False},
    {'role_code': 'sme_arm', 'role_name': 'SME ARM', 'kpi_order': 6, 'kpi_code': 'number_of_property', 'mapping_category': 'Group Synergies (20.0%)', 'kpi_weight': 0.05, 'kpi_target': 2.0, 'is_bonus': False},
    {'role_code': 'sme_arm', 'role_name': 'SME ARM', 'kpi_order': 7, 'kpi_code': 'value_of_property_sales', 'mapping_category': 'Group Synergies (20.0%)', 'kpi_weight': 0.05, 'kpi_target': 16400000.0, 'is_bonus': False},
    {'role_code': 'sme_arm', 'role_name': 'SME ARM', 'kpi_order': 8, 'kpi_code': 'business_banking_vic_premiums', 'mapping_category': 'Group Synergies (20.0%)', 'kpi_weight': 0.03, 'kpi_target': 1155627.12890625, 'is_bonus': False},
    {'role_code': 'sme_arm', 'role_name': 'SME ARM', 'kpi_order': 9, 'kpi_code': 'group_synergies_20_0', 'mapping_category': 'Group Synergies (20.0%)', 'kpi_weight': 0.03, 'kpi_target': 1155576.0, 'is_bonus': False},
    {'role_code': 'sme_arm', 'role_name': 'SME ARM', 'kpi_order': 10, 'kpi_code': 'bancassurance_premiums', 'mapping_category': 'Group Synergies (20.0%)', 'kpi_weight': 0.04, 'kpi_target': 1155576.0, 'is_bonus': False},
    {'role_code': 'sme_arm', 'role_name': 'SME ARM', 'kpi_order': 11, 'kpi_code': 'portfolio_nps', 'mapping_category': 'Portfolio Management (35.0%)', 'kpi_weight': 0.05, 'kpi_target': 0.6, 'is_bonus': False},
    {'role_code': 'sme_arm', 'role_name': 'SME ARM', 'kpi_order': 12, 'kpi_code': 'active_customers_2_months_active', 'mapping_category': 'Portfolio Management (35.0%)', 'kpi_weight': 0.1, 'kpi_target': 72.0, 'is_bonus': False},
    {'role_code': 'sme_arm', 'role_name': 'SME ARM', 'kpi_order': 13, 'kpi_code': 'operating_profit', 'mapping_category': 'Portfolio Management (35.0%)', 'kpi_weight': 0.1, 'kpi_target': 6245102.206767494, 'is_bonus': False},
    {'role_code': 'sme_arm', 'role_name': 'SME ARM', 'kpi_order': 14, 'kpi_code': 'deposit_growth', 'mapping_category': 'Portfolio Management (35.0%)', 'kpi_weight': 0.1, 'kpi_target': 72552526.28, 'is_bonus': False},
    {'role_code': 'sme_arm', 'role_name': 'SME ARM', 'kpi_order': 15, 'kpi_code': 'weigted_tat', 'mapping_category': 'Service Excellence (5.0%)', 'kpi_weight': 0.05, 'kpi_target': 1.0, 'is_bonus': False},
    {'role_code': 'sme_arm', 'role_name': 'SME ARM', 'kpi_order': 16, 'kpi_code': 'business_banking_training', 'mapping_category': 'Staff Engagement (5.0%)', 'kpi_weight': 0.025, 'kpi_target': 48.0, 'is_bonus': False},
    {'role_code': 'sme_arm', 'role_name': 'SME ARM', 'kpi_order': 17, 'kpi_code': 'business_banking_leave_magement', 'mapping_category': 'Staff Engagement (5.0%)', 'kpi_weight': 0.025, 'kpi_target': 1.0, 'is_bonus': False},
    {'role_code': 'sme_arm', 'role_name': 'SME ARM', 'kpi_order': 18, 'kpi_code': 'business_banking_par', 'mapping_category': 'Bonus Points (2.5%)', 'kpi_weight': 0.025, 'kpi_target': 0.025, 'is_bonus': True},
    {'role_code': 'sme_bbc', 'role_name': 'SME BBC', 'kpi_order': 1, 'kpi_code': 'new_business_banking_customers', 'mapping_category': 'Weighted sales (35.0%)', 'kpi_weight': 0.075, 'kpi_target': 24.0, 'is_bonus': False},
    {'role_code': 'sme_bbc', 'role_name': 'SME BBC', 'kpi_order': 2, 'kpi_code': 'net_asset_disbursements', 'mapping_category': 'Weighted sales (35.0%)', 'kpi_weight': 0.1, 'kpi_target': 270000000.0, 'is_bonus': False},
    {'role_code': 'sme_bbc', 'role_name': 'SME BBC', 'kpi_order': 3, 'kpi_code': 'asset_growth', 'mapping_category': 'Weighted sales (35.0%)', 'kpi_weight': 0.05, 'kpi_target': 14729931.788000003, 'is_bonus': False},
    {'role_code': 'sme_bbc', 'role_name': 'SME BBC', 'kpi_order': 4, 'kpi_code': 'weighted_sales', 'mapping_category': 'Weighted sales (35.0%)', 'kpi_weight': 0.05, 'kpi_target': None, 'is_bonus': False},
    {'role_code': 'sme_bbc', 'role_name': 'SME BBC', 'kpi_order': 5, 'kpi_code': 'trade_finance_volume', 'mapping_category': 'Weighted sales (35.0%)', 'kpi_weight': 0.075, 'kpi_target': 180000000.0, 'is_bonus': False},
    {'role_code': 'sme_bbc', 'role_name': 'SME BBC', 'kpi_order': 6, 'kpi_code': 'number_of_property', 'mapping_category': 'Group Synergies (20.0%)', 'kpi_weight': 0.05, 'kpi_target': 2.0, 'is_bonus': False},
    {'role_code': 'sme_bbc', 'role_name': 'SME BBC', 'kpi_order': 7, 'kpi_code': 'value_of_property_sales', 'mapping_category': 'Group Synergies (20.0%)', 'kpi_weight': 0.05, 'kpi_target': 16400000.0, 'is_bonus': False},
    {'role_code': 'sme_bbc', 'role_name': 'SME BBC', 'kpi_order': 8, 'kpi_code': 'business_banking_vic_premiums', 'mapping_category': 'Group Synergies (20.0%)', 'kpi_weight': 0.03, 'kpi_target': 1155627.12890625, 'is_bonus': False},
    {'role_code': 'sme_bbc', 'role_name': 'SME BBC', 'kpi_order': 9, 'kpi_code': 'group_synergies_20_0', 'mapping_category': 'Group Synergies (20.0%)', 'kpi_weight': 0.03, 'kpi_target': 1155576.0, 'is_bonus': False},
    {'role_code': 'sme_bbc', 'role_name': 'SME BBC', 'kpi_order': 10, 'kpi_code': 'bancassurance_premiums', 'mapping_category': 'Group Synergies (20.0%)', 'kpi_weight': 0.04, 'kpi_target': 1155576.0, 'is_bonus': False},
    {'role_code': 'sme_bbc', 'role_name': 'SME BBC', 'kpi_order': 11, 'kpi_code': 'portfolio_nps', 'mapping_category': 'Portfolio Management (35.0%)', 'kpi_weight': 0.05, 'kpi_target': 0.6, 'is_bonus': False},
    {'role_code': 'sme_bbc', 'role_name': 'SME BBC', 'kpi_order': 12, 'kpi_code': 'active_customers_2_months_active', 'mapping_category': 'Portfolio Management (35.0%)', 'kpi_weight': 0.1, 'kpi_target': 72.0, 'is_bonus': False},
    {'role_code': 'sme_bbc', 'role_name': 'SME BBC', 'kpi_order': 13, 'kpi_code': 'operating_profit', 'mapping_category': 'Portfolio Management (35.0%)', 'kpi_weight': 0.1, 'kpi_target': 6245102.206767494, 'is_bonus': False},
    {'role_code': 'sme_bbc', 'role_name': 'SME BBC', 'kpi_order': 14, 'kpi_code': 'deposit_growth', 'mapping_category': 'Portfolio Management (35.0%)', 'kpi_weight': 0.1, 'kpi_target': 72552526.28, 'is_bonus': False},
    {'role_code': 'sme_bbc', 'role_name': 'SME BBC', 'kpi_order': 15, 'kpi_code': 'weigted_tat', 'mapping_category': 'Service Excellence (5.0%)', 'kpi_weight': 0.05, 'kpi_target': 1.0, 'is_bonus': False},
    {'role_code': 'sme_bbc', 'role_name': 'SME BBC', 'kpi_order': 16, 'kpi_code': 'business_banking_training', 'mapping_category': 'Staff Engagement (5.0%)', 'kpi_weight': 0.025, 'kpi_target': 48.0, 'is_bonus': False},
    {'role_code': 'sme_bbc', 'role_name': 'SME BBC', 'kpi_order': 17, 'kpi_code': 'business_banking_leave_magement', 'mapping_category': 'Staff Engagement (5.0%)', 'kpi_weight': 0.025, 'kpi_target': 1.0, 'is_bonus': False},
    {'role_code': 'sme_bbc', 'role_name': 'SME BBC', 'kpi_order': 18, 'kpi_code': 'business_banking_par', 'mapping_category': 'Bonus Points (2.5%)', 'kpi_weight': 0.025, 'kpi_target': 0.025, 'is_bonus': True},
    {'role_code': 'pb_rm', 'role_name': 'PB RM', 'kpi_order': 1, 'kpi_code': 'active_customers', 'mapping_category': 'Portfolio Management (37.0%)', 'kpi_weight': 0.07, 'kpi_target': 286.73333333333335, 'is_bonus': False},
    {'role_code': 'pb_rm', 'role_name': 'PB RM', 'kpi_order': 2, 'kpi_code': 'digital_adoption', 'mapping_category': 'Portfolio Management (37.0%)', 'kpi_weight': 0.05, 'kpi_target': 137.33333333333331, 'is_bonus': False},
    {'role_code': 'pb_rm', 'role_name': 'PB RM', 'kpi_order': 3, 'kpi_code': 'personal_banking_new_customers', 'mapping_category': 'Portfolio Management (37.0%)', 'kpi_weight': 0.1, 'kpi_target': 32.0, 'is_bonus': False},
    {'role_code': 'pb_rm', 'role_name': 'PB RM', 'kpi_order': 4, 'kpi_code': 'portfolio_coverage_engagement', 'mapping_category': 'Portfolio Management (37.0%)', 'kpi_weight': 0.05, 'kpi_target': 0.8, 'is_bonus': False},
    {'role_code': 'pb_rm', 'role_name': 'PB RM', 'kpi_order': 5, 'kpi_code': 'income_contribution', 'mapping_category': 'Portfolio Management (37.0%)', 'kpi_weight': 0.1, 'kpi_target': -146594390.6018126, 'is_bonus': False},
    {'role_code': 'pb_rm', 'role_name': 'PB RM', 'kpi_order': 6, 'kpi_code': 'number_of_property', 'mapping_category': 'Group Synergies (23.0%)', 'kpi_weight': 0.05, 'kpi_target': 2.0, 'is_bonus': False},
    {'role_code': 'pb_rm', 'role_name': 'PB RM', 'kpi_order': 7, 'kpi_code': 'value_of_property_sales', 'mapping_category': 'Group Synergies (23.0%)', 'kpi_weight': 0.05, 'kpi_target': 16400000.0, 'is_bonus': False},
    {'role_code': 'pb_rm', 'role_name': 'PB RM', 'kpi_order': 8, 'kpi_code': 'personal_banking_vic_premiums', 'mapping_category': 'Group Synergies (23.0%)', 'kpi_weight': 0.05, 'kpi_target': 1058466.559244792, 'is_bonus': False},
    {'role_code': 'pb_rm', 'role_name': 'PB RM', 'kpi_order': 9, 'kpi_code': 'personal_banking_group_synergies_23_0', 'mapping_category': 'Group Synergies (23.0%)', 'kpi_weight': 0.05, 'kpi_target': 453616.0, 'is_bonus': False},
    {'role_code': 'pb_rm', 'role_name': 'PB RM', 'kpi_order': 10, 'kpi_code': 'bancassurance_premiums', 'mapping_category': 'Group Synergies (23.0%)', 'kpi_weight': 0.03, 'kpi_target': 453616.0, 'is_bonus': False},
    {'role_code': 'pb_rm', 'role_name': 'PB RM', 'kpi_order': 11, 'kpi_code': 'drawdowns', 'mapping_category': 'Balance Sheet (25.0%)', 'kpi_weight': 0.1, 'kpi_target': 108000000.0, 'is_bonus': False},
    {'role_code': 'pb_rm', 'role_name': 'PB RM', 'kpi_order': 12, 'kpi_code': 'asset_growth', 'mapping_category': 'Balance Sheet (25.0%)', 'kpi_weight': 0.075, 'kpi_target': 2009063440.7899992, 'is_bonus': False},
    {'role_code': 'pb_rm', 'role_name': 'PB RM', 'kpi_order': 13, 'kpi_code': 'deposit_growth_liab_growth_ntb_liab', 'mapping_category': 'Balance Sheet (25.0%)', 'kpi_weight': 0.075, 'kpi_target': 264461961.20000005, 'is_bonus': False},
    {'role_code': 'pb_rm', 'role_name': 'PB RM', 'kpi_order': 14, 'kpi_code': 'nps', 'mapping_category': 'Service Excellence (10.0%)', 'kpi_weight': 0.05, 'kpi_target': 0.6, 'is_bonus': False},
    {'role_code': 'pb_rm', 'role_name': 'PB RM', 'kpi_order': 15, 'kpi_code': 'weigted_tat', 'mapping_category': 'Service Excellence (10.0%)', 'kpi_weight': 0.05, 'kpi_target': 1.0, 'is_bonus': False},
    {'role_code': 'pb_rm', 'role_name': 'PB RM', 'kpi_order': 16, 'kpi_code': 'reduce_p_l_provisions_nill_provisions_loan_loss', 'mapping_category': 'NPL ( 5% )', 'kpi_weight': 0.0, 'kpi_target': -5702453.601267383, 'is_bonus': False},
    {'role_code': 'pb_rm', 'role_name': 'PB RM', 'kpi_order': 17, 'kpi_code': 'personal_banking_training', 'mapping_category': 'Staff Engagement (5.0%)', 'kpi_weight': 0.025, 'kpi_target': 32.0, 'is_bonus': False},
    {'role_code': 'pb_rm', 'role_name': 'PB RM', 'kpi_order': 18, 'kpi_code': 'personal_banking_leave_magement', 'mapping_category': 'Staff Engagement (5.0%)', 'kpi_weight': 0.025, 'kpi_target': 1.0, 'is_bonus': False},
    {'role_code': 'pb_rm', 'role_name': 'PB RM', 'kpi_order': 19, 'kpi_code': 'business_banking_par', 'mapping_category': 'Bonus Points (2.5%)', 'kpi_weight': 0.025, 'kpi_target': 0.025, 'is_bonus': True},
    {'role_code': 'pb_arm', 'role_name': 'PB ARM', 'kpi_order': 1, 'kpi_code': 'active_customers', 'mapping_category': 'Portfolio Management (37.0%)', 'kpi_weight': 0.07, 'kpi_target': 286.73333333333335, 'is_bonus': False},
    {'role_code': 'pb_arm', 'role_name': 'PB ARM', 'kpi_order': 2, 'kpi_code': 'digital_adoption', 'mapping_category': 'Portfolio Management (37.0%)', 'kpi_weight': 0.05, 'kpi_target': 137.33333333333331, 'is_bonus': False},
    {'role_code': 'pb_arm', 'role_name': 'PB ARM', 'kpi_order': 3, 'kpi_code': 'personal_banking_new_customers', 'mapping_category': 'Portfolio Management (37.0%)', 'kpi_weight': 0.1, 'kpi_target': 32.0, 'is_bonus': False},
    {'role_code': 'pb_arm', 'role_name': 'PB ARM', 'kpi_order': 4, 'kpi_code': 'portfolio_coverage_engagement', 'mapping_category': 'Portfolio Management (37.0%)', 'kpi_weight': 0.05, 'kpi_target': 0.8, 'is_bonus': False},
    {'role_code': 'pb_arm', 'role_name': 'PB ARM', 'kpi_order': 5, 'kpi_code': 'income_contribution', 'mapping_category': 'Portfolio Management (37.0%)', 'kpi_weight': 0.1, 'kpi_target': -146594390.6018126, 'is_bonus': False},
    {'role_code': 'pb_arm', 'role_name': 'PB ARM', 'kpi_order': 6, 'kpi_code': 'number_of_property', 'mapping_category': 'Group Synergies (23.0%)', 'kpi_weight': 0.05, 'kpi_target': 2.0, 'is_bonus': False},
    {'role_code': 'pb_arm', 'role_name': 'PB ARM', 'kpi_order': 7, 'kpi_code': 'value_of_property_sales', 'mapping_category': 'Group Synergies (23.0%)', 'kpi_weight': 0.05, 'kpi_target': 16400000.0, 'is_bonus': False},
    {'role_code': 'pb_arm', 'role_name': 'PB ARM', 'kpi_order': 8, 'kpi_code': 'personal_banking_vic_premiums', 'mapping_category': 'Group Synergies (23.0%)', 'kpi_weight': 0.05, 'kpi_target': 1058466.559244792, 'is_bonus': False},
    {'role_code': 'pb_arm', 'role_name': 'PB ARM', 'kpi_order': 9, 'kpi_code': 'personal_banking_group_synergies_23_0', 'mapping_category': 'Group Synergies (23.0%)', 'kpi_weight': 0.05, 'kpi_target': 453616.0, 'is_bonus': False},
    {'role_code': 'pb_arm', 'role_name': 'PB ARM', 'kpi_order': 10, 'kpi_code': 'bancassurance_premiums', 'mapping_category': 'Group Synergies (23.0%)', 'kpi_weight': 0.03, 'kpi_target': 453616.0, 'is_bonus': False},
    {'role_code': 'pb_arm', 'role_name': 'PB ARM', 'kpi_order': 11, 'kpi_code': 'drawdowns', 'mapping_category': 'Balance Sheet (25.0%)', 'kpi_weight': 0.1, 'kpi_target': 108000000.0, 'is_bonus': False},
    {'role_code': 'pb_arm', 'role_name': 'PB ARM', 'kpi_order': 12, 'kpi_code': 'asset_growth', 'mapping_category': 'Balance Sheet (25.0%)', 'kpi_weight': 0.075, 'kpi_target': 2009063440.7899992, 'is_bonus': False},
    {'role_code': 'pb_arm', 'role_name': 'PB ARM', 'kpi_order': 13, 'kpi_code': 'deposit_growth_liab_growth_ntb_liab', 'mapping_category': 'Balance Sheet (25.0%)', 'kpi_weight': 0.075, 'kpi_target': 264461961.20000005, 'is_bonus': False},
    {'role_code': 'pb_arm', 'role_name': 'PB ARM', 'kpi_order': 14, 'kpi_code': 'nps', 'mapping_category': 'Service Excellence (10.0%)', 'kpi_weight': 0.05, 'kpi_target': 0.6, 'is_bonus': False},
    {'role_code': 'pb_arm', 'role_name': 'PB ARM', 'kpi_order': 15, 'kpi_code': 'weigted_tat', 'mapping_category': 'Service Excellence (10.0%)', 'kpi_weight': 0.05, 'kpi_target': 1.0, 'is_bonus': False},
    {'role_code': 'pb_arm', 'role_name': 'PB ARM', 'kpi_order': 16, 'kpi_code': 'reduce_p_l_provisions_nill_provisions_loan_loss', 'mapping_category': 'NPL ( 5% )', 'kpi_weight': 0.0, 'kpi_target': -5702453.601267383, 'is_bonus': False},
    {'role_code': 'pb_arm', 'role_name': 'PB ARM', 'kpi_order': 17, 'kpi_code': 'personal_banking_training', 'mapping_category': 'Staff Engagement (5.0%)', 'kpi_weight': 0.025, 'kpi_target': 32.0, 'is_bonus': False},
    {'role_code': 'pb_arm', 'role_name': 'PB ARM', 'kpi_order': 18, 'kpi_code': 'personal_banking_leave_magement', 'mapping_category': 'Staff Engagement (5.0%)', 'kpi_weight': 0.025, 'kpi_target': 1.0, 'is_bonus': False},
    {'role_code': 'pb_arm', 'role_name': 'PB ARM', 'kpi_order': 19, 'kpi_code': 'business_banking_par', 'mapping_category': 'Bonus Points (2.5%)', 'kpi_weight': 0.025, 'kpi_target': 0.025, 'is_bonus': True},
    {'role_code': 'pb_bbc', 'role_name': 'PB BBC', 'kpi_order': 1, 'kpi_code': 'active_customers', 'mapping_category': 'Portfolio Management (37.0%)', 'kpi_weight': 0.07, 'kpi_target': 286.73333333333335, 'is_bonus': False},
    {'role_code': 'pb_bbc', 'role_name': 'PB BBC', 'kpi_order': 2, 'kpi_code': 'digital_adoption', 'mapping_category': 'Portfolio Management (37.0%)', 'kpi_weight': 0.05, 'kpi_target': 137.33333333333331, 'is_bonus': False},
    {'role_code': 'pb_bbc', 'role_name': 'PB BBC', 'kpi_order': 3, 'kpi_code': 'personal_banking_new_customers', 'mapping_category': 'Portfolio Management (37.0%)', 'kpi_weight': 0.1, 'kpi_target': 32.0, 'is_bonus': False},
    {'role_code': 'pb_bbc', 'role_name': 'PB BBC', 'kpi_order': 4, 'kpi_code': 'portfolio_coverage_engagement', 'mapping_category': 'Portfolio Management (37.0%)', 'kpi_weight': 0.05, 'kpi_target': 0.8, 'is_bonus': False},
    {'role_code': 'pb_bbc', 'role_name': 'PB BBC', 'kpi_order': 5, 'kpi_code': 'income_contribution', 'mapping_category': 'Portfolio Management (37.0%)', 'kpi_weight': 0.1, 'kpi_target': -146594390.6018126, 'is_bonus': False},
    {'role_code': 'pb_bbc', 'role_name': 'PB BBC', 'kpi_order': 6, 'kpi_code': 'number_of_property', 'mapping_category': 'Group Synergies (23.0%)', 'kpi_weight': 0.05, 'kpi_target': 2.0, 'is_bonus': False},
    {'role_code': 'pb_bbc', 'role_name': 'PB BBC', 'kpi_order': 7, 'kpi_code': 'value_of_property_sales', 'mapping_category': 'Group Synergies (23.0%)', 'kpi_weight': 0.05, 'kpi_target': 16400000.0, 'is_bonus': False},
    {'role_code': 'pb_bbc', 'role_name': 'PB BBC', 'kpi_order': 8, 'kpi_code': 'personal_banking_vic_premiums', 'mapping_category': 'Group Synergies (23.0%)', 'kpi_weight': 0.05, 'kpi_target': 1058466.559244792, 'is_bonus': False},
    {'role_code': 'pb_bbc', 'role_name': 'PB BBC', 'kpi_order': 9, 'kpi_code': 'personal_banking_group_synergies_23_0', 'mapping_category': 'Group Synergies (23.0%)', 'kpi_weight': 0.05, 'kpi_target': 453616.0, 'is_bonus': False},
    {'role_code': 'pb_bbc', 'role_name': 'PB BBC', 'kpi_order': 10, 'kpi_code': 'bancassurance_premiums', 'mapping_category': 'Group Synergies (23.0%)', 'kpi_weight': 0.03, 'kpi_target': 453616.0, 'is_bonus': False},
    {'role_code': 'pb_bbc', 'role_name': 'PB BBC', 'kpi_order': 11, 'kpi_code': 'drawdowns', 'mapping_category': 'Balance Sheet (25.0%)', 'kpi_weight': 0.1, 'kpi_target': 108000000.0, 'is_bonus': False},
    {'role_code': 'pb_bbc', 'role_name': 'PB BBC', 'kpi_order': 12, 'kpi_code': 'asset_growth', 'mapping_category': 'Balance Sheet (25.0%)', 'kpi_weight': 0.075, 'kpi_target': 2009063440.7899992, 'is_bonus': False},
    {'role_code': 'pb_bbc', 'role_name': 'PB BBC', 'kpi_order': 13, 'kpi_code': 'deposit_growth_liab_growth_ntb_liab', 'mapping_category': 'Balance Sheet (25.0%)', 'kpi_weight': 0.075, 'kpi_target': 264461961.20000005, 'is_bonus': False},
    {'role_code': 'pb_bbc', 'role_name': 'PB BBC', 'kpi_order': 14, 'kpi_code': 'nps', 'mapping_category': 'Service Excellence (10.0%)', 'kpi_weight': 0.05, 'kpi_target': 0.6, 'is_bonus': False},
    {'role_code': 'pb_bbc', 'role_name': 'PB BBC', 'kpi_order': 15, 'kpi_code': 'weigted_tat', 'mapping_category': 'Service Excellence (10.0%)', 'kpi_weight': 0.05, 'kpi_target': 1.0, 'is_bonus': False},
    {'role_code': 'pb_bbc', 'role_name': 'PB BBC', 'kpi_order': 16, 'kpi_code': 'reduce_p_l_provisions_nill_provisions_loan_loss', 'mapping_category': 'NPL ( 5% )', 'kpi_weight': 0.0, 'kpi_target': -5702453.601267383, 'is_bonus': False},
    {'role_code': 'pb_bbc', 'role_name': 'PB BBC', 'kpi_order': 17, 'kpi_code': 'personal_banking_training', 'mapping_category': 'Staff Engagement (5.0%)', 'kpi_weight': 0.025, 'kpi_target': 32.0, 'is_bonus': False},
    {'role_code': 'pb_bbc', 'role_name': 'PB BBC', 'kpi_order': 18, 'kpi_code': 'personal_banking_leave_magement', 'mapping_category': 'Staff Engagement (5.0%)', 'kpi_weight': 0.025, 'kpi_target': 1.0, 'is_bonus': False},
    {'role_code': 'pb_bbc', 'role_name': 'PB BBC', 'kpi_order': 19, 'kpi_code': 'business_banking_par', 'mapping_category': 'Bonus Points (2.5%)', 'kpi_weight': 0.025, 'kpi_target': 0.025, 'is_bonus': True},
    {'role_code': 'ultimate_rm', 'role_name': 'Ultimate RM', 'kpi_order': 1, 'kpi_code': 'number_of_property', 'mapping_category': 'Group Synergies (23.0%)', 'kpi_weight': 0.05, 'kpi_target': 1.25, 'is_bonus': False},
    {'role_code': 'ultimate_rm', 'role_name': 'Ultimate RM', 'kpi_order': 2, 'kpi_code': 'value_of_property_sales', 'mapping_category': 'Group Synergies (23.0%)', 'kpi_weight': 0.05, 'kpi_target': 10250000.0, 'is_bonus': False},
    {'role_code': 'ultimate_rm', 'role_name': 'Ultimate RM', 'kpi_order': 3, 'kpi_code': 'personal_banking_vic_premiums', 'mapping_category': 'Group Synergies (23.0%)', 'kpi_weight': 0.05, 'kpi_target': 709070.4559326171, 'is_bonus': False},
    {'role_code': 'ultimate_rm', 'role_name': 'Ultimate RM', 'kpi_order': 4, 'kpi_code': 'personal_banking_group_synergies_23_0', 'mapping_category': 'Group Synergies (23.0%)', 'kpi_weight': 0.05, 'kpi_target': 303875.0, 'is_bonus': False},
    {'role_code': 'ultimate_rm', 'role_name': 'Ultimate RM', 'kpi_order': 5, 'kpi_code': 'bancassurance_premiums', 'mapping_category': 'Group Synergies (23.0%)', 'kpi_weight': 0.03, 'kpi_target': 303875.0, 'is_bonus': False},
    {'role_code': 'ultimate_rm', 'role_name': 'Ultimate RM', 'kpi_order': 6, 'kpi_code': 'portfolio_nps', 'mapping_category': 'Portfolio Management/Financials (64.5%)', 'kpi_weight': 0.1, 'kpi_target': 0.6, 'is_bonus': False},
    {'role_code': 'ultimate_rm', 'role_name': 'Ultimate RM', 'kpi_order': 7, 'kpi_code': 'ultimate_rm_net_disbursements', 'mapping_category': 'Portfolio Management/Financials (64.5%)', 'kpi_weight': 0.075, 'kpi_target': 125000000.0, 'is_bonus': False},
    {'role_code': 'ultimate_rm', 'role_name': 'Ultimate RM', 'kpi_order': 8, 'kpi_code': 'asset_growth', 'mapping_category': 'Portfolio Management/Financials (64.5%)', 'kpi_weight': 0.075, 'kpi_target': 583814536.94, 'is_bonus': False},
    {'role_code': 'ultimate_rm', 'role_name': 'Ultimate RM', 'kpi_order': 9, 'kpi_code': 'income_contribution_portfolio_ntb', 'mapping_category': 'Portfolio Management/Financials (64.5%)', 'kpi_weight': 0.075, 'kpi_target': 10420001.242471872, 'is_bonus': False},
    {'role_code': 'ultimate_rm', 'role_name': 'Ultimate RM', 'kpi_order': 10, 'kpi_code': 'deposits_portfolio_ntb', 'mapping_category': 'Portfolio Management/Financials (64.5%)', 'kpi_weight': 0.15, 'kpi_target': 954744625.3500001, 'is_bonus': False},
    {'role_code': 'ultimate_rm', 'role_name': 'Ultimate RM', 'kpi_order': 11, 'kpi_code': 'reduce_p_l_provisions_nil_provisions_loan_loss', 'mapping_category': 'Portfolio Management/Financials (64.5%)', 'kpi_weight': 0.05, 'kpi_target': -1512397.9537892307, 'is_bonus': False},
    {'role_code': 'ultimate_rm', 'role_name': 'Ultimate RM', 'kpi_order': 12, 'kpi_code': 'active_customers_two_month', 'mapping_category': 'Portfolio Management/Financials (64.5%)', 'kpi_weight': 0.07, 'kpi_target': 140.4, 'is_bonus': False},
    {'role_code': 'ultimate_rm', 'role_name': 'Ultimate RM', 'kpi_order': 13, 'kpi_code': 'ultimate_rm_new_customers', 'mapping_category': 'Portfolio Management/Financials (64.5%)', 'kpi_weight': 0.05, 'kpi_target': 10.0, 'is_bonus': False},
    {'role_code': 'ultimate_rm', 'role_name': 'Ultimate RM', 'kpi_order': 14, 'kpi_code': 'weighted_sales_dashboard', 'mapping_category': 'Weighted Sales (5.0%)', 'kpi_weight': 0.05, 'kpi_target': 0.8, 'is_bonus': False},
    {'role_code': 'ultimate_rm', 'role_name': 'Ultimate RM', 'kpi_order': 15, 'kpi_code': 'weigted_tat', 'mapping_category': 'Service Excellence (2.5%)', 'kpi_weight': 0.025, 'kpi_target': 1.0, 'is_bonus': False},
    {'role_code': 'ultimate_rm', 'role_name': 'Ultimate RM', 'kpi_order': 16, 'kpi_code': 'personal_banking_training', 'mapping_category': 'Staff Engagement (5.0%)', 'kpi_weight': 0.025, 'kpi_target': 0.8333333333333334, 'is_bonus': False},
    {'role_code': 'ultimate_rm', 'role_name': 'Ultimate RM', 'kpi_order': 17, 'kpi_code': 'personal_banking_leave_magement', 'mapping_category': 'Staff Engagement (5.0%)', 'kpi_weight': 0.025, 'kpi_target': 1.0, 'is_bonus': False},
    {'role_code': 'ultimate_rm', 'role_name': 'Ultimate RM', 'kpi_order': 18, 'kpi_code': 'business_banking_par', 'mapping_category': 'Bonus Points (2.5%)', 'kpi_weight': 0.025, 'kpi_target': 0.025, 'is_bonus': True},
    {'role_code': 'diaspora_rm', 'role_name': 'DIASPORA RM', 'kpi_order': 1, 'kpi_code': 'diaspora_net_disbursements', 'mapping_category': 'Financials (15.0%)', 'kpi_weight': 0.075, 'kpi_target': 240000000.0, 'is_bonus': False},
    {'role_code': 'diaspora_rm', 'role_name': 'DIASPORA RM', 'kpi_order': 2, 'kpi_code': 'asset_growth', 'mapping_category': 'Financials (15.0%)', 'kpi_weight': 0.075, 'kpi_target': 173791134.54000005, 'is_bonus': False},
    {'role_code': 'diaspora_rm', 'role_name': 'DIASPORA RM', 'kpi_order': 3, 'kpi_code': 'number_of_property', 'mapping_category': 'Group Synergies (23.0%)', 'kpi_weight': 0.05, 'kpi_target': 3.0, 'is_bonus': False},
    {'role_code': 'diaspora_rm', 'role_name': 'DIASPORA RM', 'kpi_order': 4, 'kpi_code': 'value_of_property_sales', 'mapping_category': 'Group Synergies (23.0%)', 'kpi_weight': 0.05, 'kpi_target': 24600000.0, 'is_bonus': False},
    {'role_code': 'diaspora_rm', 'role_name': 'DIASPORA RM', 'kpi_order': 5, 'kpi_code': 'vic_premium', 'mapping_category': 'Group Synergies (23.0%)', 'kpi_weight': 0.065, 'kpi_target': 1850342.368164062, 'is_bonus': False},
    {'role_code': 'diaspora_rm', 'role_name': 'DIASPORA RM', 'kpi_order': 6, 'kpi_code': 'personal_banking_group_synergies_23_0', 'mapping_category': 'Group Synergies (23.0%)', 'kpi_weight': 0.065, 'kpi_target': 793056.0, 'is_bonus': False},
    {'role_code': 'diaspora_rm', 'role_name': 'DIASPORA RM', 'kpi_order': 7, 'kpi_code': 'operating_profit', 'mapping_category': 'Portfolio Management (44.5%)', 'kpi_weight': 0.15, 'kpi_target': 15032536.718206279, 'is_bonus': False},
    {'role_code': 'diaspora_rm', 'role_name': 'DIASPORA RM', 'kpi_order': 8, 'kpi_code': 'deposit_growth', 'mapping_category': 'Portfolio Management (44.5%)', 'kpi_weight': 0.1, 'kpi_target': 317288013.61, 'is_bonus': False},
    {'role_code': 'diaspora_rm', 'role_name': 'DIASPORA RM', 'kpi_order': 9, 'kpi_code': 'personal_banking_new_customers', 'mapping_category': 'Portfolio Management (44.5%)', 'kpi_weight': 0.075, 'kpi_target': 1.2779456193353473, 'is_bonus': False},
    {'role_code': 'diaspora_rm', 'role_name': 'DIASPORA RM', 'kpi_order': 10, 'kpi_code': 'portfolio_management_aum_dec_previous_year', 'mapping_category': 'Portfolio Management (44.5%)', 'kpi_weight': 0.07, 'kpi_target': 776734323.5200002, 'is_bonus': False},
    {'role_code': 'diaspora_rm', 'role_name': 'DIASPORA RM', 'kpi_order': 11, 'kpi_code': 'portfolio_nps', 'mapping_category': 'Portfolio Management (44.5%)', 'kpi_weight': 0.05, 'kpi_target': 0.6, 'is_bonus': False},
    {'role_code': 'diaspora_rm', 'role_name': 'DIASPORA RM', 'kpi_order': 12, 'kpi_code': 'weigted_tat_sla_service_standards_query_response_time', 'mapping_category': 'Customer Experience (10.0%)', 'kpi_weight': 0.1, 'kpi_target': 1.0, 'is_bonus': False},
    {'role_code': 'diaspora_rm', 'role_name': 'DIASPORA RM', 'kpi_order': 13, 'kpi_code': 'audit', 'mapping_category': 'Process Controls (2.5%)', 'kpi_weight': 0.025, 'kpi_target': 1.65, 'is_bonus': False},
    {'role_code': 'diaspora_rm', 'role_name': 'DIASPORA RM', 'kpi_order': 14, 'kpi_code': 'business_banking_training', 'mapping_category': 'Staff Engagement (5.0%)', 'kpi_weight': 0.025, 'kpi_target': 60.0, 'is_bonus': False},
    {'role_code': 'diaspora_rm', 'role_name': 'DIASPORA RM', 'kpi_order': 15, 'kpi_code': 'business_banking_leave_magement', 'mapping_category': 'Staff Engagement (5.0%)', 'kpi_weight': 0.025, 'kpi_target': 1.0, 'is_bonus': False},
    {'role_code': 'diaspora_rm', 'role_name': 'DIASPORA RM', 'kpi_order': 16, 'kpi_code': 'business_banking_par', 'mapping_category': 'Bonus Points (2.5%)', 'kpi_weight': 0.025, 'kpi_target': 0.025, 'is_bonus': True},
    {'role_code': 'diaspora_arm', 'role_name': 'DIASPORA ARM', 'kpi_order': 1, 'kpi_code': 'diaspora_net_disbursements', 'mapping_category': 'Financials (15.0%)', 'kpi_weight': 0.075, 'kpi_target': 240000000.0, 'is_bonus': False},
    {'role_code': 'diaspora_arm', 'role_name': 'DIASPORA ARM', 'kpi_order': 2, 'kpi_code': 'asset_growth', 'mapping_category': 'Financials (15.0%)', 'kpi_weight': 0.075, 'kpi_target': 173791134.54000005, 'is_bonus': False},
    {'role_code': 'diaspora_arm', 'role_name': 'DIASPORA ARM', 'kpi_order': 3, 'kpi_code': 'number_of_property', 'mapping_category': 'Group Synergies (23.0%)', 'kpi_weight': 0.05, 'kpi_target': 3.0, 'is_bonus': False},
    {'role_code': 'diaspora_arm', 'role_name': 'DIASPORA ARM', 'kpi_order': 4, 'kpi_code': 'value_of_property_sales', 'mapping_category': 'Group Synergies (23.0%)', 'kpi_weight': 0.05, 'kpi_target': 24600000.0, 'is_bonus': False},
    {'role_code': 'diaspora_arm', 'role_name': 'DIASPORA ARM', 'kpi_order': 5, 'kpi_code': 'vic_premium', 'mapping_category': 'Group Synergies (23.0%)', 'kpi_weight': 0.065, 'kpi_target': 1850342.368164062, 'is_bonus': False},
    {'role_code': 'diaspora_arm', 'role_name': 'DIASPORA ARM', 'kpi_order': 6, 'kpi_code': 'personal_banking_group_synergies_23_0', 'mapping_category': 'Group Synergies (23.0%)', 'kpi_weight': 0.065, 'kpi_target': 793056.0, 'is_bonus': False},
    {'role_code': 'diaspora_arm', 'role_name': 'DIASPORA ARM', 'kpi_order': 7, 'kpi_code': 'operating_profit', 'mapping_category': 'Portfolio Management (44.5%)', 'kpi_weight': 0.15, 'kpi_target': 15032536.718206279, 'is_bonus': False},
    {'role_code': 'diaspora_arm', 'role_name': 'DIASPORA ARM', 'kpi_order': 8, 'kpi_code': 'deposit_growth', 'mapping_category': 'Portfolio Management (44.5%)', 'kpi_weight': 0.1, 'kpi_target': 317288013.61, 'is_bonus': False},
    {'role_code': 'diaspora_arm', 'role_name': 'DIASPORA ARM', 'kpi_order': 9, 'kpi_code': 'personal_banking_new_customers', 'mapping_category': 'Portfolio Management (44.5%)', 'kpi_weight': 0.075, 'kpi_target': 1.2779456193353473, 'is_bonus': False},
    {'role_code': 'diaspora_arm', 'role_name': 'DIASPORA ARM', 'kpi_order': 10, 'kpi_code': 'portfolio_management_aum_dec_previous_year', 'mapping_category': 'Portfolio Management (44.5%)', 'kpi_weight': 0.07, 'kpi_target': 776734323.5200002, 'is_bonus': False},
    {'role_code': 'diaspora_arm', 'role_name': 'DIASPORA ARM', 'kpi_order': 11, 'kpi_code': 'portfolio_nps', 'mapping_category': 'Portfolio Management (44.5%)', 'kpi_weight': 0.05, 'kpi_target': 0.6, 'is_bonus': False},
    {'role_code': 'diaspora_arm', 'role_name': 'DIASPORA ARM', 'kpi_order': 12, 'kpi_code': 'weigted_tat_sla_service_standards_query_response_time', 'mapping_category': 'Customer Experience (10.0%)', 'kpi_weight': 0.1, 'kpi_target': 1.0, 'is_bonus': False},
    {'role_code': 'diaspora_arm', 'role_name': 'DIASPORA ARM', 'kpi_order': 13, 'kpi_code': 'audit', 'mapping_category': 'Process Controls (2.5%)', 'kpi_weight': 0.025, 'kpi_target': 1.65, 'is_bonus': False},
    {'role_code': 'diaspora_arm', 'role_name': 'DIASPORA ARM', 'kpi_order': 14, 'kpi_code': 'business_banking_training', 'mapping_category': 'Staff Engagement (5.0%)', 'kpi_weight': 0.025, 'kpi_target': 60.0, 'is_bonus': False},
    {'role_code': 'diaspora_arm', 'role_name': 'DIASPORA ARM', 'kpi_order': 15, 'kpi_code': 'business_banking_leave_magement', 'mapping_category': 'Staff Engagement (5.0%)', 'kpi_weight': 0.025, 'kpi_target': 1.0, 'is_bonus': False},
    {'role_code': 'diaspora_arm', 'role_name': 'DIASPORA ARM', 'kpi_order': 16, 'kpi_code': 'business_banking_par', 'mapping_category': 'Bonus Points (2.5%)', 'kpi_weight': 0.025, 'kpi_target': 0.025, 'is_bonus': True},
    {'role_code': 'mortgage_business_arm', 'role_name': 'Mortgage Business ARM', 'kpi_order': 1, 'kpi_code': 'net_mortgage_sales_10_commercial_rate_mortgages', 'mapping_category': 'Financials (47.5%)', 'kpi_weight': 0.2, 'kpi_target': 0.0, 'is_bonus': False},
    {'role_code': 'mortgage_business_arm', 'role_name': 'Mortgage Business ARM', 'kpi_order': 2, 'kpi_code': 'net_mortgage_sales_10_non_commercial_rate_mortgages', 'mapping_category': 'Financials (47.5%)', 'kpi_weight': 0.2, 'kpi_target': 0.0, 'is_bonus': False},
    {'role_code': 'mortgage_business_arm', 'role_name': 'Mortgage Business ARM', 'kpi_order': 3, 'kpi_code': 'cross_sell_new_casa_accounts_focus_accounts', 'mapping_category': 'Financials (47.5%)', 'kpi_weight': 0.075, 'kpi_target': 0.0, 'is_bonus': False},
    {'role_code': 'mortgage_business_arm', 'role_name': 'Mortgage Business ARM', 'kpi_order': 4, 'kpi_code': 'number_of_property', 'mapping_category': 'Group Synergies (25.0%)', 'kpi_weight': 0.075, 'kpi_target': 0.0, 'is_bonus': False},
    {'role_code': 'mortgage_business_arm', 'role_name': 'Mortgage Business ARM', 'kpi_order': 5, 'kpi_code': 'value_of_property_sales', 'mapping_category': 'Group Synergies (25.0%)', 'kpi_weight': 0.075, 'kpi_target': 0.0, 'is_bonus': False},
    {'role_code': 'mortgage_business_arm', 'role_name': 'Mortgage Business ARM', 'kpi_order': 6, 'kpi_code': 'personal_banking_vic_premiums', 'mapping_category': 'Group Synergies (25.0%)', 'kpi_weight': 0.05, 'kpi_target': 0.0, 'is_bonus': False},
    {'role_code': 'mortgage_business_arm', 'role_name': 'Mortgage Business ARM', 'kpi_order': 7, 'kpi_code': 'group_synergies_25_0', 'mapping_category': 'Group Synergies (25.0%)', 'kpi_weight': 0.05, 'kpi_target': 0.0, 'is_bonus': False},
    {'role_code': 'mortgage_business_arm', 'role_name': 'Mortgage Business ARM', 'kpi_order': 8, 'kpi_code': 'portfolio_nps', 'mapping_category': 'Customer Service (5.0%)', 'kpi_weight': 0.05, 'kpi_target': 0.6, 'is_bonus': False},
    {'role_code': 'mortgage_business_arm', 'role_name': 'Mortgage Business ARM', 'kpi_order': 9, 'kpi_code': 'tat_loan', 'mapping_category': 'Process and Controls (15.0%)', 'kpi_weight': 0.1, 'kpi_target': 7.0, 'is_bonus': False},
    {'role_code': 'mortgage_business_arm', 'role_name': 'Mortgage Business ARM', 'kpi_order': 10, 'kpi_code': 'errors', 'mapping_category': 'Process and Controls (15.0%)', 'kpi_weight': 0.05, 'kpi_target': 0.05, 'is_bonus': False},
    {'role_code': 'mortgage_business_arm', 'role_name': 'Mortgage Business ARM', 'kpi_order': 11, 'kpi_code': 'personal_banking_training', 'mapping_category': 'Staff Engagement (7.5%)', 'kpi_weight': 0.05, 'kpi_target': 16.0, 'is_bonus': False},
    {'role_code': 'mortgage_business_arm', 'role_name': 'Mortgage Business ARM', 'kpi_order': 12, 'kpi_code': 'business_banking_leave_magement', 'mapping_category': 'Staff Engagement (7.5%)', 'kpi_weight': 0.025, 'kpi_target': 1.0, 'is_bonus': False},
    {'role_code': 'mortgage_business_arm', 'role_name': 'Mortgage Business ARM', 'kpi_order': 13, 'kpi_code': 'mortgage_business_par', 'mapping_category': 'Bonus Points (2.5%)', 'kpi_weight': 0.025, 'kpi_target': 0.025, 'is_bonus': True},
    {'role_code': 'commercial_rm', 'role_name': 'COMMERCIAL RM', 'kpi_order': 1, 'kpi_code': 'trade_income', 'mapping_category': 'Financials (20.0%)', 'kpi_weight': 0.05, 'kpi_target': 9600000.0, 'is_bonus': False},
    {'role_code': 'commercial_rm', 'role_name': 'COMMERCIAL RM', 'kpi_order': 2, 'kpi_code': 'direct_portfolio_contribution', 'mapping_category': 'Financials (20.0%)', 'kpi_weight': 0.1, 'kpi_target': 277856513.62800014, 'is_bonus': False},
    {'role_code': 'commercial_rm', 'role_name': 'COMMERCIAL RM', 'kpi_order': 3, 'kpi_code': 'loan_loss', 'mapping_category': 'Financials (20.0%)', 'kpi_weight': 0.05, 'kpi_target': -7396772.508053169, 'is_bonus': False},
    {'role_code': 'commercial_rm', 'role_name': 'COMMERCIAL RM', 'kpi_order': 4, 'kpi_code': 'number_of_property', 'mapping_category': 'Group Synergies (20.0%)', 'kpi_weight': 0.05, 'kpi_target': 3.0, 'is_bonus': False},
    {'role_code': 'commercial_rm', 'role_name': 'COMMERCIAL RM', 'kpi_order': 5, 'kpi_code': 'value_of_property_sales', 'mapping_category': 'Group Synergies (20.0%)', 'kpi_weight': 0.05, 'kpi_target': 24600000.0, 'is_bonus': False},
    {'role_code': 'commercial_rm', 'role_name': 'COMMERCIAL RM', 'kpi_order': 6, 'kpi_code': 'commercial_vic_premiums', 'mapping_category': 'Group Synergies (20.0%)', 'kpi_weight': 0.1, 'kpi_target': 12223177.319335938, 'is_bonus': False},
    {'role_code': 'commercial_rm', 'role_name': 'COMMERCIAL RM', 'kpi_order': 7, 'kpi_code': 'portfolio_nps', 'mapping_category': 'Portfolio Management (55.0%)', 'kpi_weight': 0.05, 'kpi_target': 0.6, 'is_bonus': False},
    {'role_code': 'commercial_rm', 'role_name': 'COMMERCIAL RM', 'kpi_order': 8, 'kpi_code': 'portfolio_coverage_engagement', 'mapping_category': 'Portfolio Management (55.0%)', 'kpi_weight': 0.05, 'kpi_target': 0.8, 'is_bonus': False},
    {'role_code': 'commercial_rm', 'role_name': 'COMMERCIAL RM', 'kpi_order': 9, 'kpi_code': 'grow_deposits', 'mapping_category': 'Portfolio Management (55.0%)', 'kpi_weight': 0.1, 'kpi_target': 513542063.96999997, 'is_bonus': False},
    {'role_code': 'commercial_rm', 'role_name': 'COMMERCIAL RM', 'kpi_order': 10, 'kpi_code': 'new_customer_min_turnover_of_50m', 'mapping_category': 'Portfolio Management (55.0%)', 'kpi_weight': 0.05, 'kpi_target': 12.0, 'is_bonus': False},
    {'role_code': 'commercial_rm', 'role_name': 'COMMERCIAL RM', 'kpi_order': 11, 'kpi_code': 'net_loan_disbursments', 'mapping_category': 'Portfolio Management (55.0%)', 'kpi_weight': 0.1, 'kpi_target': 780000000.0, 'is_bonus': False},
    {'role_code': 'commercial_rm', 'role_name': 'COMMERCIAL RM', 'kpi_order': 12, 'kpi_code': 'asset_growth', 'mapping_category': 'Portfolio Management (55.0%)', 'kpi_weight': 0.1, 'kpi_target': 1752701010.45, 'is_bonus': False},
    {'role_code': 'commercial_rm', 'role_name': 'COMMERCIAL RM', 'kpi_order': 13, 'kpi_code': 'banking_covenant_tracking_should_be_in_iapply', 'mapping_category': 'Portfolio Management (55.0%)', 'kpi_weight': 0.05, 'kpi_target': 12.0, 'is_bonus': False},
    {'role_code': 'commercial_rm', 'role_name': 'COMMERCIAL RM', 'kpi_order': 14, 'kpi_code': 'tooling_and_account_planning_all_customers', 'mapping_category': 'Portfolio Management (55.0%)', 'kpi_weight': 0.05, 'kpi_target': 12.0, 'is_bonus': False},
    {'role_code': 'commercial_rm', 'role_name': 'COMMERCIAL RM', 'kpi_order': 15, 'kpi_code': 'business_banking_training', 'mapping_category': 'Staff Engagement (5.0%)', 'kpi_weight': 0.025, 'kpi_target': 48.0, 'is_bonus': False},
    {'role_code': 'commercial_rm', 'role_name': 'COMMERCIAL RM', 'kpi_order': 16, 'kpi_code': 'business_banking_leave_magement', 'mapping_category': 'Staff Engagement (5.0%)', 'kpi_weight': 0.025, 'kpi_target': 1.0, 'is_bonus': False},
    {'role_code': 'commercial_rm', 'role_name': 'COMMERCIAL RM', 'kpi_order': 17, 'kpi_code': 'business_banking_par', 'mapping_category': 'Bonus Points (2.5%)', 'kpi_weight': 0.025, 'kpi_target': 0.025, 'is_bonus': True},
    {'role_code': 'commercial_rm_trade', 'role_name': 'COMMERCIAL RM- TRADE', 'kpi_order': 1, 'kpi_code': 'trade_income', 'mapping_category': 'Financials (55.0%)', 'kpi_weight': 0.2, 'kpi_target': 24000000.0, 'is_bonus': False},
    {'role_code': 'commercial_rm_trade', 'role_name': 'COMMERCIAL RM- TRADE', 'kpi_order': 2, 'kpi_code': 'trade_volume', 'mapping_category': 'Financials (55.0%)', 'kpi_weight': 0.15, 'kpi_target': 1200000000.0, 'is_bonus': False},
    {'role_code': 'commercial_rm_trade', 'role_name': 'COMMERCIAL RM- TRADE', 'kpi_order': 3, 'kpi_code': 'new_customer_min_turnover_of_10m', 'mapping_category': 'Financials (55.0%)', 'kpi_weight': 0.1, 'kpi_target': 12.0, 'is_bonus': False},
    {'role_code': 'commercial_rm_trade', 'role_name': 'COMMERCIAL RM- TRADE', 'kpi_order': 4, 'kpi_code': 'loan_loss', 'mapping_category': 'Financials (55.0%)', 'kpi_weight': 0.05, 'kpi_target': -16042448.389348377, 'is_bonus': False},
    {'role_code': 'commercial_rm_trade', 'role_name': 'COMMERCIAL RM- TRADE', 'kpi_order': 5, 'kpi_code': 'net_loan_disbursments', 'mapping_category': 'Financials (55.0%)', 'kpi_weight': 0.05, 'kpi_target': 240000000.0, 'is_bonus': False},
    {'role_code': 'commercial_rm_trade', 'role_name': 'COMMERCIAL RM- TRADE', 'kpi_order': 6, 'kpi_code': 'number_of_property', 'mapping_category': 'Group Synergies (23.0%)', 'kpi_weight': 0.05, 'kpi_target': 3.0, 'is_bonus': False},
    {'role_code': 'commercial_rm_trade', 'role_name': 'COMMERCIAL RM- TRADE', 'kpi_order': 7, 'kpi_code': 'value_of_property_sales', 'mapping_category': 'Group Synergies (23.0%)', 'kpi_weight': 0.05, 'kpi_target': 24600000.0, 'is_bonus': False},
    {'role_code': 'commercial_rm_trade', 'role_name': 'COMMERCIAL RM- TRADE', 'kpi_order': 8, 'kpi_code': 'personal_banking_vic_premiums', 'mapping_category': 'Group Synergies (23.0%)', 'kpi_weight': 0.05, 'kpi_target': 7639292.705078125, 'is_bonus': False},
    {'role_code': 'commercial_rm_trade', 'role_name': 'COMMERCIAL RM- TRADE', 'kpi_order': 9, 'kpi_code': 'commercial_trade_group_synergies_23_0', 'mapping_category': 'Group Synergies (23.0%)', 'kpi_weight': 0.05, 'kpi_target': 7639292.705078125, 'is_bonus': False},
    {'role_code': 'commercial_rm_trade', 'role_name': 'COMMERCIAL RM- TRADE', 'kpi_order': 10, 'kpi_code': 'other_bancassurance_premiums', 'mapping_category': 'Group Synergies (23.0%)', 'kpi_weight': 0.03, 'kpi_target': 7639292.705078125, 'is_bonus': False},
    {'role_code': 'commercial_rm_trade', 'role_name': 'COMMERCIAL RM- TRADE', 'kpi_order': 11, 'kpi_code': 'portfolo_nps', 'mapping_category': 'Portfolio Management (15.0%)', 'kpi_weight': 0.05, 'kpi_target': 0.6, 'is_bonus': False},
    {'role_code': 'commercial_rm_trade', 'role_name': 'COMMERCIAL RM- TRADE', 'kpi_order': 12, 'kpi_code': 'deposits_energy_water', 'mapping_category': 'Portfolio Management (15.0%)', 'kpi_weight': 0.04, 'kpi_target': 2370979678.1400003, 'is_bonus': False},
    {'role_code': 'commercial_rm_trade', 'role_name': 'COMMERCIAL RM- TRADE', 'kpi_order': 13, 'kpi_code': 'deposits_portfolio', 'mapping_category': 'Portfolio Management (15.0%)', 'kpi_weight': 0.06, 'kpi_target': 285804667.04999995, 'is_bonus': False},
    {'role_code': 'commercial_rm_trade', 'role_name': 'COMMERCIAL RM- TRADE', 'kpi_order': 14, 'kpi_code': 'business_banking_training', 'mapping_category': 'Staff Engagement (7.0%)', 'kpi_weight': 0.05, 'kpi_target': 48.0, 'is_bonus': False},
    {'role_code': 'commercial_rm_trade', 'role_name': 'COMMERCIAL RM- TRADE', 'kpi_order': 15, 'kpi_code': 'business_banking_leave_magement', 'mapping_category': 'Staff Engagement (7.0%)', 'kpi_weight': 0.02, 'kpi_target': 1.0, 'is_bonus': False},
    {'role_code': 'commercial_rm_trade', 'role_name': 'COMMERCIAL RM- TRADE', 'kpi_order': 16, 'kpi_code': 'business_banking_par', 'mapping_category': 'Bonus Points (2.5%)', 'kpi_weight': 0.025, 'kpi_target': 0.025, 'is_bonus': True},
]


def seed(apps, schema_editor):
    ScKpi = apps.get_model("staff_management", "ScKpi")
    ScRole = apps.get_model("staff_management", "ScRole")
    ScRoleKpiMapping = apps.get_model("staff_management", "ScRoleKpiMapping")

    if ScKpi.objects.exists() or ScRoleKpiMapping.objects.exists():
        print("\n  scorecard config: already present - left alone.")
        return

    for code, name in ROLES.items():
        ScRole.objects.get_or_create(
            role_code=code,
            defaults={"role_name": name, "role_type": "IC", "is_active": True})

    inactive = 0
    for row in KPIS:
        row = dict(row)
        reason = row.pop("not_configured_reason", "")
        ScKpi.objects.create(
            kpi_calculation_mode="actual_over_target",
            kpi_rating_type="prorate",
            score_cap="1.20",
            is_active=not reason,
            not_configured_reason=reason,
            **row)
        if reason:
            inactive += 1

    start, end = date(YEAR, 1, 1), date(YEAR, 12, 31)
    for row in MAPPINGS:
        row = dict(row)
        row.pop("role_name", None)
        target = row.pop("kpi_target", None)
        ScRoleKpiMapping.objects.create(
            effective_from=start, effective_to=end,
            bonus_effective_from=start, bonus_effective_to=end,
            plan_category="p1", target_category="full_year", prorate=True,
            kpi_target=target,
            **row)

    print(f"\n  scorecard config: {len(ROLES)} roles, {len(KPIS)} KPIs "
          f"({inactive} awaiting a block), {len(MAPPINGS)} mappings.")


def unseed(apps, schema_editor):
    """Nothing to undo - removing a desk's configuration to reverse a seed
    would destroy tuning this migration never made."""


class Migration(migrations.Migration):

    dependencies = [
        ("staff_management", "0026_sc_kpi_allocation_column"),
    ]

    operations = [
        migrations.RunPython(seed, unseed),
    ]
