# Generated by Django 4.2.20 on 2026-10-09 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff_management', '0027_seed_rm_scorecards'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalScorecardSignoff',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('sales_code', models.CharField(db_index=True, max_length=255)),
                ('period', models.CharField(db_index=True, max_length=7)),
                ('card', models.JSONField(default=dict)),
                ('performance_score', models.FloatField(blank=True, null=True)),
                ('scored_lines', models.PositiveSmallIntegerField(default=0)),
                ('pending_lines', models.PositiveSmallIntegerField(default=0)),
                ('signed_by_name', models.CharField(blank=True, default='', max_length=255)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('owner_comment', models.TextField(blank=True, default='')),
                ('manager_signed_by_name', models.CharField(blank=True, default='', max_length=255)),
                ('manager_signed_at', models.DateTimeField(blank=True, null=True)),
                ('manager_comment', models.TextField(blank=True, default='')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('manager_signed_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('signed_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Scorecard Sign-off',
                'verbose_name_plural': 'historical Scorecard Sign-offs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ScorecardSignoff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_code', models.CharField(db_index=True, max_length=255)),
                ('period', models.CharField(db_index=True, max_length=7)),
                ('card', models.JSONField(default=dict)),
                ('performance_score', models.FloatField(blank=True, null=True)),
                ('scored_lines', models.PositiveSmallIntegerField(default=0)),
                ('pending_lines', models.PositiveSmallIntegerField(default=0)),
                ('signed_by_name', models.CharField(blank=True, default='', max_length=255)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('owner_comment', models.TextField(blank=True, default='')),
                ('manager_signed_by_name', models.CharField(blank=True, default='', max_length=255)),
                ('manager_signed_at', models.DateTimeField(blank=True, null=True)),
                ('manager_comment', models.TextField(blank=True, default='')),
                ('manager_signed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scorecards_countersigned', to=settings.AUTH_USER_MODEL)),
                ('signed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scorecards_signed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Scorecard Sign-off',
                'verbose_name_plural': 'Scorecard Sign-offs',
                'db_table': 'sc_scorecard_signoffs',
                'indexes': [models.Index(fields=['period', 'sales_code'], name='sc_scorecar_period_3ff046_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='scorecardsignoff',
            constraint=models.UniqueConstraint(fields=('sales_code', 'period'), name='sc_unique_signoff_per_period'),
        ),
    ]
