# Generated by Django 4.2.20 on 2026-10-09 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_management', '0029_role_target_basis'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalscrolekpimapping',
            name='kpi_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='scrolekpimapping',
            name='kpi_description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
