"""Seed the back-office (non-sales) scorecards: 10 cards, their lines, weights.

Read out of ``2026_BO_Non_Sales_Scorecards - Q2 with_updated_targets.xlsb`` by
``manage.py extract_bo_scorecards``, cross-checked against
``2026_BO_Actual_Template.xlsx``, and recorded in
``docs/bo-scorecard-kpi-map.csv``. The analysis is in
``docs/bo-scorecard-readiness.md``.

Unlike the RM workbook, this one STATES which actuals sheet each line reads, so
there is no calibration pass behind any of this and nothing is seeded inactive
for want of a block. 16 KPI(s) ARE seeded inactive, for a different and
narrower reason: the card names a sheet the actuals template does not have, or
names none at all. Those are listed with what the card claims, because the
question belongs with the desk rather than in a guess.

A KPI is keyed on its FEED, because the feed is the identity of the figure.
Keying on the measure split NPS into two codes over a trailing disambiguator
and split KYC over a typo on one card, while lumping three different
account-opening measures together. [   {   'kpi_code': 'bo_account_errors',
        'kpi_name': 'Account Errors',
        'kpi_description': 'Keep errors under 5 %',
        'actuals_sheet': 'Account_Errors',
        'not_configured_reason': 'names the sheet Account_Errors, which the actuals template does '
                                 'not have. Trx_Errors and RBO_Account_Errors both exist and '
                                 'either could be meant, so neither is assumed.'},
    {   'kpi_code': 'bo_account_opening_bb',
        'kpi_name': 'Account Opening',
        'kpi_description': 'BB AO TAT of 1 Day',
        'actuals_sheet': 'Account_Opening_BB',
        'not_configured_reason': ''},
    {   'kpi_code': 'bo_account_opening_pb',
        'kpi_name': 'Account Opening',
        'kpi_description': 'PB AO TAT OF 1 Day',
        'actuals_sheet': 'Account_Opening_PB',
        'not_configured_reason': ''},
    {   'kpi_code': 'bo_account_opening_sme',
        'kpi_name': 'Account Opening TAT',
        'kpi_description': 'SME AO TAT of 5days',
        'actuals_sheet': 'Account_Opening_sme',
        'not_configured_reason': 'names Account_Opening_sme. The template has PB, BB and UB '
                                 'account-opening sheets and no SME one.'},
    {   'kpi_code': 'bo_account_opening_ub',
        'kpi_name': 'ULTIMATE TAT',
        'kpi_description': 'AO TAT of 1 day on accounts opened by Ultimate RMs only',
        'actuals_sheet': 'Account_Opening_UB',
        'not_configured_reason': ''},
    {   'kpi_code': 'bo_active_customers',
        'kpi_name': 'Active Clients',
        'kpi_description': 'Active Customers - Two Months (Branch Active Customers Score)',
        'actuals_sheet': 'Active_Customers',
        'not_configured_reason': ''},
    {   'kpi_code': 'bo_bbm_financials',
        'kpi_name': 'BBM Financials',
        'kpi_description': 'Full branch financials',
        'actuals_sheet': 'BBM_Financials',
        'not_configured_reason': 'names BBM_Financials, which the template does not have. The '
                                 "branch manager's financials are not one of the 37 feeds."},
    {   'kpi_code': 'bo_branch_audit_branch_audit',
        'kpi_name': 'Branch Audit',
        'kpi_description': 'Annual audit score of 1.65',
        'actuals_sheet': 'Branch_Audit',
        'not_configured_reason': ''},
    {   'kpi_code': 'bo_branch_audit_cash_management',
        'kpi_name': 'Cash Management',
        'kpi_description': 'Accuracy of cash repatriated ..Nill CBK fines',
        'actuals_sheet': 'Branch_Audit',
        'not_configured_reason': ''},
    {   'kpi_code': 'bo_branch_audit_compliance',
        'kpi_name': 'Branch Audit',
        'kpi_description': 'Annual Compliance score of 90% and above',
        'actuals_sheet': 'Branch_Audit_Compliance',
        'not_configured_reason': ''},
    {   'kpi_code': 'bo_branch_audit_resolution',
        'kpi_name': 'Branch Audit',
        'kpi_description': 'Resolve 85% of Repeat finding',
        'actuals_sheet': 'Branch_Audit_Resolution',
        'not_configured_reason': ''},
    {   'kpi_code': 'bo_branch_loan_tat',
        'kpi_name': 'TAT (Loan)',
        'kpi_description': 'As per SLA of the different products',
        'actuals_sheet': 'Branch_Loan_TAT',
        'not_configured_reason': ''},
    {   'kpi_code': 'bo_branch_rtgs',
        'kpi_name': 'Digital Onboarding',
        'kpi_description': '80% of RTGS transactions to be online',
        'actuals_sheet': 'Branch_RTGS',
        'not_configured_reason': ''},
    {   'kpi_code': 'bo_casa',
        'kpi_name': 'Account Opening',
        'kpi_description': 'Open 4 funded accounts - Focus',
        'actuals_sheet': 'CASA',
        'not_configured_reason': ''},
    {   'kpi_code': 'bo_cash_management',
        'kpi_name': 'Cash Management',
        'kpi_description': 'Accuracy of cash repatriated ..Nill CBK fines',
        'actuals_sheet': 'Cash_management',
        'not_configured_reason': ''},
    {   'kpi_code': 'bo_cost',
        'kpi_name': 'Cost',
        'kpi_description': 'Reduce cost by 10%',
        'actuals_sheet': 'Cost',
        'not_configured_reason': 'names Cost, which the template does not have. There is no '
                                 'operating-cost data anywhere in this warehouse, so this cannot '
                                 'come from a feed as things stand.'},
    {   'kpi_code': 'bo_crm',
        'kpi_name': 'CRM',
        'kpi_description': '100 Complaints logged MOM',
        'actuals_sheet': 'CRM',
        'not_configured_reason': ''},
    {   'kpi_code': 'bo_customer_feedback_achieve_3_diaspora_banking_client_co',
        'kpi_name': 'Customer Feedback',
        'kpi_description': 'Achieve 3 Diaspora Banking client compliments',
        'actuals_sheet': '',
        'not_configured_reason': 'names no feed at all on the card, so there is nothing to read it '
                                 'from. It is a return somebody keeps rather than a warehouse '
                                 'figure.'},
    {   'kpi_code': 'bo_customer_feedback_achieve_3_ultimate_banking_client_co',
        'kpi_name': 'Customer Feedback',
        'kpi_description': 'Achieve 3 Ultimate Banking client compliments',
        'actuals_sheet': '',
        'not_configured_reason': 'names no feed at all on the card, so there is nothing to read it '
                                 'from. It is a return somebody keeps rather than a warehouse '
                                 'figure.'},
    {   'kpi_code': 'bo_customer_feedback_achieve_5_client_compliments',
        'kpi_name': 'Customer feedback',
        'kpi_description': 'Achieve 5 client compliments',
        'actuals_sheet': '',
        'not_configured_reason': 'names no feed at all on the card, so there is nothing to read it '
                                 'from. It is a return somebody keeps rather than a warehouse '
                                 'figure.'},
    {   'kpi_code': 'bo_customer_feedback_nil_client_complaints',
        'kpi_name': 'Customer feedback',
        'kpi_description': 'Nil client complaints',
        'actuals_sheet': '',
        'not_configured_reason': 'names no feed at all on the card, so there is nothing to read it '
                                 'from. It is a return somebody keeps rather than a warehouse '
                                 'figure.'},
    {   'kpi_code': 'bo_customer_journey_document_and_approve_the_customer_ser',
        'kpi_name': 'Customer Journey',
        'kpi_description': 'Document and approve the customer servicing model with all touch '
                           'points - including lending',
        'actuals_sheet': '',
        'not_configured_reason': 'names no feed at all on the card, so there is nothing to read it '
                                 'from. It is a return somebody keeps rather than a warehouse '
                                 'figure.'},
    {   'kpi_code': 'bo_deposit_growth',
        'kpi_name': 'Deposit',
        'kpi_description': 'Deposit of 1m per month',
        'actuals_sheet': 'Deposit_Growth',
        'not_configured_reason': 'names Deposit_Growth, which the template does not have - there '
                                 'is no deposits sheet on it at all.'},
    {   'kpi_code': 'bo_diaspora_audit',
        'kpi_name': 'Audit',
        'kpi_description': 'Department audit score',
        'actuals_sheet': 'Diaspora_Audit',
        'not_configured_reason': ''},
    {   'kpi_code': 'bo_digital_activation',
        'kpi_name': 'Digital Activation',
        'kpi_description': 'Digitally active Diaspora customers (Diaspora Digital Active Score)',
        'actuals_sheet': 'Digital_Activation',
        'not_configured_reason': ''},
    {   'kpi_code': 'bo_digital_customers',
        'kpi_name': 'Digital Onboarding',
        'kpi_description': 'Onboard 15 Digital customers monthly',
        'actuals_sheet': 'Digital_Customers',
        'not_configured_reason': ''},
    {   'kpi_code': 'bo_events',
        'kpi_name': 'Events',
        'kpi_description': 'Support 2 bi-annual events for Ultimate Banking',
        'actuals_sheet': 'Events',
        'not_configured_reason': ''},
    {   'kpi_code': 'bo_hfcb_properties_value',
        'kpi_name': 'Value of properties',
        'kpi_description': 'As per assigned targets',
        'actuals_sheet': 'HFCB_Properties_Value',
        'not_configured_reason': ''},
    {   'kpi_code': 'bo_hfcb_properties_volume',
        'kpi_name': 'Property Sales',
        'kpi_description': 'As per assigned team referral targets (2 per year)',
        'actuals_sheet': 'HFCB_Properties_Volume',
        'not_configured_reason': ''},
    {   'kpi_code': 'bo_kyc',
        'kpi_name': 'KYC',
        'kpi_description': 'KYC Update (Drive data cleanup through KYC)',
        'actuals_sheet': 'KYC',
        'not_configured_reason': ''},
    {   'kpi_code': 'bo_leave_management',
        'kpi_name': 'Leave management',
        'kpi_description': 'Ensure adherence to the leave policy',
        'actuals_sheet': 'Leave_management',
        'not_configured_reason': ''},
    {   'kpi_code': 'bo_new_customers',
        'kpi_name': 'New Diaspora customers',
        'kpi_description': '> 2 Active Products',
        'actuals_sheet': 'New_Customers',
        'not_configured_reason': ''},
    {   'kpi_code': 'bo_npl',
        'kpi_name': 'NPL Management',
        'kpi_description': 'Reduce NPL ratio (Retail) as per target',
        'actuals_sheet': 'NPL',
        'not_configured_reason': 'names NPL, which the template does not have. PL_Charge is what '
                                 'every other NPL line on these cards reads, but this one says '
                                 'something different and the difference is not explained.'},
    {   'kpi_code': 'bo_npl_reduce_p_l_provisions_from_diaspora',
        'kpi_name': 'NPL',
        'kpi_description': 'Reduce P&L provisions (From Diaspora)',
        'actuals_sheet': '',
        'not_configured_reason': 'names no feed at all on the card, so there is nothing to read it '
                                 'from. It is a return somebody keeps rather than a warehouse '
                                 'figure.'},
    {   'kpi_code': 'bo_nps',
        'kpi_name': 'NPS',
        'kpi_description': 'Achieve a net promoter score of 60%',
        'actuals_sheet': 'NPS',
        'not_configured_reason': ''},
    {   'kpi_code': 'bo_operation_lossess',
        'kpi_name': 'Operation Losses',
        'kpi_description': 'Nill operation losses/Cash differences',
        'actuals_sheet': 'Operation_Lossess',
        'not_configured_reason': ''},
    {   'kpi_code': 'bo_pl_charge',
        'kpi_name': 'NPL Management',
        'kpi_description': 'Reduce P&L provisions as per target',
        'actuals_sheet': 'PL_Charge',
        'not_configured_reason': ''},
    {   'kpi_code': 'bo_rbo_account_errors',
        'kpi_name': 'Returns',
        'kpi_description': 'Achieve less than 10% returns from governance on 35 rims actioned on.',
        'actuals_sheet': 'RBO_Account_Errors',
        'not_configured_reason': ''},
    {   'kpi_code': 'bo_rbo_monthly_summ',
        'kpi_name': 'Team Productivity',
        'kpi_description': 'Ensure 70% of Team scorecard is above 70%',
        'actuals_sheet': 'RBO_Monthly_Summ',
        'not_configured_reason': 'names RBO_Monthly_Summ, which is a summary sheet in the '
                                 'scorecard workbook rather than a feed in the actuals template.'},
    {   'kpi_code': 'bo_re_activation',
        'kpi_name': 'Dormancy',
        'kpi_description': 'Accounts activated (Branch Dormancy score)',
        'actuals_sheet': 'RE_activation',
        'not_configured_reason': ''},
    {   'kpi_code': 'bo_sales_productivity',
        'kpi_name': 'Team Productivity',
        'kpi_description': 'Ensure Direct Team (CSO, Teller) productivity scorecard is above 80%',
        'actuals_sheet': 'Sales_Productivity',
        'not_configured_reason': ''},
    {   'kpi_code': 'bo_tds_track_ub_term_deposit_renewals',
        'kpi_name': 'TDs',
        'kpi_description': 'Track UB Term Deposit renewals',
        'actuals_sheet': '',
        'not_configured_reason': 'names no feed at all on the card, so there is nothing to read it '
                                 'from. It is a return somebody keeps rather than a warehouse '
                                 'figure.'},
    {   'kpi_code': 'bo_term_deposits_track_diaspora_term_deposit_renewals_ret',
        'kpi_name': 'Term Deposits',
        'kpi_description': 'Track Diaspora Term Deposit renewals( Retain 80% of renewals)',
        'actuals_sheet': '',
        'not_configured_reason': 'names no feed at all on the card, so there is nothing to read it '
                                 'from. It is a return somebody keeps rather than a warehouse '
                                 'figure.'},
    {   'kpi_code': 'bo_tools_achieve_tat_of_1_day_for_mobile_banking_onboardi',
        'kpi_name': 'Tools',
        'kpi_description': 'Achieve TAT of 1 day for mobile banking onboarding.',
        'actuals_sheet': '',
        'not_configured_reason': 'names no feed at all on the card, so there is nothing to read it '
                                 'from. It is a return somebody keeps rather than a warehouse '
                                 'figure.'},
    {   'kpi_code': 'bo_training_hours',
        'kpi_name': 'Training hours',
        'kpi_description': 'Achieve training hours as per assigned target',
        'actuals_sheet': 'Training_hours',
        'not_configured_reason': ''},
    {   'kpi_code': 'bo_trx_errors',
        'kpi_name': 'ATM Management',
        'kpi_description': 'Retracted cash refunded in 24 hrs',
        'actuals_sheet': 'Trx_Errors',
        'not_configured_reason': ''},
    {   'kpi_code': 'bo_trx_productivity',
        'kpi_name': 'Productivity',
        'kpi_description': 'Teller Transactions as per Target',
        'actuals_sheet': 'Trx_Productivity',
        'not_configured_reason': ''},
    {   'kpi_code': 'bo_vic',
        'kpi_name': 'VIC Gross volume Written Premiums',
        'kpi_description': 'As per asigned team referral targets(4 per year)',
        'actuals_sheet': 'VIC',
        'not_configured_reason': ''},
    {   'kpi_code': 'bo_vic_life',
        'kpi_name': 'VIC Gross volume Written Premiums',
        'kpi_description': 'life policies as per assigned target',
        'actuals_sheet': 'VIC_Life',
        'not_configured_reason': ''},
    {   'kpi_code': 'bo_vic_non_life',
        'kpi_name': 'VIC Gross volume Written Premiums',
        'kpi_description': 'non-life as per assigned Target',
        'actuals_sheet': 'VIC_Non_Life',
        'not_configured_reason': ''},
    {   'kpi_code': 'bo_weighted_tat',
        'kpi_name': 'DIASPORA TAT',
        'kpi_description': 'Weigted TAT (SLA,Service standards, query response time)',
        'actuals_sheet': 'Weighted_TAT',
        'not_configured_reason': ''}] KPIs cover 132 card lines.

Weight, target and WORDING are per role and live on the mapping. Several roles
read one feed against different numbers - CASA is "open 4 funded accounts" on
one card, "6 per month" on another and "30 accounts a day" on a third - and
before ``ScRoleKpiMapping.kpi_description`` existed, whichever role was seeded
first put its wording on everybody else's card.

Every card's weights sum to exactly 1.000, which is the check that the
extraction is complete rather than partial.

Seed-only-if-empty, like 0020, 0023 and 0027: if somebody has already
configured these roles this does nothing, because a seed that overwrote a
desk's tuning would be worse than one that never ran.
"""

from datetime import date

from django.db import migrations

YEAR = 2026

#: Codes whose target is a THRESHOLD rather than an accrual, read off the
#: cards: the per-month figure and the YTD figure are the same number.
#: live_scorecard.FULL_YEAR_TARGETS carries the same list and is what stops
#: them being pro-rated.
THRESHOLDS = [   'bo_account_opening_bb',
    'bo_account_opening_pb',
    'bo_account_opening_sme',
    'bo_account_opening_ub',
    'bo_active_customers',
    'bo_branch_audit_branch_audit',
    'bo_branch_audit_cash_management',
    'bo_branch_audit_compliance',
    'bo_branch_audit_resolution',
    'bo_branch_loan_tat',
    'bo_branch_rtgs',
    'bo_cash_management',
    'bo_customer_feedback_nil_client_complaints',
    'bo_customer_journey_document_and_approve_the_customer_ser',
    'bo_diaspora_audit',
    'bo_digital_activation',
    'bo_npl_reduce_p_l_provisions_from_diaspora',
    'bo_nps',
    'bo_operation_lossess',
    'bo_rbo_account_errors',
    'bo_rbo_monthly_summ',
    'bo_re_activation',
    'bo_sales_productivity',
    'bo_tds_track_ub_term_deposit_renewals',
    'bo_tools_achieve_tat_of_1_day_for_mobile_banking_onboardi',
    'bo_trx_errors',
    'bo_trx_productivity',
    'bo_weighted_tat']

ROLES = {   'bo_bom': 'Branch Operations Manager',
    'bo_bom_cso': 'Branch Operations Manager (CSO branch)',
    'bo_cso': 'Customer Service Officer',
    'bo_cso_ub': 'Customer Service Officer - Ultimate Banking',
    'bo_csm_diaspora': 'Customer Service Manager - Diaspora Banking',
    'bo_cash_teller': 'Cash Teller',
    'bo_cash_centre_teller': 'Cash Centre Teller',
    'bo_teller': 'Teller',
    'bo_rbo': 'Retail Back Office Officer',
    'bo_tl_rbo': 'Team Leader - Retail Back Office'}

KPIS = [   {   'kpi_code': 'bo_account_errors',
        'kpi_name': 'Account Errors',
        'kpi_description': 'Keep errors under 5 %',
        'actuals_sheet': 'Account_Errors',
        'not_configured_reason': 'names the sheet Account_Errors, which the actuals template does '
                                 'not have. Trx_Errors and RBO_Account_Errors both exist and '
                                 'either could be meant, so neither is assumed.'},
    {   'kpi_code': 'bo_account_opening_bb',
        'kpi_name': 'Account Opening',
        'kpi_description': 'BB AO TAT of 1 Day',
        'actuals_sheet': 'Account_Opening_BB',
        'not_configured_reason': ''},
    {   'kpi_code': 'bo_account_opening_pb',
        'kpi_name': 'Account Opening',
        'kpi_description': 'PB AO TAT OF 1 Day',
        'actuals_sheet': 'Account_Opening_PB',
        'not_configured_reason': ''},
    {   'kpi_code': 'bo_account_opening_sme',
        'kpi_name': 'Account Opening TAT',
        'kpi_description': 'SME AO TAT of 5days',
        'actuals_sheet': 'Account_Opening_sme',
        'not_configured_reason': 'names Account_Opening_sme. The template has PB, BB and UB '
                                 'account-opening sheets and no SME one.'},
    {   'kpi_code': 'bo_account_opening_ub',
        'kpi_name': 'ULTIMATE TAT',
        'kpi_description': 'AO TAT of 1 day on accounts opened by Ultimate RMs only',
        'actuals_sheet': 'Account_Opening_UB',
        'not_configured_reason': ''},
    {   'kpi_code': 'bo_active_customers',
        'kpi_name': 'Active Clients',
        'kpi_description': 'Active Customers - Two Months (Branch Active Customers Score)',
        'actuals_sheet': 'Active_Customers',
        'not_configured_reason': ''},
    {   'kpi_code': 'bo_bbm_financials',
        'kpi_name': 'BBM Financials',
        'kpi_description': 'Full branch financials',
        'actuals_sheet': 'BBM_Financials',
        'not_configured_reason': 'names BBM_Financials, which the template does not have. The '
                                 "branch manager's financials are not one of the 37 feeds."},
    {   'kpi_code': 'bo_branch_audit_branch_audit',
        'kpi_name': 'Branch Audit',
        'kpi_description': 'Annual audit score of 1.65',
        'actuals_sheet': 'Branch_Audit',
        'not_configured_reason': ''},
    {   'kpi_code': 'bo_branch_audit_cash_management',
        'kpi_name': 'Cash Management',
        'kpi_description': 'Accuracy of cash repatriated ..Nill CBK fines',
        'actuals_sheet': 'Branch_Audit',
        'not_configured_reason': ''},
    {   'kpi_code': 'bo_branch_audit_compliance',
        'kpi_name': 'Branch Audit',
        'kpi_description': 'Annual Compliance score of 90% and above',
        'actuals_sheet': 'Branch_Audit_Compliance',
        'not_configured_reason': ''},
    {   'kpi_code': 'bo_branch_audit_resolution',
        'kpi_name': 'Branch Audit',
        'kpi_description': 'Resolve 85% of Repeat finding',
        'actuals_sheet': 'Branch_Audit_Resolution',
        'not_configured_reason': ''},
    {   'kpi_code': 'bo_branch_loan_tat',
        'kpi_name': 'TAT (Loan)',
        'kpi_description': 'As per SLA of the different products',
        'actuals_sheet': 'Branch_Loan_TAT',
        'not_configured_reason': ''},
    {   'kpi_code': 'bo_branch_rtgs',
        'kpi_name': 'Digital Onboarding',
        'kpi_description': '80% of RTGS transactions to be online',
        'actuals_sheet': 'Branch_RTGS',
        'not_configured_reason': ''},
    {   'kpi_code': 'bo_casa',
        'kpi_name': 'Account Opening',
        'kpi_description': 'Open 4 funded accounts - Focus',
        'actuals_sheet': 'CASA',
        'not_configured_reason': ''},
    {   'kpi_code': 'bo_cash_management',
        'kpi_name': 'Cash Management',
        'kpi_description': 'Accuracy of cash repatriated ..Nill CBK fines',
        'actuals_sheet': 'Cash_management',
        'not_configured_reason': ''},
    {   'kpi_code': 'bo_cost',
        'kpi_name': 'Cost',
        'kpi_description': 'Reduce cost by 10%',
        'actuals_sheet': 'Cost',
        'not_configured_reason': 'names Cost, which the template does not have. There is no '
                                 'operating-cost data anywhere in this warehouse, so this cannot '
                                 'come from a feed as things stand.'},
    {   'kpi_code': 'bo_crm',
        'kpi_name': 'CRM',
        'kpi_description': '100 Complaints logged MOM',
        'actuals_sheet': 'CRM',
        'not_configured_reason': ''},
    {   'kpi_code': 'bo_customer_feedback_achieve_3_diaspora_banking_client_co',
        'kpi_name': 'Customer Feedback',
        'kpi_description': 'Achieve 3 Diaspora Banking client compliments',
        'actuals_sheet': '',
        'not_configured_reason': 'names no feed at all on the card, so there is nothing to read it '
                                 'from. It is a return somebody keeps rather than a warehouse '
                                 'figure.'},
    {   'kpi_code': 'bo_customer_feedback_achieve_3_ultimate_banking_client_co',
        'kpi_name': 'Customer Feedback',
        'kpi_description': 'Achieve 3 Ultimate Banking client compliments',
        'actuals_sheet': '',
        'not_configured_reason': 'names no feed at all on the card, so there is nothing to read it '
                                 'from. It is a return somebody keeps rather than a warehouse '
                                 'figure.'},
    {   'kpi_code': 'bo_customer_feedback_achieve_5_client_compliments',
        'kpi_name': 'Customer feedback',
        'kpi_description': 'Achieve 5 client compliments',
        'actuals_sheet': '',
        'not_configured_reason': 'names no feed at all on the card, so there is nothing to read it '
                                 'from. It is a return somebody keeps rather than a warehouse '
                                 'figure.'},
    {   'kpi_code': 'bo_customer_feedback_nil_client_complaints',
        'kpi_name': 'Customer feedback',
        'kpi_description': 'Nil client complaints',
        'actuals_sheet': '',
        'not_configured_reason': 'names no feed at all on the card, so there is nothing to read it '
                                 'from. It is a return somebody keeps rather than a warehouse '
                                 'figure.'},
    {   'kpi_code': 'bo_customer_journey_document_and_approve_the_customer_ser',
        'kpi_name': 'Customer Journey',
        'kpi_description': 'Document and approve the customer servicing model with all touch '
                           'points - including lending',
        'actuals_sheet': '',
        'not_configured_reason': 'names no feed at all on the card, so there is nothing to read it '
                                 'from. It is a return somebody keeps rather than a warehouse '
                                 'figure.'},
    {   'kpi_code': 'bo_deposit_growth',
        'kpi_name': 'Deposit',
        'kpi_description': 'Deposit of 1m per month',
        'actuals_sheet': 'Deposit_Growth',
        'not_configured_reason': 'names Deposit_Growth, which the template does not have - there '
                                 'is no deposits sheet on it at all.'},
    {   'kpi_code': 'bo_diaspora_audit',
        'kpi_name': 'Audit',
        'kpi_description': 'Department audit score',
        'actuals_sheet': 'Diaspora_Audit',
        'not_configured_reason': ''},
    {   'kpi_code': 'bo_digital_activation',
        'kpi_name': 'Digital Activation',
        'kpi_description': 'Digitally active Diaspora customers (Diaspora Digital Active Score)',
        'actuals_sheet': 'Digital_Activation',
        'not_configured_reason': ''},
    {   'kpi_code': 'bo_digital_customers',
        'kpi_name': 'Digital Onboarding',
        'kpi_description': 'Onboard 15 Digital customers monthly',
        'actuals_sheet': 'Digital_Customers',
        'not_configured_reason': ''},
    {   'kpi_code': 'bo_events',
        'kpi_name': 'Events',
        'kpi_description': 'Support 2 bi-annual events for Ultimate Banking',
        'actuals_sheet': 'Events',
        'not_configured_reason': ''},
    {   'kpi_code': 'bo_hfcb_properties_value',
        'kpi_name': 'Value of properties',
        'kpi_description': 'As per assigned targets',
        'actuals_sheet': 'HFCB_Properties_Value',
        'not_configured_reason': ''},
    {   'kpi_code': 'bo_hfcb_properties_volume',
        'kpi_name': 'Property Sales',
        'kpi_description': 'As per assigned team referral targets (2 per year)',
        'actuals_sheet': 'HFCB_Properties_Volume',
        'not_configured_reason': ''},
    {   'kpi_code': 'bo_kyc',
        'kpi_name': 'KYC',
        'kpi_description': 'KYC Update (Drive data cleanup through KYC)',
        'actuals_sheet': 'KYC',
        'not_configured_reason': ''},
    {   'kpi_code': 'bo_leave_management',
        'kpi_name': 'Leave management',
        'kpi_description': 'Ensure adherence to the leave policy',
        'actuals_sheet': 'Leave_management',
        'not_configured_reason': ''},
    {   'kpi_code': 'bo_new_customers',
        'kpi_name': 'New Diaspora customers',
        'kpi_description': '> 2 Active Products',
        'actuals_sheet': 'New_Customers',
        'not_configured_reason': ''},
    {   'kpi_code': 'bo_npl',
        'kpi_name': 'NPL Management',
        'kpi_description': 'Reduce NPL ratio (Retail) as per target',
        'actuals_sheet': 'NPL',
        'not_configured_reason': 'names NPL, which the template does not have. PL_Charge is what '
                                 'every other NPL line on these cards reads, but this one says '
                                 'something different and the difference is not explained.'},
    {   'kpi_code': 'bo_npl_reduce_p_l_provisions_from_diaspora',
        'kpi_name': 'NPL',
        'kpi_description': 'Reduce P&L provisions (From Diaspora)',
        'actuals_sheet': '',
        'not_configured_reason': 'names no feed at all on the card, so there is nothing to read it '
                                 'from. It is a return somebody keeps rather than a warehouse '
                                 'figure.'},
    {   'kpi_code': 'bo_nps',
        'kpi_name': 'NPS',
        'kpi_description': 'Achieve a net promoter score of 60%',
        'actuals_sheet': 'NPS',
        'not_configured_reason': ''},
    {   'kpi_code': 'bo_operation_lossess',
        'kpi_name': 'Operation Losses',
        'kpi_description': 'Nill operation losses/Cash differences',
        'actuals_sheet': 'Operation_Lossess',
        'not_configured_reason': ''},
    {   'kpi_code': 'bo_pl_charge',
        'kpi_name': 'NPL Management',
        'kpi_description': 'Reduce P&L provisions as per target',
        'actuals_sheet': 'PL_Charge',
        'not_configured_reason': ''},
    {   'kpi_code': 'bo_rbo_account_errors',
        'kpi_name': 'Returns',
        'kpi_description': 'Achieve less than 10% returns from governance on 35 rims actioned on.',
        'actuals_sheet': 'RBO_Account_Errors',
        'not_configured_reason': ''},
    {   'kpi_code': 'bo_rbo_monthly_summ',
        'kpi_name': 'Team Productivity',
        'kpi_description': 'Ensure 70% of Team scorecard is above 70%',
        'actuals_sheet': 'RBO_Monthly_Summ',
        'not_configured_reason': 'names RBO_Monthly_Summ, which is a summary sheet in the '
                                 'scorecard workbook rather than a feed in the actuals template.'},
    {   'kpi_code': 'bo_re_activation',
        'kpi_name': 'Dormancy',
        'kpi_description': 'Accounts activated (Branch Dormancy score)',
        'actuals_sheet': 'RE_activation',
        'not_configured_reason': ''},
    {   'kpi_code': 'bo_sales_productivity',
        'kpi_name': 'Team Productivity',
        'kpi_description': 'Ensure Direct Team (CSO, Teller) productivity scorecard is above 80%',
        'actuals_sheet': 'Sales_Productivity',
        'not_configured_reason': ''},
    {   'kpi_code': 'bo_tds_track_ub_term_deposit_renewals',
        'kpi_name': 'TDs',
        'kpi_description': 'Track UB Term Deposit renewals',
        'actuals_sheet': '',
        'not_configured_reason': 'names no feed at all on the card, so there is nothing to read it '
                                 'from. It is a return somebody keeps rather than a warehouse '
                                 'figure.'},
    {   'kpi_code': 'bo_term_deposits_track_diaspora_term_deposit_renewals_ret',
        'kpi_name': 'Term Deposits',
        'kpi_description': 'Track Diaspora Term Deposit renewals( Retain 80% of renewals)',
        'actuals_sheet': '',
        'not_configured_reason': 'names no feed at all on the card, so there is nothing to read it '
                                 'from. It is a return somebody keeps rather than a warehouse '
                                 'figure.'},
    {   'kpi_code': 'bo_tools_achieve_tat_of_1_day_for_mobile_banking_onboardi',
        'kpi_name': 'Tools',
        'kpi_description': 'Achieve TAT of 1 day for mobile banking onboarding.',
        'actuals_sheet': '',
        'not_configured_reason': 'names no feed at all on the card, so there is nothing to read it '
                                 'from. It is a return somebody keeps rather than a warehouse '
                                 'figure.'},
    {   'kpi_code': 'bo_training_hours',
        'kpi_name': 'Training hours',
        'kpi_description': 'Achieve training hours as per assigned target',
        'actuals_sheet': 'Training_hours',
        'not_configured_reason': ''},
    {   'kpi_code': 'bo_trx_errors',
        'kpi_name': 'ATM Management',
        'kpi_description': 'Retracted cash refunded in 24 hrs',
        'actuals_sheet': 'Trx_Errors',
        'not_configured_reason': ''},
    {   'kpi_code': 'bo_trx_productivity',
        'kpi_name': 'Productivity',
        'kpi_description': 'Teller Transactions as per Target',
        'actuals_sheet': 'Trx_Productivity',
        'not_configured_reason': ''},
    {   'kpi_code': 'bo_vic',
        'kpi_name': 'VIC Gross volume Written Premiums',
        'kpi_description': 'As per asigned team referral targets(4 per year)',
        'actuals_sheet': 'VIC',
        'not_configured_reason': ''},
    {   'kpi_code': 'bo_vic_life',
        'kpi_name': 'VIC Gross volume Written Premiums',
        'kpi_description': 'life policies as per assigned target',
        'actuals_sheet': 'VIC_Life',
        'not_configured_reason': ''},
    {   'kpi_code': 'bo_vic_non_life',
        'kpi_name': 'VIC Gross volume Written Premiums',
        'kpi_description': 'non-life as per assigned Target',
        'actuals_sheet': 'VIC_Non_Life',
        'not_configured_reason': ''},
    {   'kpi_code': 'bo_weighted_tat',
        'kpi_name': 'DIASPORA TAT',
        'kpi_description': 'Weigted TAT (SLA,Service standards, query response time)',
        'actuals_sheet': 'Weighted_TAT',
        'not_configured_reason': ''}]

MAPPINGS = [   {   'role_code': 'bo_bom',
        'kpi_code': 'bo_active_customers',
        'kpi_order': 1,
        'mapping_category': 'Financials 24.0%',
        'kpi_weight': 0.08,
        'kpi_target': 1.0,
        'kpi_description': 'Active Customers - Two Months (Branch Active Customers Score)'},
    {   'role_code': 'bo_bom',
        'kpi_code': 'bo_pl_charge',
        'kpi_order': 2,
        'mapping_category': 'Financials 24.0%',
        'kpi_weight': 0.08,
        'kpi_target': -434037.47640330624,
        'kpi_description': 'Reduce P&L provisions as per target'},
    {   'role_code': 'bo_bom',
        'kpi_code': 'bo_re_activation',
        'kpi_order': 3,
        'mapping_category': 'Financials 24.0%',
        'kpi_weight': 0.08,
        'kpi_target': 0.3840654055787111,
        'kpi_description': 'Accounts activated (Branch Dormancy score)'},
    {   'role_code': 'bo_bom',
        'kpi_code': 'bo_nps',
        'kpi_order': 4,
        'mapping_category': 'Customer Experience 25.0%',
        'kpi_weight': 0.1,
        'kpi_target': 0.6,
        'kpi_description': 'Achieve a net promoter score of 60%'},
    {   'role_code': 'bo_bom',
        'kpi_code': 'bo_account_opening_pb',
        'kpi_order': 5,
        'mapping_category': 'Customer Experience 25.0%',
        'kpi_weight': 0.05,
        'kpi_target': 1.0,
        'kpi_description': 'PB AO TAT OF 1 Day'},
    {   'role_code': 'bo_bom',
        'kpi_code': 'bo_account_opening_bb',
        'kpi_order': 6,
        'mapping_category': 'Customer Experience 25.0%',
        'kpi_weight': 0.05,
        'kpi_target': 1.0,
        'kpi_description': 'BB AO TAT of 1 day'},
    {   'role_code': 'bo_bom',
        'kpi_code': 'bo_branch_loan_tat',
        'kpi_order': 7,
        'mapping_category': 'Customer Experience 25.0%',
        'kpi_weight': 0.05,
        'kpi_target': 2.0,
        'kpi_description': 'As per SLA of the different products'},
    {   'role_code': 'bo_bom',
        'kpi_code': 'bo_hfcb_properties_volume',
        'kpi_order': 8,
        'mapping_category': 'Group Synergies 5.0%',
        'kpi_weight': 0.025,
        'kpi_target': 2.0,
        'kpi_description': 'As per assigned team referral targets (2 per year)'},
    {   'role_code': 'bo_bom',
        'kpi_code': 'bo_vic',
        'kpi_order': 9,
        'mapping_category': 'Group Synergies 5.0%',
        'kpi_weight': 0.025,
        'kpi_target': 4.0,
        'kpi_description': 'As per asigned team referral targets (4 per year)'},
    {   'role_code': 'bo_bom',
        'kpi_code': 'bo_branch_audit_branch_audit',
        'kpi_order': 10,
        'mapping_category': 'Operational Excellence 31.0%',
        'kpi_weight': 0.08,
        'kpi_target': 1.0,
        'kpi_description': 'Annual audit score of 1.65'},
    {   'role_code': 'bo_bom',
        'kpi_code': 'bo_branch_audit_resolution',
        'kpi_order': 11,
        'mapping_category': 'Operational Excellence 31.0%',
        'kpi_weight': 0.08,
        'kpi_target': 0.85,
        'kpi_description': 'Achieve 85% audit implementation score'},
    {   'role_code': 'bo_bom',
        'kpi_code': 'bo_branch_audit_compliance',
        'kpi_order': 12,
        'mapping_category': 'Group Synergies 15.0%',
        'kpi_weight': 0.05,
        'kpi_target': 0.9,
        'kpi_description': 'Annual Compliance score of 90% and above'},
    {   'role_code': 'bo_bom',
        'kpi_code': 'bo_operation_lossess',
        'kpi_order': 13,
        'mapping_category': 'Group Synergies 15.0%',
        'kpi_weight': 0.1,
        'kpi_target': 0.0,
        'kpi_description': 'Nil operation losses / Frauds'},
    {   'role_code': 'bo_bom',
        'kpi_code': 'bo_sales_productivity',
        'kpi_order': 14,
        'mapping_category': 'Staff Engagement 15.0%',
        'kpi_weight': 0.1,
        'kpi_target': 0.8,
        'kpi_description': 'Ensure Direct Team (CSO, Teller) productivity scorecard is above 80%'},
    {   'role_code': 'bo_bom',
        'kpi_code': 'bo_training_hours',
        'kpi_order': 15,
        'mapping_category': 'Staff Engagement 15.0%',
        'kpi_weight': 0.05,
        'kpi_target': 48.0,
        'kpi_description': 'Achieve training hours as per assigned target'},
    {   'role_code': 'bo_bom_cso',
        'kpi_code': 'bo_bbm_financials',
        'kpi_order': 1,
        'mapping_category': '',
        'kpi_weight': 0.15,
        'kpi_target': 12.0,
        'kpi_description': 'Full branch financials'},
    {   'role_code': 'bo_bom_cso',
        'kpi_code': 'bo_nps',
        'kpi_order': 2,
        'mapping_category': 'Customer (30%) 30.0%',
        'kpi_weight': 0.1,
        'kpi_target': 0.6,
        'kpi_description': 'Achieve a net promoter score of 60%'},
    {   'role_code': 'bo_bom_cso',
        'kpi_code': 'bo_account_errors',
        'kpi_order': 3,
        'mapping_category': 'Customer (30%) 30.0%',
        'kpi_weight': 0.1,
        'kpi_target': None,
        'kpi_description': 'Keep errors under 5 %'},
    {   'role_code': 'bo_bom_cso',
        'kpi_code': 'bo_crm',
        'kpi_order': 4,
        'mapping_category': 'Customer (30%) 30.0%',
        'kpi_weight': 0.05,
        'kpi_target': 7200.0,
        'kpi_description': '100 Complaints logged MOM'},
    {   'role_code': 'bo_bom_cso',
        'kpi_code': 'bo_kyc',
        'kpi_order': 5,
        'mapping_category': 'Customer (30%) 30.0%',
        'kpi_weight': 0.05,
        'kpi_target': 2160.0,
        'kpi_description': 'KYC Update(Drive data cleanup through KYC)'},
    {   'role_code': 'bo_bom_cso',
        'kpi_code': 'bo_branch_audit_branch_audit',
        'kpi_order': 6,
        'mapping_category': 'Process & Controls 45.0%',
        'kpi_weight': 0.15,
        'kpi_target': 1.0,
        'kpi_description': 'Achieve above required audit performance'},
    {   'role_code': 'bo_bom_cso',
        'kpi_code': 'bo_re_activation',
        'kpi_order': 7,
        'mapping_category': 'Process & Controls 45.0%',
        'kpi_weight': 0.1,
        'kpi_target': 1.0,
        'kpi_description': 'Re-activation of innactive customers as per target'},
    {   'role_code': 'bo_bom_cso',
        'kpi_code': 'bo_operation_lossess',
        'kpi_order': 8,
        'mapping_category': 'Process & Controls 45.0%',
        'kpi_weight': 0.1,
        'kpi_target': 0.0,
        'kpi_description': 'Nill operation losses'},
    {   'role_code': 'bo_bom_cso',
        'kpi_code': 'bo_cost',
        'kpi_order': 9,
        'mapping_category': 'Process & Controls 45.0%',
        'kpi_weight': 0.1,
        'kpi_target': None,
        'kpi_description': 'Reduce cost by 10%'},
    {   'role_code': 'bo_bom_cso',
        'kpi_code': 'bo_leave_management',
        'kpi_order': 10,
        'mapping_category': 'Organization Capacity (People) (10%) 10.0%',
        'kpi_weight': 0.05,
        'kpi_target': 6.0,
        'kpi_description': 'Ensure adherence to the leave policy - develop annual leave schedule, '
                           'ensure staff go on leave as per the schedule and that no staff crosses '
                           'over with more than 5 days.'},
    {   'role_code': 'bo_bom_cso',
        'kpi_code': 'bo_training_hours',
        'kpi_order': 11,
        'mapping_category': 'Organization Capacity (People) (10%) 10.0%',
        'kpi_weight': 0.05,
        'kpi_target': 288.0,
        'kpi_description': 'Ensure your teams achieve 48 training hours'},
    {   'role_code': 'bo_cso',
        'kpi_code': 'bo_digital_customers',
        'kpi_order': 1,
        'mapping_category': 'Financials 20.0%',
        'kpi_weight': 0.1,
        'kpi_target': 96.0,
        'kpi_description': 'Onboard 15 Digital customers monthly'},
    {   'role_code': 'bo_cso',
        'kpi_code': 'bo_re_activation',
        'kpi_order': 2,
        'mapping_category': 'Financials 20.0%',
        'kpi_weight': 0.1,
        'kpi_target': 0.22342137845645896,
        'kpi_description': 'Accounts activated must have a tool'},
    {   'role_code': 'bo_cso',
        'kpi_code': 'bo_crm',
        'kpi_order': 3,
        'mapping_category': 'Customer Experience 42.0%',
        'kpi_weight': 0.1,
        'kpi_target': 1200.0,
        'kpi_description': '100 Complaints logged MOM'},
    {   'role_code': 'bo_cso',
        'kpi_code': 'bo_nps',
        'kpi_order': 4,
        'mapping_category': 'Customer Experience 42.0%',
        'kpi_weight': 0.1,
        'kpi_target': 0.6,
        'kpi_description': 'Achieve a net promoter score of 60%'},
    {   'role_code': 'bo_cso',
        'kpi_code': 'bo_kyc',
        'kpi_order': 5,
        'mapping_category': 'Customer Experience 42.0%',
        'kpi_weight': 0.1,
        'kpi_target': 360.0,
        'kpi_description': 'KYC Update (Drive data cleanup through KYC)'},
    {   'role_code': 'bo_cso',
        'kpi_code': 'bo_account_opening_pb',
        'kpi_order': 6,
        'mapping_category': 'Customer Experience 42.0%',
        'kpi_weight': 0.06,
        'kpi_target': 1.0,
        'kpi_description': 'PB AO TAT OF 1 Day'},
    {   'role_code': 'bo_cso',
        'kpi_code': 'bo_account_opening_bb',
        'kpi_order': 7,
        'mapping_category': 'Customer Experience 42.0%',
        'kpi_weight': 0.06,
        'kpi_target': 1.0,
        'kpi_description': 'BB AO TAT of 1 Day'},
    {   'role_code': 'bo_cso',
        'kpi_code': 'bo_casa',
        'kpi_order': 8,
        'mapping_category': 'Group Synergies 15.0%',
        'kpi_weight': 0.1,
        'kpi_target': 48.0,
        'kpi_description': 'Open 4 funded accounts - Focus'},
    {   'role_code': 'bo_cso',
        'kpi_code': 'bo_hfcb_properties_volume',
        'kpi_order': 9,
        'mapping_category': 'Group Synergies 15.0%',
        'kpi_weight': 0.025,
        'kpi_target': 24.0,
        'kpi_description': 'As per assigned team referral targets (2 per year)'},
    {   'role_code': 'bo_cso',
        'kpi_code': 'bo_vic',
        'kpi_order': 10,
        'mapping_category': 'Group Synergies 15.0%',
        'kpi_weight': 0.025,
        'kpi_target': 48.0,
        'kpi_description': 'As per asigned team referral targets(4 per year)'},
    {   'role_code': 'bo_cso',
        'kpi_code': 'bo_branch_audit_branch_audit',
        'kpi_order': 11,
        'mapping_category': 'Operational Excellence 18.0%',
        'kpi_weight': 0.1,
        'kpi_target': 1.0,
        'kpi_description': 'Annual audit score of 1.65'},
    {   'role_code': 'bo_cso',
        'kpi_code': 'bo_branch_audit_resolution',
        'kpi_order': 12,
        'mapping_category': 'Operational Excellence 18.0%',
        'kpi_weight': 0.08,
        'kpi_target': 0.85,
        'kpi_description': 'Resolve 85% of Repeat finding'},
    {   'role_code': 'bo_cso',
        'kpi_code': 'bo_training_hours',
        'kpi_order': 13,
        'mapping_category': 'Staff Engagement 5.0%',
        'kpi_weight': 0.05,
        'kpi_target': 576.0,
        'kpi_description': 'Achieve training hours as per assigned target'},
    {   'role_code': 'bo_cso_ub',
        'kpi_code': 'bo_active_customers',
        'kpi_order': 1,
        'mapping_category': 'Financials 27.0%',
        'kpi_weight': 0.05,
        'kpi_target': 1.0,
        'kpi_description': 'Active ultimate customers (1month) (Ultimate Active Customer Score)'},
    {   'role_code': 'bo_cso_ub',
        'kpi_code': 'bo_digital_activation',
        'kpi_order': 2,
        'mapping_category': 'Financials 27.0%',
        'kpi_weight': 0.05,
        'kpi_target': 1.0,
        'kpi_description': 'Digitally active Ultimate customers (Ultimate Digital Active Score)'},
    {   'role_code': 'bo_cso_ub',
        'kpi_code': 'bo_casa',
        'kpi_order': 3,
        'mapping_category': 'Financials 27.0%',
        'kpi_weight': 0.1,
        'kpi_target': 72.0,
        'kpi_description': 'Open 6 funded accounts- per month (Average from Ultimate RMs)'},
    {   'role_code': 'bo_cso_ub',
        'kpi_code': 'bo_re_activation',
        'kpi_order': 4,
        'mapping_category': 'Financials 27.0%',
        'kpi_weight': 0.07,
        'kpi_target': 0.13776237623762377,
        'kpi_description': 'Accounts activated (Ultimate Dormancy Score)'},
    {   'role_code': 'bo_cso_ub',
        'kpi_code': 'bo_account_opening_ub',
        'kpi_order': 5,
        'mapping_category': 'Customer Experience 51.0%',
        'kpi_weight': 0.1,
        'kpi_target': 1.0,
        'kpi_description': 'AO TAT of 1 day on accounts opened by Ultimate RMs only'},
    {   'role_code': 'bo_cso_ub',
        'kpi_code': 'bo_crm',
        'kpi_order': 6,
        'mapping_category': 'Customer Experience 51.0%',
        'kpi_weight': 0.15,
        'kpi_target': 240.0,
        'kpi_description': '20 UB queries logged in CRM MOM'},
    {   'role_code': 'bo_cso_ub',
        'kpi_code': 'bo_nps',
        'kpi_order': 7,
        'mapping_category': 'Customer Experience 51.0%',
        'kpi_weight': 0.15,
        'kpi_target': 0.6,
        'kpi_description': 'Achieve a net promoter score of 60% (Segment)'},
    {   'role_code': 'bo_cso_ub',
        'kpi_code': 'bo_kyc',
        'kpi_order': 8,
        'mapping_category': 'Customer Experience 51.0%',
        'kpi_weight': 0.04,
        'kpi_target': 120.0,
        'kpi_description': 'KYC Update(Drive data cleanup through KYC)'},
    {   'role_code': 'bo_cso_ub',
        'kpi_code': 'bo_customer_feedback_achieve_3_ultimate_banking_client_co',
        'kpi_order': 9,
        'mapping_category': 'Customer Experience 51.0%',
        'kpi_weight': 0.03,
        'kpi_target': 36.0,
        'kpi_description': 'Achieve 3 Ultimate Banking client compliments'},
    {   'role_code': 'bo_cso_ub',
        'kpi_code': 'bo_rbo_account_errors',
        'kpi_order': 10,
        'mapping_category': 'Customer Experience 51.0%',
        'kpi_weight': 0.04,
        'kpi_target': None,
        'kpi_description': 'Keep errors under 5% for Ultimate RMs accs'},
    {   'role_code': 'bo_cso_ub',
        'kpi_code': 'bo_hfcb_properties_volume',
        'kpi_order': 11,
        'mapping_category': 'Group Synergies 10.0%',
        'kpi_weight': 0.05,
        'kpi_target': 24.0,
        'kpi_description': 'As per assigned team referral targets (2 per year)'},
    {   'role_code': 'bo_cso_ub',
        'kpi_code': 'bo_vic',
        'kpi_order': 12,
        'mapping_category': 'Group Synergies 10.0%',
        'kpi_weight': 0.05,
        'kpi_target': 48.0,
        'kpi_description': 'As per asigned team referral targets(4 per year)'},
    {   'role_code': 'bo_cso_ub',
        'kpi_code': 'bo_events',
        'kpi_order': 13,
        'mapping_category': 'Strategic Initiatives 7.0%',
        'kpi_weight': 0.04,
        'kpi_target': 24.0,
        'kpi_description': 'Support 2 bi-annual events for Ultimate Banking'},
    {   'role_code': 'bo_cso_ub',
        'kpi_code': 'bo_tds_track_ub_term_deposit_renewals',
        'kpi_order': 14,
        'mapping_category': 'Strategic Initiatives 7.0%',
        'kpi_weight': 0.03,
        'kpi_target': 1.0,
        'kpi_description': 'Track UB Term Deposit renewals'},
    {   'role_code': 'bo_cso_ub',
        'kpi_code': 'bo_training_hours',
        'kpi_order': 15,
        'mapping_category': 'Staff Engagement 5.0%',
        'kpi_weight': 0.05,
        'kpi_target': 576.0,
        'kpi_description': 'Achieve training hours as per assigned target'},
    {   'role_code': 'bo_csm_diaspora',
        'kpi_code': 'bo_new_customers',
        'kpi_order': 1,
        'mapping_category': 'Financials 15.0%',
        'kpi_weight': 0.025,
        'kpi_target': 60.0,
        'kpi_description': '> 2 Active Products'},
    {   'role_code': 'bo_csm_diaspora',
        'kpi_code': 'bo_digital_activation',
        'kpi_order': 2,
        'mapping_category': 'Financials 15.0%',
        'kpi_weight': 0.025,
        'kpi_target': 1.0,
        'kpi_description': 'Digitally active Diaspora customers (Diaspora Digital Active Score)'},
    {   'role_code': 'bo_csm_diaspora',
        'kpi_code': 'bo_term_deposits_track_diaspora_term_deposit_renewals_ret',
        'kpi_order': 3,
        'mapping_category': 'Financials 15.0%',
        'kpi_weight': 0.05,
        'kpi_target': 12.0,
        'kpi_description': 'Track Diaspora Term Deposit renewals( Retain 80% of renewals)'},
    {   'role_code': 'bo_csm_diaspora',
        'kpi_code': 'bo_npl_reduce_p_l_provisions_from_diaspora',
        'kpi_order': 4,
        'mapping_category': 'Financials 15.0%',
        'kpi_weight': 0.05,
        'kpi_target': 1.0,
        'kpi_description': 'Reduce P&L provisions (From Diaspora)'},
    {   'role_code': 'bo_csm_diaspora',
        'kpi_code': 'bo_weighted_tat',
        'kpi_order': 5,
        'mapping_category': 'Customer Experience 60.0%',
        'kpi_weight': 0.1,
        'kpi_target': 1.0,
        'kpi_description': 'Weigted TAT (SLA,Service standards, query response time)'},
    {   'role_code': 'bo_csm_diaspora',
        'kpi_code': 'bo_crm',
        'kpi_order': 6,
        'mapping_category': 'Customer Experience 60.0%',
        'kpi_weight': 0.2,
        'kpi_target': 600.0,
        'kpi_description': '50 DB queries logged in CRM MOM'},
    {   'role_code': 'bo_csm_diaspora',
        'kpi_code': 'bo_nps',
        'kpi_order': 7,
        'mapping_category': 'Customer Experience 60.0%',
        'kpi_weight': 0.15,
        'kpi_target': 0.6,
        'kpi_description': 'Achieve a net promoter score of 60% (Segment)'},
    {   'role_code': 'bo_csm_diaspora',
        'kpi_code': 'bo_kyc',
        'kpi_order': 8,
        'mapping_category': 'Customer Experience 60.0%',
        'kpi_weight': 0.05,
        'kpi_target': 48.0,
        'kpi_description': 'KYC Update (Drive data cleanup through KYC)'},
    {   'role_code': 'bo_csm_diaspora',
        'kpi_code': 'bo_customer_journey_document_and_approve_the_customer_ser',
        'kpi_order': 9,
        'mapping_category': 'Customer Experience 60.0%',
        'kpi_weight': 0.05,
        'kpi_target': 1.0,
        'kpi_description': 'Document and approve the customer servicing model with all touch '
                           'points - including lending'},
    {   'role_code': 'bo_csm_diaspora',
        'kpi_code': 'bo_customer_feedback_achieve_3_diaspora_banking_client_co',
        'kpi_order': 10,
        'mapping_category': 'Customer Experience 60.0%',
        'kpi_weight': 0.05,
        'kpi_target': 36.0,
        'kpi_description': 'Achieve 3 Diaspora Banking client compliments'},
    {   'role_code': 'bo_csm_diaspora',
        'kpi_code': 'bo_hfcb_properties_volume',
        'kpi_order': 11,
        'mapping_category': 'Group Synergies 10.0%',
        'kpi_weight': 0.025,
        'kpi_target': 36.0,
        'kpi_description': 'As per assigned targets (3 per year)'},
    {   'role_code': 'bo_csm_diaspora',
        'kpi_code': 'bo_hfcb_properties_value',
        'kpi_order': 12,
        'mapping_category': 'Group Synergies 10.0%',
        'kpi_weight': 0.025,
        'kpi_target': 295200000.0,
        'kpi_description': 'As per assigned targets'},
    {   'role_code': 'bo_csm_diaspora',
        'kpi_code': 'bo_vic_life',
        'kpi_order': 13,
        'mapping_category': 'Group Synergies 10.0%',
        'kpi_weight': 0.025,
        'kpi_target': 48.0,
        'kpi_description': 'life policies as per assigned target'},
    {   'role_code': 'bo_csm_diaspora',
        'kpi_code': 'bo_vic_non_life',
        'kpi_order': 14,
        'mapping_category': 'Group Synergies 10.0%',
        'kpi_weight': 0.025,
        'kpi_target': 48.0,
        'kpi_description': 'non-life as per assigned Target'},
    {   'role_code': 'bo_csm_diaspora',
        'kpi_code': 'bo_events',
        'kpi_order': 15,
        'mapping_category': 'Operational Excellence 10.0%',
        'kpi_weight': 0.05,
        'kpi_target': 144.0,
        'kpi_description': 'Support monthly engagements for Diaspora Banking- Including '
                           'events,webinars & activations'},
    {   'role_code': 'bo_csm_diaspora',
        'kpi_code': 'bo_diaspora_audit',
        'kpi_order': 16,
        'mapping_category': 'Operational Excellence 10.0%',
        'kpi_weight': 0.05,
        'kpi_target': 1.65,
        'kpi_description': 'Department audit score'},
    {   'role_code': 'bo_csm_diaspora',
        'kpi_code': 'bo_training_hours',
        'kpi_order': 17,
        'mapping_category': 'Staff Engagement 5.0%',
        'kpi_weight': 0.05,
        'kpi_target': 576.0,
        'kpi_description': 'Achieve training hours as per assigned target'},
    {   'role_code': 'bo_cash_teller',
        'kpi_code': 'bo_casa',
        'kpi_order': 1,
        'mapping_category': 'Financials 15.0%',
        'kpi_weight': 0.075,
        'kpi_target': 48.0,
        'kpi_description': 'Open 4 funded accounts- Focus'},
    {   'role_code': 'bo_cash_teller',
        'kpi_code': 'bo_branch_rtgs',
        'kpi_order': 2,
        'mapping_category': 'Financials 15.0%',
        'kpi_weight': 0.075,
        'kpi_target': 0.8,
        'kpi_description': '80% of RTGS transactions to be online'},
    {   'role_code': 'bo_cash_teller',
        'kpi_code': 'bo_account_opening_pb',
        'kpi_order': 3,
        'mapping_category': 'Customer Experience 20.0%',
        'kpi_weight': 0.05,
        'kpi_target': 1.0,
        'kpi_description': 'PB AO TAT OF 1 Day'},
    {   'role_code': 'bo_cash_teller',
        'kpi_code': 'bo_account_opening_bb',
        'kpi_order': 4,
        'mapping_category': 'Customer Experience 20.0%',
        'kpi_weight': 0.05,
        'kpi_target': 1.0,
        'kpi_description': 'BB AO TAT OF 1 Day'},
    {   'role_code': 'bo_cash_teller',
        'kpi_code': 'bo_nps',
        'kpi_order': 5,
        'mapping_category': 'Customer Experience 20.0%',
        'kpi_weight': 0.1,
        'kpi_target': 0.6,
        'kpi_description': 'Achieve a net promoter score of above 60%'},
    {   'role_code': 'bo_cash_teller',
        'kpi_code': 'bo_hfcb_properties_volume',
        'kpi_order': 6,
        'mapping_category': 'Group Synergies 5.0%',
        'kpi_weight': 0.025,
        'kpi_target': 24.0,
        'kpi_description': 'As per assigned team referral targets (2 per year)'},
    {   'role_code': 'bo_cash_teller',
        'kpi_code': 'bo_vic',
        'kpi_order': 7,
        'mapping_category': 'Group Synergies 5.0%',
        'kpi_weight': 0.025,
        'kpi_target': 48.0,
        'kpi_description': 'As per asigned team referral targets(4 per year)'},
    {   'role_code': 'bo_cash_teller',
        'kpi_code': 'bo_branch_audit_branch_audit',
        'kpi_order': 8,
        'mapping_category': 'Operational Excellence 55.0%',
        'kpi_weight': 0.1,
        'kpi_target': 1.0,
        'kpi_description': 'Annual audit score of 1.65'},
    {   'role_code': 'bo_cash_teller',
        'kpi_code': 'bo_branch_audit_resolution',
        'kpi_order': 9,
        'mapping_category': 'Operational Excellence 55.0%',
        'kpi_weight': 0.1,
        'kpi_target': 0.85,
        'kpi_description': 'Resolve 85% of Repeat finding'},
    {   'role_code': 'bo_cash_teller',
        'kpi_code': 'bo_operation_lossess',
        'kpi_order': 10,
        'mapping_category': 'Operational Excellence 55.0%',
        'kpi_weight': 0.1,
        'kpi_target': 0.0,
        'kpi_description': 'Nill operation losses/Cash differences'},
    {   'role_code': 'bo_cash_teller',
        'kpi_code': 'bo_cash_management',
        'kpi_order': 11,
        'mapping_category': 'Operational Excellence 55.0%',
        'kpi_weight': 0.25,
        'kpi_target': 0.0,
        'kpi_description': 'Accuracy of cash repatriated ..Nill CBK fines'},
    {   'role_code': 'bo_cash_teller',
        'kpi_code': 'bo_training_hours',
        'kpi_order': 12,
        'mapping_category': 'Staff Engagement 5.0%',
        'kpi_weight': 0.05,
        'kpi_target': 576.0,
        'kpi_description': 'Achieve training hours as per assigned target'},
    {   'role_code': 'bo_teller',
        'kpi_code': 'bo_casa',
        'kpi_order': 1,
        'mapping_category': 'Financials 15.0%',
        'kpi_weight': 0.075,
        'kpi_target': 48.0,
        'kpi_description': 'Open 4 funded accounts - Focus'},
    {   'role_code': 'bo_teller',
        'kpi_code': 'bo_branch_rtgs',
        'kpi_order': 2,
        'mapping_category': 'Financials 15.0%',
        'kpi_weight': 0.075,
        'kpi_target': 0.8,
        'kpi_description': '80% of RTGS transactions to be online'},
    {   'role_code': 'bo_teller',
        'kpi_code': 'bo_kyc',
        'kpi_order': 3,
        'mapping_category': 'Customer Experience 30.0%',
        'kpi_weight': 0.05,
        'kpi_target': 360.0,
        'kpi_description': 'KYC Update(Drive data clenup through KYC)'},
    {   'role_code': 'bo_teller',
        'kpi_code': 'bo_customer_feedback_nil_client_complaints',
        'kpi_order': 4,
        'mapping_category': 'Customer Experience 30.0%',
        'kpi_weight': 0.075,
        'kpi_target': 0.0,
        'kpi_description': 'Nil client complaints'},
    {   'role_code': 'bo_teller',
        'kpi_code': 'bo_customer_feedback_achieve_5_client_compliments',
        'kpi_order': 5,
        'mapping_category': 'Customer Experience 30.0%',
        'kpi_weight': 0.075,
        'kpi_target': 60.0,
        'kpi_description': 'Achieve 5 client compliments'},
    {   'role_code': 'bo_teller',
        'kpi_code': 'bo_nps',
        'kpi_order': 6,
        'mapping_category': 'Customer Experience 30.0%',
        'kpi_weight': 0.1,
        'kpi_target': 0.6,
        'kpi_description': 'Achieve a net promoter score of 60%'},
    {   'role_code': 'bo_teller',
        'kpi_code': 'bo_hfcb_properties_volume',
        'kpi_order': 7,
        'mapping_category': 'Group Synergies 5.0%',
        'kpi_weight': 0.025,
        'kpi_target': 24.0,
        'kpi_description': 'As per assigned team referral targets (2 per year)'},
    {   'role_code': 'bo_teller',
        'kpi_code': 'bo_vic',
        'kpi_order': 8,
        'mapping_category': 'Group Synergies 5.0%',
        'kpi_weight': 0.025,
        'kpi_target': 48.0,
        'kpi_description': 'As per asigned team referral targets(4 per year)'},
    {   'role_code': 'bo_teller',
        'kpi_code': 'bo_branch_audit_branch_audit',
        'kpi_order': 9,
        'mapping_category': 'Operational Excellence 45.0%',
        'kpi_weight': 0.1,
        'kpi_target': 1.0,
        'kpi_description': 'Annual audit score of 1.65'},
    {   'role_code': 'bo_teller',
        'kpi_code': 'bo_operation_lossess',
        'kpi_order': 10,
        'mapping_category': 'Operational Excellence 45.0%',
        'kpi_weight': 0.1,
        'kpi_target': 0.0,
        'kpi_description': 'Nill operation losses/Cash differences'},
    {   'role_code': 'bo_teller',
        'kpi_code': 'bo_trx_productivity',
        'kpi_order': 11,
        'mapping_category': 'Operational Excellence 45.0%',
        'kpi_weight': 0.25,
        'kpi_target': 43.0,
        'kpi_description': 'Teller Transactions as per Target'},
    {   'role_code': 'bo_teller',
        'kpi_code': 'bo_training_hours',
        'kpi_order': 12,
        'mapping_category': 'Staff Management 5.0%',
        'kpi_weight': 0.05,
        'kpi_target': 576.0,
        'kpi_description': 'Achieve training hours as per assigned target'},
    {   'role_code': 'bo_rbo',
        'kpi_code': 'bo_casa',
        'kpi_order': 1,
        'mapping_category': 'Process and Controls 85.0%',
        'kpi_weight': 0.3,
        'kpi_target': 360.0,
        'kpi_description': 'Work on 30 accounts per day.'},
    {   'role_code': 'bo_rbo',
        'kpi_code': 'bo_account_opening_pb',
        'kpi_order': 2,
        'mapping_category': 'Process and Controls 85.0%',
        'kpi_weight': 0.15,
        'kpi_target': 1.0,
        'kpi_description': 'PB AO TAT OF 1 Day'},
    {   'role_code': 'bo_rbo',
        'kpi_code': 'bo_account_opening_bb',
        'kpi_order': 3,
        'mapping_category': 'Process and Controls 85.0%',
        'kpi_weight': 0.15,
        'kpi_target': 1.0,
        'kpi_description': 'BB AO TAT of 1 Day'},
    {   'role_code': 'bo_rbo',
        'kpi_code': 'bo_rbo_account_errors',
        'kpi_order': 4,
        'mapping_category': 'Process and Controls 85.0%',
        'kpi_weight': 0.1,
        'kpi_target': 0.1,
        'kpi_description': 'Achieve less than 10% returns from governance on 35 rims actioned on.'},
    {   'role_code': 'bo_rbo',
        'kpi_code': 'bo_nps',
        'kpi_order': 5,
        'mapping_category': 'Process and Controls 85.0%',
        'kpi_weight': 0.05,
        'kpi_target': 0.6,
        'kpi_description': 'Achieve a net promoter score of 60%'},
    {   'role_code': 'bo_rbo',
        'kpi_code': 'bo_tools_achieve_tat_of_1_day_for_mobile_banking_onboardi',
        'kpi_order': 6,
        'mapping_category': 'Process and Controls 85.0%',
        'kpi_weight': 0.05,
        'kpi_target': 1.0,
        'kpi_description': 'Achieve TAT of 1 day for mobile banking onboarding.'},
    {   'role_code': 'bo_rbo',
        'kpi_code': 'bo_operation_lossess',
        'kpi_order': 7,
        'mapping_category': 'Process and Controls 85.0%',
        'kpi_weight': 0.05,
        'kpi_target': 0.0,
        'kpi_description': 'Nill tolerance on operational losses as a result of account opening'},
    {   'role_code': 'bo_rbo',
        'kpi_code': 'bo_hfcb_properties_volume',
        'kpi_order': 8,
        'mapping_category': 'Group Synergies 5.0%',
        'kpi_weight': 0.025,
        'kpi_target': 24.0,
        'kpi_description': 'As per assigned team referral targets (2 per year)'},
    {   'role_code': 'bo_rbo',
        'kpi_code': 'bo_vic',
        'kpi_order': 9,
        'mapping_category': 'Group Synergies 5.0%',
        'kpi_weight': 0.025,
        'kpi_target': 48.0,
        'kpi_description': 'As per asigned team referral targets(4 per year)'},
    {   'role_code': 'bo_rbo',
        'kpi_code': 'bo_leave_management',
        'kpi_order': 10,
        'mapping_category': 'Staff Management 10.0%',
        'kpi_weight': 0.05,
        'kpi_target': 12.0,
        'kpi_description': 'Ensure adherence to the leave policy'},
    {   'role_code': 'bo_rbo',
        'kpi_code': 'bo_training_hours',
        'kpi_order': 11,
        'mapping_category': 'Staff Management 10.0%',
        'kpi_weight': 0.05,
        'kpi_target': 576.0,
        'kpi_description': 'Achieve training hours as per assigned target'},
    {   'role_code': 'bo_cash_centre_teller',
        'kpi_code': 'bo_digital_activation',
        'kpi_order': 1,
        'mapping_category': 'Financials (25%) 25.0%',
        'kpi_weight': 0.05,
        'kpi_target': 1.0,
        'kpi_description': 'Digitally active customers (Branch Digital Active Score)'},
    {   'role_code': 'bo_cash_centre_teller',
        'kpi_code': 'bo_casa',
        'kpi_order': 2,
        'mapping_category': 'Financials (25%) 25.0%',
        'kpi_weight': 0.05,
        'kpi_target': 48.0,
        'kpi_description': 'Open 4 funded accounts- Focus'},
    {   'role_code': 'bo_cash_centre_teller',
        'kpi_code': 'bo_re_activation',
        'kpi_order': 3,
        'mapping_category': 'Financials (25%) 25.0%',
        'kpi_weight': 0.05,
        'kpi_target': 1.0,
        'kpi_description': 'Accounts activated (Branch dormancy score)'},
    {   'role_code': 'bo_cash_centre_teller',
        'kpi_code': 'bo_deposit_growth',
        'kpi_order': 4,
        'mapping_category': 'Financials (25%) 25.0%',
        'kpi_weight': 0.05,
        'kpi_target': 12000000.0,
        'kpi_description': 'Deposit of 1m per month'},
    {   'role_code': 'bo_cash_centre_teller',
        'kpi_code': 'bo_branch_audit_branch_audit',
        'kpi_order': 5,
        'mapping_category': 'Customer Experience (25%) 25.0%',
        'kpi_weight': 0.1,
        'kpi_target': 1.0,
        'kpi_description': 'Annual audit score of 1.65'},
    {   'role_code': 'bo_cash_centre_teller',
        'kpi_code': 'bo_account_opening_pb',
        'kpi_order': 6,
        'mapping_category': 'Customer Experience (25%) 25.0%',
        'kpi_weight': 0.05,
        'kpi_target': None,
        'kpi_description': 'PB AO TAT OF 1 Day'},
    {   'role_code': 'bo_cash_centre_teller',
        'kpi_code': 'bo_account_opening_sme',
        'kpi_order': 7,
        'mapping_category': 'Customer Experience (25%) 25.0%',
        'kpi_weight': 0.05,
        'kpi_target': None,
        'kpi_description': 'SME AO TAT of 5days'},
    {   'role_code': 'bo_cash_centre_teller',
        'kpi_code': 'bo_nps',
        'kpi_order': 8,
        'mapping_category': 'Customer Experience (25%) 25.0%',
        'kpi_weight': 0.05,
        'kpi_target': 0.75,
        'kpi_description': 'achieve a net promoter score of above 75%'},
    {   'role_code': 'bo_cash_centre_teller',
        'kpi_code': 'bo_branch_audit_cash_management',
        'kpi_order': 9,
        'mapping_category': 'Process & Controls 40.0%',
        'kpi_weight': 0.1,
        'kpi_target': 1.0,
        'kpi_description': 'Accuracy of cash repatriated ..Nill CBK fines'},
    {   'role_code': 'bo_cash_centre_teller',
        'kpi_code': 'bo_trx_errors',
        'kpi_order': 10,
        'mapping_category': 'Process & Controls 40.0%',
        'kpi_weight': 0.1,
        'kpi_target': 1.0,
        'kpi_description': 'Retracted cash refunded in 24 hrs'},
    {   'role_code': 'bo_cash_centre_teller',
        'kpi_code': 'bo_operation_lossess',
        'kpi_order': 11,
        'mapping_category': 'Process & Controls 40.0%',
        'kpi_weight': 0.1,
        'kpi_target': 1.0,
        'kpi_description': 'Nill ATM cash differences'},
    {   'role_code': 'bo_cash_centre_teller',
        'kpi_code': 'bo_pl_charge',
        'kpi_order': 12,
        'mapping_category': 'Process & Controls 40.0%',
        'kpi_weight': 0.1,
        'kpi_target': None,
        'kpi_description': 'Reduce P&L provisions as per target'},
    {   'role_code': 'bo_cash_centre_teller',
        'kpi_code': 'bo_npl',
        'kpi_order': 13,
        'mapping_category': 'Process & Controls 40.0%',
        'kpi_weight': 0.05,
        'kpi_target': None,
        'kpi_description': 'Reduce NPL ratio (Retail) as per target'},
    {   'role_code': 'bo_cash_centre_teller',
        'kpi_code': 'bo_leave_management',
        'kpi_order': 14,
        'mapping_category': 'Organization Capacity (People) (10%) 10.0%',
        'kpi_weight': 0.05,
        'kpi_target': 12.0,
        'kpi_description': 'Ensure adherence to the leave policy - develop annual leave schedule, '
                           'ensure staff go on leave as per the schedule and that no staff crosses '
                           'over with more than 5 days.'},
    {   'role_code': 'bo_cash_centre_teller',
        'kpi_code': 'bo_training_hours',
        'kpi_order': 15,
        'mapping_category': 'Organization Capacity (People) (10%) 10.0%',
        'kpi_weight': 0.05,
        'kpi_target': 576.0,
        'kpi_description': 'Ensure your teams achieve 48 training hours'},
    {   'role_code': 'bo_tl_rbo',
        'kpi_code': 'bo_casa',
        'kpi_order': 1,
        'mapping_category': 'Process and Controls 82.5%',
        'kpi_weight': 0.3,
        'kpi_target': 360.0,
        'kpi_description': 'Ensure account opening officers achieve and exceed their daily set '
                           'targets.'},
    {   'role_code': 'bo_tl_rbo',
        'kpi_code': 'bo_account_opening_pb',
        'kpi_order': 2,
        'mapping_category': 'Process and Controls 82.5%',
        'kpi_weight': 0.15,
        'kpi_target': 1.0,
        'kpi_description': 'PB AO TAT OF 1 Day'},
    {   'role_code': 'bo_tl_rbo',
        'kpi_code': 'bo_account_opening_bb',
        'kpi_order': 3,
        'mapping_category': 'Process and Controls 82.5%',
        'kpi_weight': 0.15,
        'kpi_target': 1.0,
        'kpi_description': 'BB AO TAT of 1 Day'},
    {   'role_code': 'bo_tl_rbo',
        'kpi_code': 'bo_rbo_account_errors',
        'kpi_order': 4,
        'mapping_category': 'Process and Controls 82.5%',
        'kpi_weight': 0.1,
        'kpi_target': 0.2,
        'kpi_description': 'Have less than 20% returns done from RBO to Branches (Follow up with '
                           'BOMs to reduce errors)'},
    {   'role_code': 'bo_tl_rbo',
        'kpi_code': 'bo_nps',
        'kpi_order': 5,
        'mapping_category': 'Process and Controls 82.5%',
        'kpi_weight': 0.05,
        'kpi_target': 0.6,
        'kpi_description': 'Achieve a net promoter score of 60%'},
    {   'role_code': 'bo_tl_rbo',
        'kpi_code': 'bo_operation_lossess',
        'kpi_order': 6,
        'mapping_category': 'Process and Controls 82.5%',
        'kpi_weight': 0.075,
        'kpi_target': 0.0,
        'kpi_description': 'Nill Tolerance on operational losses as a result of account opening'},
    {   'role_code': 'bo_tl_rbo',
        'kpi_code': 'bo_hfcb_properties_volume',
        'kpi_order': 7,
        'mapping_category': 'Group Synergies 5.0%',
        'kpi_weight': 0.025,
        'kpi_target': 24.0,
        'kpi_description': 'As per assigned team referral targets (2 per year)'},
    {   'role_code': 'bo_tl_rbo',
        'kpi_code': 'bo_vic',
        'kpi_order': 8,
        'mapping_category': 'Group Synergies 5.0%',
        'kpi_weight': 0.025,
        'kpi_target': 48.0,
        'kpi_description': 'As per asigned team referral targets(4 per year)'},
    {   'role_code': 'bo_tl_rbo',
        'kpi_code': 'bo_rbo_monthly_summ',
        'kpi_order': 9,
        'mapping_category': 'Staff Management 12.5%',
        'kpi_weight': 0.05,
        'kpi_target': 0.7,
        'kpi_description': 'Ensure 70% of Team scorecard is above 70%'},
    {   'role_code': 'bo_tl_rbo',
        'kpi_code': 'bo_leave_management',
        'kpi_order': 10,
        'mapping_category': 'Staff Management 12.5%',
        'kpi_weight': 0.025,
        'kpi_target': 12.0,
        'kpi_description': 'Ensure adherence to the leave policy'},
    {   'role_code': 'bo_tl_rbo',
        'kpi_code': 'bo_training_hours',
        'kpi_order': 11,
        'mapping_category': 'Staff Management 12.5%',
        'kpi_weight': 0.05,
        'kpi_target': 576.0,
        'kpi_description': 'Achieve training hours as per assigned target'}]


def seed(apps, schema_editor):
    ScKpi = apps.get_model("staff_management", "ScKpi")
    ScRole = apps.get_model("staff_management", "ScRole")
    ScRoleKpiMapping = apps.get_model("staff_management", "ScRoleKpiMapping")

    existing = set(ScRole.objects.filter(
        role_code__in=list(ROLES)).values_list("role_code", flat=True))
    if existing:
        print(f"\n  back-office scorecards: {len(existing)} role(s) already "
              f"configured - left alone.")
        return

    for code, name in ROLES.items():
        ScRole.objects.get_or_create(
            role_code=code,
            defaults={"role_name": name, "role_type": "IC",
                      "is_active": True})

    inactive = 0
    for row in KPIS:
        row = dict(row)
        reason = row.pop("not_configured_reason", "")
        ScKpi.objects.get_or_create(
            kpi_code=row.pop("kpi_code"),
            defaults={
                "kpi_rating_type": "prorate",
                "score_cap": "1.20",
                "is_active": not reason,
                "not_configured_reason": reason,
                "has_base_value": False,
                "is_increasing": True,
                "kpi_calculation_mode": "actual_over_target",
                **row,
            })
        if reason:
            inactive += 1

    start, end = date(YEAR, 1, 1), date(YEAR, 12, 31)
    for row in MAPPINGS:
        row = dict(row)
        ScRoleKpiMapping.objects.create(
            effective_from=start, effective_to=end,
            bonus_effective_from=start, bonus_effective_to=end,
            plan_category="p1", target_category="full_year", prorate=True,
            **row)

    print(f"\n  back-office scorecards: {len(ROLES)} roles, {len(KPIS)} KPIs "
          f"({inactive} naming a feed the template does not have), "
          f"{len(MAPPINGS)} mappings.")


def unseed(apps, schema_editor):
    """Nothing to undo - removing a desk's configuration to reverse a seed
    would destroy tuning this migration never made."""


class Migration(migrations.Migration):

    dependencies = [
        ("staff_management", "0030_mapping_description"),
    ]

    operations = [
        migrations.RunPython(seed, unseed),
    ]
