"""Who holds which back-office card - the workbook's own List sheet.

The ten cards seeded by 0031 are no use to anybody until the platform knows who
holds which, and a teller is not on ``branch_employee_dmc_data``: that table is
the SALES roster, keyed on sales code and carrying sales targets. These are
branch operations staff.

``employee_role_history`` is where this belongs and it already existed, with a
CRUD API and a CSV upload behind it - ``sales_code``, ``role_code``,
``start_date``, ``end_date``, ``role_status``. Nothing was writing to it. So
this seeds the List sheet into it rather than inventing a second roster, which
also means it can be corrected through the API when somebody moves branch
without waiting for a migration.

101 people across 8 of the ten cards. The role labels are the sheet's
own - BOM, CSO, CSO_UB, CSM_DB, Teller, Cash_Center, RBO, TL_RBO - and they are
mapped to card codes, not guessed:

* ``Cash_Center`` is the one cash-centre teller, so CASHTELLER_SCORECARD is
  read as that person's card;
* ``bo_cash_teller`` and ``bo_bom_cso`` have NOBODY on the List sheet. They are
  left with no holders rather than guessed onto the 41 tellers or the 25 BOMs.
  If somebody does hold them, a row in ``employee_role_history`` is all it
  takes.

The branch, zone and line manager are kept in ``notes`` because this table has
nowhere else for them and the card header wants them. ``staff_employee_data``
is the better long-term home for a person's branch; this is what is available
today without inventing a table.

Seed-only-if-empty for these role codes, like 0027 and 0031.
"""

from datetime import date

from django.db import migrations

YEAR = 2026

PEOPLE = [   {   'sales_code': 'EKN1329',
        'role_code': 'bo_bom',
        'staff_name': 'Eric Nguithi',
        'branch': 'Meru',
        'zone': 'Zone A',
        'line_manager': 'Annrita Mwirigi'},
    {   'sales_code': 'LMN1452',
        'role_code': 'bo_bom',
        'staff_name': 'Liza Muthoni Ndwiga',
        'branch': 'Thika',
        'zone': 'Zone A',
        'line_manager': 'Naomi Kagiri'},
    {   'sales_code': 'JMW516',
        'role_code': 'bo_bom',
        'staff_name': 'Joyce Wambugu',
        'branch': 'Mombasa',
        'zone': 'Zone B',
        'line_manager': 'Joyce Wambugu'},
    {   'sales_code': 'SKM1327',
        'role_code': 'bo_bom',
        'staff_name': 'Samuel Kibiti',
        'branch': 'Nyeri',
        'zone': 'Zone A',
        'line_manager': 'Samuel Kibiti'},
    {   'sales_code': 'FJK1799',
        'role_code': 'bo_bom',
        'staff_name': 'Faith Koima',
        'branch': 'Eldoret',
        'zone': 'Zone A',
        'line_manager': 'Weldon Korir'},
    {   'sales_code': 'WKM1248',
        'role_code': 'bo_bom',
        'staff_name': 'Washington Gicheha',
        'branch': 'Rehani',
        'zone': 'Zone C',
        'line_manager': 'Charles Munuve'},
    {   'sales_code': 'PFM1264',
        'role_code': 'bo_bom',
        'staff_name': 'Purity Morrison',
        'branch': 'Riverroad',
        'zone': 'Zone A',
        'line_manager': 'Silas Abudho'},
    {   'sales_code': 'CMK1268',
        'role_code': 'bo_bom',
        'staff_name': 'Christabel Muthoki Katumo',
        'branch': 'Westlands',
        'zone': 'Zone B',
        'line_manager': 'Elizabeth Musula'},
    {   'sales_code': 'MK1955',
        'role_code': 'bo_bom',
        'staff_name': 'Martin Kirimi',
        'branch': 'Embu',
        'zone': 'Zone A',
        'line_manager': 'Mary Muthoni'},
    {   'sales_code': 'JMK2006',
        'role_code': 'bo_bom',
        'staff_name': 'Jennifer Kiango',
        'branch': 'TRM',
        'zone': 'Zone A',
        'line_manager': 'Pheona Ondu'},
    {   'sales_code': 'JOO1695',
        'role_code': 'bo_bom',
        'staff_name': 'Jasper Ondari',
        'branch': 'TRM',
        'zone': 'Zone A',
        'line_manager': 'Pheona Ondu'},
    {   'sales_code': 'SAA1331',
        'role_code': 'bo_bom',
        'staff_name': 'Sylvia Ayiedza',
        'branch': 'Rongai',
        'zone': 'Zone A',
        'line_manager': 'Peter Mbuthia'},
    {   'sales_code': 'DAO1815',
        'role_code': 'bo_bom',
        'staff_name': 'Diana Osewe',
        'branch': 'Kisumu',
        'zone': 'Zone A',
        'line_manager': 'Gordon Aram'},
    {   'sales_code': 'VJK1459',
        'role_code': 'bo_bom',
        'staff_name': 'Veronica Karan',
        'branch': 'Nakuru',
        'zone': 'Zone A',
        'line_manager': 'Micah Kirwa'},
    {   'sales_code': 'GM1891',
        'role_code': 'bo_bom',
        'staff_name': 'Gideon Murimi Mugambi',
        'branch': 'Nanyuki',
        'zone': 'Zone A',
        'line_manager': 'Calvin Muchiri'},
    {   'sales_code': 'EMM1995',
        'role_code': 'bo_bom',
        'staff_name': 'Elizabeth Mutinda',
        'branch': 'Machakos',
        'zone': 'Zone A',
        'line_manager': 'Stephen Mutava'},
    {   'sales_code': 'NJK1425',
        'role_code': 'bo_bom',
        'staff_name': 'Nelly Jebiwott Kibet',
        'branch': 'Naivasha',
        'zone': 'Zone A',
        'line_manager': 'Nelly Jebiwott Kibet'},
    {   'sales_code': 'HK3101',
        'role_code': 'bo_bom',
        'staff_name': 'Hillary Kimchas',
        'branch': 'Buruburu',
        'zone': 'Zone A',
        'line_manager': 'Christopher Kibugi'},
    {   'sales_code': 'JOO3189',
        'role_code': 'bo_bom',
        'staff_name': 'James Oduor Okoth',
        'branch': 'Komarock',
        'zone': 'Zone A',
        'line_manager': 'Fredrick Mayaka'},
    {   'sales_code': 'MAO3167',
        'role_code': 'bo_bom',
        'staff_name': 'Mildred Ann Ogutu',
        'branch': 'Rehani',
        'zone': 'Zone C',
        'line_manager': 'Charles Munuve'},
    {   'sales_code': 'EAR3038',
        'role_code': 'bo_bom',
        'staff_name': 'Eugenia Rota Rota',
        'branch': 'Harambee',
        'zone': 'Zone B',
        'line_manager': 'Anthony Ombati'},
    {   'sales_code': 'JMM3214',
        'role_code': 'bo_bom',
        'staff_name': 'Jordan Munene Mutuku',
        'branch': 'Hurlingham',
        'zone': 'Zone B',
        'line_manager': 'Mwihaki Muiruri'},
    {   'sales_code': 'HC3302',
        'role_code': 'bo_csm_diaspora',
        'staff_name': 'Hilda Chemutai',
        'branch': 'Diaspora Banking',
        'zone': 'Diaspora Banking',
        'line_manager': 'Jennifer Kamoni'},
    {   'sales_code': 'RWM1670',
        'role_code': 'bo_cso',
        'staff_name': 'Rose Muthee',
        'branch': 'Nyeri',
        'zone': 'Zone A',
        'line_manager': 'Samuel Kibiti'},
    {   'sales_code': 'MNN2081',
        'role_code': 'bo_cso',
        'staff_name': 'Milka Njeri Njoroge',
        'branch': 'Nanyuki',
        'zone': 'Zone A',
        'line_manager': 'Calvin Muchiri'},
    {   'sales_code': 'HCS1419',
        'role_code': 'bo_cso',
        'staff_name': 'Henry Serem',
        'branch': 'Eldoret',
        'zone': 'Zone A',
        'line_manager': 'Weldon Korir'},
    {   'sales_code': 'JAO2078',
        'role_code': 'bo_cso',
        'staff_name': 'Juliana Adhiambo Okoth',
        'branch': 'Kisumu',
        'zone': 'Zone A',
        'line_manager': 'Gordon Aram'},
    {   'sales_code': 'SOM3223',
        'role_code': 'bo_bom',
        'staff_name': 'Sarah Okenyuri Mayienda',
        'branch': 'SameerPark',
        'zone': 'Zone B',
        'line_manager': 'Eric Weroh'},
    {   'sales_code': 'ASI3192',
        'role_code': 'bo_bom',
        'staff_name': 'Antony Siajabu',
        'branch': 'Kitengela',
        'zone': 'Zone A',
        'line_manager': 'Robert Waichigo'},
    {   'sales_code': 'DA3079',
        'role_code': 'bo_cso',
        'staff_name': 'DAHABO ABDI',
        'branch': 'Meru',
        'zone': 'Zone A',
        'line_manager': 'Annrita Mwirigi'},
    {   'sales_code': 'TWM3229',
        'role_code': 'bo_cso',
        'staff_name': 'Tabitha Muita',
        'branch': 'Naivasha',
        'zone': 'Zone A',
        'line_manager': 'Nelly Jebiwott Kibet'},
    {   'sales_code': 'JKK3227',
        'role_code': 'bo_bom',
        'staff_name': 'Joseph Kinuthia',
        'branch': 'Naivasha',
        'zone': 'Zone A',
        'line_manager': 'Nelly Jebiwott Kibet'},
    {   'sales_code': 'JOO3376',
        'role_code': 'bo_cso',
        'staff_name': 'Jack Osumba Omondi',
        'branch': 'Westlands',
        'zone': 'Zone B',
        'line_manager': 'Elizabeth Musula'},
    {   'sales_code': 'PID3366',
        'role_code': 'bo_cso',
        'staff_name': 'Peter Ibrae Dabasso',
        'branch': 'TRM',
        'zone': 'Zone A',
        'line_manager': 'Pheona Ondu'},
    {   'sales_code': 'LM3280',
        'role_code': 'bo_cso',
        'staff_name': 'Lynet Priscillar Mutwa',
        'branch': 'Kitengela',
        'zone': 'Zone A',
        'line_manager': 'Robert Waichigo'},
    {   'sales_code': 'RWW3529',
        'role_code': 'bo_cso',
        'staff_name': 'Rahab Wambui',
        'branch': 'left',
        'zone': 'Head Office',
        'line_manager': 'Reports Analytics'},
    {   'sales_code': 'KMK1960',
        'role_code': 'bo_cso',
        'staff_name': 'Keziah Kioria',
        'branch': 'Machakos',
        'zone': 'Zone A',
        'line_manager': 'Stephen Mutava'},
    {   'sales_code': 'LWK3596',
        'role_code': 'bo_cso',
        'staff_name': 'Liza Wamaitha Kamunyu',
        'branch': 'Thika',
        'zone': 'Zone A',
        'line_manager': 'Naomi Kagiri'},
    {   'sales_code': 'PS3507',
        'role_code': 'bo_cso',
        'staff_name': 'Pharace Simiyu Nyakuri',
        'branch': 'Nakuru',
        'zone': 'Zone A',
        'line_manager': 'Micah Kirwa'},
    {   'sales_code': 'JWK3142',
        'role_code': 'bo_cso',
        'staff_name': 'Jane Karathe',
        'branch': 'Rehani',
        'zone': 'Zone C',
        'line_manager': 'Charles Munuve'},
    {   'sales_code': 'KMM3379',
        'role_code': 'bo_cso',
        'staff_name': 'Kennedy Mue Mwanthi',
        'branch': 'Rongai',
        'zone': 'Zone A',
        'line_manager': 'Peter Mbuthia'},
    {   'sales_code': 'WWW3179',
        'role_code': 'bo_cso',
        'staff_name': 'Win Joy Mugabe',
        'branch': 'Hurlingham',
        'zone': 'Zone B',
        'line_manager': 'Mwihaki Muiruri'},
    {   'sales_code': 'BAS3755',
        'role_code': 'bo_cso',
        'staff_name': 'Berit Sulwe',
        'branch': 'left',
        'zone': 'Head Office',
        'line_manager': 'Reports Analytics'},
    {   'sales_code': 'EJS3782',
        'role_code': 'bo_cso',
        'staff_name': 'Emmy Sego',
        'branch': 'Rehani',
        'zone': 'Zone C',
        'line_manager': 'Charles Munuve'},
    {   'sales_code': 'SNG3787',
        'role_code': 'bo_cso',
        'staff_name': 'Samuel Gitundu',
        'branch': 'RiverRoad',
        'zone': 'Zone A',
        'line_manager': 'Silas Abudho'},
    {   'sales_code': 'ANM3404',
        'role_code': 'bo_cso_ub',
        'staff_name': 'Anne Nduku Muthama',
        'branch': 'Rehani',
        'zone': 'Zone C',
        'line_manager': 'Charles Munuve'},
    {   'sales_code': 'CA3780',
        'role_code': 'bo_cash_centre_teller',
        'staff_name': 'Christine Adhiambo',
        'branch': 'Rehani',
        'zone': 'Zone C',
        'line_manager': 'Charles Munuve'},
    {   'sales_code': 'VOO3746',
        'role_code': 'bo_cso',
        'staff_name': 'Victor Orwa',
        'branch': 'Mombasa',
        'zone': 'Zone B',
        'line_manager': 'Joyce Wambugu'},
    {   'sales_code': 'AMA3786',
        'role_code': 'bo_teller',
        'staff_name': 'Ahatha Ali',
        'branch': 'Rehani',
        'zone': 'Zone C',
        'line_manager': 'Charles Munuve'},
    {   'sales_code': 'CSS3532',
        'role_code': 'bo_cso',
        'staff_name': 'Christopher Shema',
        'branch': 'Harambee',
        'zone': 'Zone B',
        'line_manager': 'Anthony Ombati'},
    {   'sales_code': 'EA3473',
        'role_code': 'bo_teller',
        'staff_name': 'Everline Anyango',
        'branch': 'Naivasha',
        'zone': 'Zone A',
        'line_manager': 'Nelly Jebiwott Kibet'},
    {   'sales_code': 'IO3870',
        'role_code': 'bo_teller',
        'staff_name': 'Ivan Ombiru',
        'branch': 'RiverRoad',
        'zone': 'Zone A',
        'line_manager': 'Silas Abudho'},
    {   'sales_code': 'CWG3448',
        'role_code': 'bo_teller',
        'staff_name': 'Christine Wanjiku Gitonga',
        'branch': 'Nyeri',
        'zone': 'Zone A',
        'line_manager': 'Samuel Kibiti'},
    {   'sales_code': 'MJS3454',
        'role_code': 'bo_cso',
        'staff_name': 'Mary Jerop Selembu',
        'branch': 'SameerPark',
        'zone': 'Zone B',
        'line_manager': 'Eric Weroh'},
    {   'sales_code': 'JN3303',
        'role_code': 'bo_teller',
        'staff_name': 'Jane Njoki',
        'branch': 'TRM',
        'zone': 'Zone A',
        'line_manager': 'Pheona Ondu'},
    {   'sales_code': 'JN3465',
        'role_code': 'bo_teller',
        'staff_name': 'Joseph Gatundu',
        'branch': 'Harambee',
        'zone': 'Zone B',
        'line_manager': 'Anthony Ombati'},
    {   'sales_code': 'PM3810',
        'role_code': 'bo_cso',
        'staff_name': 'Phyllis Mutheu Peter',
        'branch': 'Hurlingham',
        'zone': 'Zone B',
        'line_manager': 'Mwihaki Muiruri'},
    {   'sales_code': 'LO3442',
        'role_code': 'bo_teller',
        'staff_name': 'Lorette Otieno',
        'branch': 'Hurlingham',
        'zone': 'Zone B',
        'line_manager': 'Mwihaki Muiruri'},
    {   'sales_code': 'FA3508',
        'role_code': 'bo_teller',
        'staff_name': 'Flora Aketch',
        'branch': 'Meru',
        'zone': 'Zone A',
        'line_manager': 'Annrita Mwirigi'},
    {   'sales_code': 'ENW3871',
        'role_code': 'bo_teller',
        'staff_name': 'Edwin Wangui',
        'branch': 'Embu',
        'zone': 'Zone A',
        'line_manager': 'Mary Muthoni'},
    {   'sales_code': 'BOO3571',
        'role_code': 'bo_teller',
        'staff_name': 'Brian Ojode',
        'branch': 'Eldoret',
        'zone': 'Zone A',
        'line_manager': 'Weldon Korir'},
    {   'sales_code': 'JN3581',
        'role_code': 'bo_cso',
        'staff_name': 'Jackson Njagi',
        'branch': 'Komarock',
        'zone': 'Zone A',
        'line_manager': 'Fredrick Mayaka'},
    {   'sales_code': 'BL3524',
        'role_code': 'bo_teller',
        'staff_name': 'Bruno Litiema',
        'branch': 'Mombasa',
        'zone': 'Zone B',
        'line_manager': 'Joyce Wambugu'},
    {   'sales_code': 'RN3878',
        'role_code': 'bo_teller',
        'staff_name': 'Revin Nyawade',
        'branch': 'Thika',
        'zone': 'Zone A',
        'line_manager': 'Naomi Kagiri'},
    {   'sales_code': 'JJN3756',
        'role_code': 'bo_cso',
        'staff_name': 'Janet Nabwire',
        'branch': 'Buruburu',
        'zone': 'Zone A',
        'line_manager': 'Christopher Kibugi'},
    {   'sales_code': 'WN3965',
        'role_code': 'bo_teller',
        'staff_name': 'Walter Nyongesa',
        'branch': 'Rongai',
        'zone': 'Zone A',
        'line_manager': 'Peter Mbuthia'},
    {   'sales_code': 'KRB3968',
        'role_code': 'bo_teller',
        'staff_name': 'Rebecca Koroso',
        'branch': 'Kisumu',
        'zone': 'Zone A',
        'line_manager': 'Gordon Aram'},
    {   'sales_code': 'BBO3980',
        'role_code': 'bo_teller',
        'staff_name': 'Belinda Ojiambo',
        'branch': 'Buruburu',
        'zone': 'Zone A',
        'line_manager': 'Christopher Kibugi'},
    {   'sales_code': 'RM3990',
        'role_code': 'bo_teller',
        'staff_name': 'Ronnie Migwi',
        'branch': 'Meru',
        'zone': 'Zone A',
        'line_manager': 'Annrita Mwirigi'},
    {   'sales_code': 'EMM3991',
        'role_code': 'bo_teller',
        'staff_name': 'Eric Mutuva',
        'branch': 'Nanyuki',
        'zone': 'Zone A',
        'line_manager': 'Calvin Muchiri'},
    {   'sales_code': 'WO4025',
        'role_code': 'bo_teller',
        'staff_name': 'Wendy Achieng',
        'branch': 'Eldoret',
        'zone': 'Zone A',
        'line_manager': 'Weldon Korir'},
    {   'sales_code': 'BE4022',
        'role_code': 'bo_teller',
        'staff_name': 'Billy Ekitela',
        'branch': 'Westlands',
        'zone': 'Zone B',
        'line_manager': 'Elizabeth Musula'},
    {   'sales_code': 'CAN3531',
        'role_code': 'bo_teller',
        'staff_name': 'Charline Audrey',
        'branch': 'SameerPark',
        'zone': 'Zone B',
        'line_manager': 'Eric Weroh'},
    {   'sales_code': 'SWK3992',
        'role_code': 'bo_teller',
        'staff_name': 'Sharon Wanjiru',
        'branch': 'Embu',
        'zone': 'Zone A',
        'line_manager': 'Mary Muthoni'},
    {   'sales_code': 'LNK3630',
        'role_code': 'bo_teller',
        'staff_name': 'Lee Kamau',
        'branch': 'Thika',
        'zone': 'Zone A',
        'line_manager': 'Naomi Kagiri'},
    {   'sales_code': 'SNK4010',
        'role_code': 'bo_teller',
        'staff_name': 'Shannon Naeku',
        'branch': 'Kitengela',
        'zone': 'Zone A',
        'line_manager': 'Robert Waichigo'},
    {   'sales_code': 'TK3764',
        'role_code': 'bo_teller',
        'staff_name': 'Tony Kakai',
        'branch': 'Naivasha',
        'zone': 'Zone A',
        'line_manager': 'Nelly Jebiwott Kibet'},
    {   'sales_code': 'EFB4102',
        'role_code': 'bo_teller',
        'staff_name': 'Emeka Bahati',
        'branch': 'Rehani',
        'zone': 'Zone C',
        'line_manager': 'Charles Munuve'},
    {   'sales_code': 'VKM4103',
        'role_code': 'bo_teller',
        'staff_name': 'Vincent Koome',
        'branch': 'Riverroad',
        'zone': 'Zone A',
        'line_manager': 'Silas Abudho'},
    {   'sales_code': 'JAW4106',
        'role_code': 'bo_teller',
        'staff_name': 'Jenta Wandera',
        'branch': 'Buruburu',
        'zone': 'Zone A',
        'line_manager': 'Christopher Kibugi'},
    {   'sales_code': 'CK4132',
        'role_code': 'bo_teller',
        'staff_name': 'Christine Kamande',
        'branch': 'Harambee',
        'zone': 'Zone B',
        'line_manager': 'Anthony Ombati'},
    {   'sales_code': 'BJM4144',
        'role_code': 'bo_teller',
        'staff_name': 'Brian Magothe',
        'branch': 'Nakuru',
        'zone': 'Zone A',
        'line_manager': 'Micah Kirwa'},
    {   'sales_code': 'SW4164',
        'role_code': 'bo_teller',
        'staff_name': 'Sylvia Wafula',
        'branch': 'Kisumu',
        'zone': 'Zone A',
        'line_manager': 'Gordon Aram'},
    {   'sales_code': 'FO4213',
        'role_code': 'bo_teller',
        'staff_name': 'Francis Ochieng',
        'branch': 'Westlands',
        'zone': 'Zone B',
        'line_manager': 'Elizabeth Musula'},
    {   'sales_code': 'DM4214',
        'role_code': 'bo_teller',
        'staff_name': 'Davies Mogare',
        'branch': 'Rongai',
        'zone': 'Zone A',
        'line_manager': 'Peter Mbuthia'},
    {   'sales_code': 'EM4215',
        'role_code': 'bo_teller',
        'staff_name': 'Evans Muthama',
        'branch': 'TRM',
        'zone': 'Zone A',
        'line_manager': 'Pheona Ondu'},
    {   'sales_code': 'MM4230',
        'role_code': 'bo_teller',
        'staff_name': 'Michael Mutiso',
        'branch': 'Machakos',
        'zone': 'Zone A',
        'line_manager': 'Stephen Mutava'},
    {   'sales_code': 'BCK3783',
        'role_code': 'bo_teller',
        'staff_name': 'Bob Waigwa',
        'branch': 'Komarock',
        'zone': 'Zone A',
        'line_manager': 'Fredrick Mayaka'},
    {   'sales_code': 'CA4241',
        'role_code': 'bo_teller',
        'staff_name': 'Clinton Alulu',
        'branch': 'Nyeri',
        'zone': 'Zone A',
        'line_manager': 'Samuel Kibiti'},
    {   'sales_code': 'ML4290',
        'role_code': 'bo_teller',
        'staff_name': 'Mildren Lila',
        'branch': 'Nakuru',
        'zone': 'Zone A',
        'line_manager': 'Micah Kirwa'},
    {   'sales_code': 'BG4291',
        'role_code': 'bo_teller',
        'staff_name': 'Brian Gikuri',
        'branch': 'Komarock',
        'zone': 'Zone A',
        'line_manager': 'Fredrick Mayaka'},
    {   'sales_code': 'JW4335',
        'role_code': 'bo_teller',
        'staff_name': 'John Wijass',
        'branch': 'Mombasa',
        'zone': 'Zone B',
        'line_manager': 'Joyce Wambugu'},
    {   'sales_code': 'DM3795',
        'role_code': 'bo_teller',
        'staff_name': 'David Maina',
        'branch': 'Rehani',
        'zone': 'Zone C',
        'line_manager': 'Charles Munuve'},
    {   'sales_code': 'RW4354',
        'role_code': 'bo_teller',
        'staff_name': 'Rebecca Wambua',
        'branch': 'Nanyuki',
        'zone': 'Zone A',
        'line_manager': 'Calvin Muchiri'},
    {   'sales_code': 'AJL3925',
        'role_code': 'bo_rbo',
        'staff_name': 'Atundo Longinus',
        'branch': 'Retail Banking',
        'zone': 'Retail Back Office',
        'line_manager': 'Samuel Muigai'},
    {   'sales_code': 'CNM3433',
        'role_code': 'bo_rbo',
        'staff_name': 'Caroline Ndunge',
        'branch': 'Retail Banking',
        'zone': 'Retail Back Office',
        'line_manager': 'Samuel Muigai'},
    {   'sales_code': 'EWG3175',
        'role_code': 'bo_rbo',
        'staff_name': 'Eva Wacu Gititi',
        'branch': 'Retail Banking',
        'zone': 'Retail Back Office',
        'line_manager': 'Samuel Muigai'},
    {   'sales_code': 'BN4018',
        'role_code': 'bo_rbo',
        'staff_name': 'Brian Njenga',
        'branch': 'Retail Banking',
        'zone': 'Retail Back Office',
        'line_manager': 'Samuel Muigai'},
    {   'sales_code': 'RMN3940',
        'role_code': 'bo_rbo',
        'staff_name': 'Ronkenolly Nyakwana',
        'branch': 'Retail Banking',
        'zone': 'Retail Back Office',
        'line_manager': 'Samuel Muigai'},
    {   'sales_code': 'DM3830',
        'role_code': 'bo_rbo',
        'staff_name': 'Dius Muraguri',
        'branch': 'Retail Banking',
        'zone': 'Retail Back Office',
        'line_manager': 'Samuel Muigai'},
    {   'sales_code': 'SNM1905',
        'role_code': 'bo_tl_rbo',
        'staff_name': 'Samuel Nduati Muigai',
        'branch': 'Retail Banking',
        'zone': 'Retail Back Office',
        'line_manager': 'Samuel Muigai'}]


def seed(apps, schema_editor):
    History = apps.get_model("staff_management", "EmployeeRoleHistory")

    codes = sorted({row["role_code"] for row in PEOPLE})
    if History.objects.filter(role_code__in=codes).exists():
        print("\n  back-office roster: already present - left alone.")
        return

    start, end = date(YEAR, 1, 1), date(YEAR, 12, 31)
    made = 0
    for row in PEOPLE:
        if not row["sales_code"]:
            continue
        _, created = History.objects.get_or_create(
            sales_code=row["sales_code"], role_code=row["role_code"],
            start_date=start,
            defaults={
                "end_date": end,
                "role_status": "permanent",
                # The card header wants a name, a branch and a line manager,
                # and this table has nowhere else to put them.
                "notes": (f'{row["staff_name"]} | {row["branch"]} | '
                          f'{row["zone"]} | {row["line_manager"]}'),
            })
        made += int(created)

    from collections import Counter
    counts = Counter(row["role_code"] for row in PEOPLE)
    print(f"\n  back-office roster: {made} of {len(PEOPLE)} people seeded "
          f"across {len(counts)} card(s) - "
          + ", ".join(f"{code} {n}" for code, n in sorted(counts.items())))


def unseed(apps, schema_editor):
    """Nothing to undo: removing a roster to reverse a seed would take out
    corrections made through the API since."""


class Migration(migrations.Migration):

    dependencies = [
        ("staff_management", "0031_seed_bo_scorecards"),
    ]

    operations = [
        migrations.RunPython(seed, unseed),
    ]
