from django.urls import path
from . import views

urlpatterns = [
    path("customers/", views.CustomerListView.as_view()),
    path("customers/search/", views.DynamicFilterCustomerListPaginatedDetailView.as_view()),
    path("customers/<str:rm_code>", views.RmCustomerListView.as_view()),
    path("customers/<int:pk>/", views.CustomerDetailView.as_view()),
    path("customers/<int:pk>/data", views.CustomerDataView.as_view()),
    path("customers/<int:pk>/ppc", views.CustomerPpcView.as_view()),
    path("customers/<int:pk>/deposits", views.CustomerDepositTrendsView.as_view()),
    path("customers/<int:pk>/loans", views.CustomerLoanTrendsView.as_view()),
    path("customers/<int:pk>/focus", views.CustomerFocusChartView.as_view()),
    path("customers/<int:pk>/feedback", views.CustomerFeedbackListView.as_view()),
    path("customers/<int:pk>/detail_deposits", views.CustomerAccountDetailsView.as_view()),
    path("customers/<int:pk>/detail_loans", views.LoanAccountDetailsView.as_view()),
    path("customers/revenue-list/", views.CustomersRevenueListView.as_view(), name="customers_revenue_list"),
    path("customers/revenue-list/search/", views.DynamicFilterCustomersRevenueListPaginatedView.as_view(), name="customers_revenue_list_search"),
    path("rm/", views.RmListView.as_view()),
    path("prospects/", views.ProspectsListView.as_view()),
    path("feedback/", views.FeedbackListView.as_view()),
    path("feedback_summ_by_lead/", views.FeedbackSummByLeadView.as_view()),
    path("feedback_summ_contactability/", views.FeedbackSummContactabilityView.as_view()),
    path("feedback_customers_not_contacted/", views.FeedbackCustomersNotContactedView.as_view()),
    path("feedback/<int:pk>/", views.FeedbackDetailView.as_view()),
    path("feedback/<int:pk>/history", views.CustomerFeedbackHistoryView.as_view()),
    path("customer_totals/", views.TotalCustomersView.as_view()),
    path("customer_totals/<str:rm_code>", views.RmTotalCustomersView.as_view()),
    path("deposit_trends/", views.RmDepositTrendsView.as_view()),
    path("deposit_trends/<str:rm_code>", views.RmDepositsView.as_view()),
    path("loan_trends/", views.RmLoanTrendsView.as_view()),
    path("rm_revenue/", views.RmRevenueView.as_view()),
    path("rm_revenue/<str:rm_code>", views.RmRevenueByCodeView.as_view()),
    path("total_summary/", views.TotalSummaryView.as_view()),
    path("current_customers/", views.CustomersYtdView.as_view()),
    path("new_customers/", views.NewCustomersYtdView.as_view()),
    path("new_customers_list/", views.NewCustomersYtdListView.as_view()),
    path("customer_per_segment/", views.CustomerPerSegmentView.as_view()),
    path("profile/", views.ProfileView.as_view()),
    path("userprofile/", views.UserProfileView.as_view()),
    path("salesCode/", views.SalesCodeView.as_view()),
    path("rmlist/", views.RmFullListView.as_view()),
    path("allocated/", views.RetailAllocatedPortfolioView.as_view()),
    path("allocated/<int:pk>/", views.RetailAllocatedPortfolioDetailView.as_view()),
    path("ppc/", views.RmPpcView.as_view()),
    # Fixed Deposits
    path("fixed_deposits/list/", views.FixedDepositListView.as_view(), name="fixed_deposit_list"),
    path("fixed_deposits/list/search/", views.SearchFixedDepositListView.as_view(), name="fixed_deposit_list_search"),
    path("fixed_deposits/rate_bands/", views.FixedDepositRateBandsByRmView.as_view(), name="fixed_deposit_rate_bands_by_rm"),
    path("fixed_deposits/expiry_timeline/", views.FixedDepositExpiryTimelineByRmView.as_view(), name="fixed_deposit_expiry_timeline_by_rm"),
    # IFRS Movement
    path("loans-mom-ifrs-movement/", views.LoansMomIfrsMovementListView.as_view(), name="loans-mom-ifrs-movement-list"),
    path("loans-mom-ifrs-movement/search/", views.LoansMomIfrsMovementFilterView.as_view(), name="loans-mom-ifrs-movement-filter"),
    path("loans-mom-ifrs-movement/by-cust-code-strategy/<int:cust_code_strategy>/", views.LoansMomIfrsMovementByCustCodeView.as_view(), name="loans-mom-ifrs-movement-by-cust-code"),
    path("loans-mom-ifrs-movement/by-lns-account/<str:lns_account>/", views.LoansMomIfrsMovementByLnsAccountView.as_view(), name="loans-mom-ifrs-movement-by-lns-account"),
    path("loans-mom-ifrs-movement/by-branch/<str:branch>/", views.LoansMomIfrsMovementByBranchView.as_view(), name="loans-mom-ifrs-movement-by-branch"),
    # Arrears
    path("loans-arrears/summary/", views.LoansArrearsSummaryByRmView.as_view(), name="loans_arrears_summary"),
    path("loans-arrears/list/", views.LoansArrearsAccountsListByRmView.as_view(), name="loans_arrears_list"),
    path("loans-arrears/list/search/", views.SearchLoansArrearsAccountsListByRmView.as_view(), name="loans_arrears_list_search"),
    path("loans-arrears/dpd_bucket/", views.LoansArrearsDpdBucketSummaryByRmView.as_view(), name="loans_arrears_dpd_bucket_summary_by_rm"),
    path("loans-arrears/loan_products/", views.LoansProductArrearsSummaryByRmView.as_view(), name="loans_arrears_product_summary_by_rm"),
    # Revenue
    path("rm_top_ftp_customers/", views.RmTopFtpCustomersView.as_view(), name="rm_top_ftp_customers"),
    path("rm_top_loan_loss_customers/", views.RmTopLoanLossCustomersView.as_view(), name="rm_top_loan_loss_customers"),
    path("rm_top_10_customers_per_income_category/", views.RmTop10CustomersPerIncomeCategoryView.as_view(), name="rm_top_10_customers_per_income_category"),
]
