# Generated by Django 6.0.5 on 2026-06-12 15:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientBrief',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('from_party', models.CharField(default='DIRECTOR, RETAIL BANKING', max_length=255)),
                ('to_party', models.CharField(default='GROUP CHIEF EXECUTIVE OFFICER', max_length=255)),
                ('subject', models.CharField(blank=True, help_text="Defaults to 'CLIENT BRIEF – <client_name>' when left blank.", max_length=255)),
                ('brief_date', models.DateField(default=django.utils.timezone.now)),
                ('contact_persons', models.TextField(blank=True, help_text="Client-side contacts, e.g. 'Eng. Joseph Kamau - CEO / CPA. Michael Kimotho – Finance Manager'.")),
                ('background', models.TextField(blank=True, help_text='Background narrative. Separate paragraphs with a blank line.')),
                ('key_responsibilities', models.TextField(blank=True, help_text='One responsibility per line — rendered as a bulleted list.')),
                ('budget_note', models.TextField(blank=True, help_text='Budget / revenue paragraph.')),
                ('opportunities', models.JSONField(blank=True, default=list, help_text='Ordered list of business opportunities, each {title, body}.')),
                ('prepared_by', models.CharField(blank=True, max_length=255)),
                ('rm_designation', models.CharField(blank=True, default='Relationship Manager', max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('signed', 'Signed')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_briefs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'client_briefs',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
    ]
