# Generated by Django 6.0.5 on 2026-05-18 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('body', models.TextField()),
                ('category', models.CharField(choices=[('deposits', 'Deposits'), ('loans', 'Loans'), ('customers', 'Customers'), ('revenue', 'Revenue'), ('collections', 'Collections'), ('risk', 'Risk'), ('performance', 'Performance')], max_length=20)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical'), ('positive', 'Positive')], default='info', max_length=10)),
                ('segment', models.CharField(blank=True, max_length=100, null=True)),
                ('branch', models.CharField(blank=True, max_length=100, null=True)),
                ('metric_value', models.DecimalField(blank=True, decimal_places=5, max_digits=30, null=True)),
                ('metric_delta', models.DecimalField(blank=True, decimal_places=5, max_digits=30, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'portfolio_insights',
                'ordering': ['-generated_at'],
                'managed': True,
                'indexes': [models.Index(fields=['category', 'generated_at'], name='portfolio_i_categor_b29aeb_idx'), models.Index(fields=['is_active', 'generated_at'], name='portfolio_i_is_acti_fb7f62_idx')],
            },
        ),
    ]
