# Generated by Django 4.2.20 on 2026-08-19 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gceo_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeRosterOverlay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('standard_department', models.CharField(blank=True, default='', max_length=120)),
                ('current_role', models.CharField(blank=True, default='', max_length=200)),
                ('previous_role', models.CharField(blank=True, default='', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, default='', max_length=150)),
            ],
            options={
                'verbose_name': 'Employee roster overlay',
                'db_table': 'employee_roster_overlay',
            },
        ),
    ]
